### PR TITLE
TSIG SOA query fix

### PR DESCRIPTION
**Pull request by frillip**
Previously the DNS RFC2136 module only used the TSIG key to update BIND9 zone, but did not use the key when querying for an authoritative SOA record. This caused problems when using the key as a component of an ACL to determine which view to use for a client.

By using the `use_tsig()` function on the SOA request, the use of the TSIG key is now consistent between these two steps, allowing the use of keys in ACLs.

## Pull Request Checklist

- [x] The Certbot team has recently expressed interest in reviewing a PR for this. If not, this PR may be closed due our limited resources and need to prioritize how we spend them.
- [x] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [x] Add or update any documentation as needed to support the changes in this PR.
- [x] Include your name in `AUTHORS.md` if you like.

### CODE REVIEW

**Comment by alexzorin** [comment]
Hello,

1. If Certbot sends unsolicited signatures, where not required by the view/query, will this cause any issues? For BIND, PowerDNS, other authoritative servers that implement DNSRFC2136? Is there any RFC which defines the behavior in that case?
2. Regarding the test failure, `dnspython`'s stubs are unfortunately inaccurate, so you would have to add:
    
    `# type: ignore[attr-defined]`

    in order to fix `mypy` failure.

**Comment by frillip** [comment]
Hi,

1.  It will generate a `NOTAUTH` RCODE response with a `BADKEY` TSIG error, but I don't think this is a problem because:

  - The same response will be generated if the key is incorrect when attempting to add the TXT record
  - The SOA query and the TXT update should go to the same place
  
The behaviour is defined by [RFC 8945](https://datatracker.ietf.org/doc/html/rfc8945), specifically [Section 5.2.1](https://datatracker.ietf.org/doc/html/rfc8945#section-5.2.1)

 2. Ok, I'll add the `# type: ignore[attr-defined]` workaround later today

**Comment by alexzorin** [comment]
I think I will need to find some time to test this PR against some common zone setups, [like this one](https://certbot-dns-rfc2136.readthedocs.io/en/stable/#id5). This change makes me a little nervous because what you've written seems to suggest that the above example would produce a `NOTAUTH` error.

**Review by alexzorin — APPROVED** [review]
Results of my testing:

- [x] In BIND9, as long as the key is recognized by the server, the query succeeds, even if the key is not actually part of any policy on the zone. This seems congruent with Section 5.2.1 linked above.
- [x] PowerDNS appears to have exactly the same behavior. 

This LGTM but I am going to ask for a second set of eyeballs to review this change. Thanks.

**Comment by frillip** [comment]
That's great news, thanks for double checking.

**Comment by warewolf** [comment]
Thanks for getting done what I could not: https://github.com/certbot/certbot/pull/9106

**Review by alexzorin — APPROVED** [review]
Just had to merge `master` to move the `CHANGELOG` entry. Happy to merge this now.

**Comment by benweeks2** [comment]
This commit breaks functionality with hidden master name server setups.

In such setups the slave does not have the ddns update tsig key but forward to the hidden master using BIND's allow-update-forwarding functionality.

This commit causes the slave to respond to the SOA query with NotAuth and causes certbot to exit

**Comment by alexzorin** [comment]
@frillip @warewolf if this PR is reverted, does https://certbot-dns-rfc2136.readthedocs.io/en/stable/#special-considerations-for-multiple-views-in-bind address your use cases, or not? Since this has caused a regression to existing setups, this change is probably getting reverted fully or partially, by next release. I need to understand your use cases and how they fit into the advice we have published.

**Comment by frillip** [comment]
@alexzorin Unfortunately not. The setup I have is a split-horizon configuration, with some records being available for specific views only. Configuring it as outlined there would expose all my internal only records.

I think the solution here is to add in a configuration option, either CLI or in the `.ini` config, for the SOA request. If set, we use the TSIG key for the SOA request, if not, don't use it.

I'll spend some time today looking at it, essentially this line needs to be wrapped in an if statement: [certbot-dns-rfc2136/certbot_dns_rfc2136/_internal/dns_rfc2136.py](https://github.com/certbot/certbot/blob/dc05b4da7a79bf33622ffb9d6b571c59b4415688/certbot-dns-rfc2136/certbot_dns_rfc2136/_internal/dns_rfc2136.py#L220)

**Comment by frillip** [comment]
@alexzorin I've done some more digging, with some more configuration on the BIND side of things, it _can_ work in split horizon, with some compromises:

 - You cannot use the same IP for both advertiser and resolver. If you have your internal name server set up to resolve queries from a zone in an hidden view, this prevents the `AA` flag appearing on the responses, which is what `certbot` is looking for, but allows DNSSEC validation to be done on the server, rather than relying on the clients.
 - Requires each zone to be configured in both (or more) views. Fine for a few zones perhaps, but less manageable the more are hosted.

@warewolf can you elaborate on your setup?

The above said, I still think that at least the option to use the TSIG key for the initial query is valid.

**Comment by warewolf** [comment]
@alexzorin Sorry, I'm disinclined to participate further here from past experiences with the certbot team.  #9106 was opt-in for signing the SOA via .ini config file setting.

@frillip I still appreciate you getting done what I could not.

**Comment by benweeks2** [comment]
> @alexzorin Unfortunately not. The setup I have is a split-horizon configuration, with some records being available for specific views only. Configuring it as outlined there would expose all my internal only records. Using the TSIG key in my external view configuration allows internally connected hosts to get certificates automatically, whilst maintaining their ability to access internal records in normal use:
> 
> `named.conf`:
> 
> ```
> acl "certbot_keys" {
>         key root-certbot;
>         key fqdn.here.com;
> };
> 
> view "external" {
>         match-clients { certbot_keys; !internal_hosts; any; };
>         zone "here.com" {
>                 type master;
>                 update-policy {
>                         grant "root-certbot" zonesub TXT;
>                         grant "fqdn.here.com" selfsub fqdn.here.com. TXT;
> .
> .
> .
> ```
> 
> I think the solution here is to add in a configuration option, either CLI or in the `.ini` config, for the SOA request. If set, we use the TSIG key for the SOA request, if not, don't use it.
> 
> I'll spend some time today looking at it, essentially this line needs to be wrapped in an if statement: [certbot-dns-rfc2136/certbot_dns_rfc2136/_internal/dns_rfc2136.py](https://github.com/certbot/certbot/blob/dc05b4da7a79bf33622ffb9d6b571c59b4415688/certbot-dns-rfc2136/certbot_dns_rfc2136/_internal/dns_rfc2136.py#L220)
> 
> Fortunately, @warewolf seems to have done most of the leg work here in his previous pull request!

The best way to achieve what you want is to create CNAME records to delegate to a challenge-authentication only subdomain as described [here](https://letsencrypt.org/docs/challenge-types/) and [here](https://www.eff.org/deeplinks/2018/02/technical-deep-dive-securing-automation-acme-dns-challenge-validation).

Of course for this to work with certbot, https://github.com/certbot/certbot/issues/6566 would have to implemented.

**Pull request merged**
