### PR TITLE
[Unix] (WIP) Create a framework for certbot integration tests

### PR DESCRIPTION
**Pull request by adferrand**
This PR proposes an industrialization of Certbot integration tests.

On top of the unit tests, there are several integration tests that test certbot and certbot-nginx plugin against an ad-hoc instance of Boulder, the software that run the ACME CA server of LetsEncrypt.

Theses scripts are written in bash, and are located respectively on `tests/certbot-integration-tests.sh` and `certbot-nginx/tests`. While theses tests do their job, I see several flaws in their construction.
* Bash is a scripting language, not a programming language like Python. If you can make already several abstractions with Bash, it is nothing in comparison with what can be done with Python, as of structured data, collection comprehension, context manager, generators, or whatever you can imagine. In fact, using Python lead to more robust codes, and better maintenance capabilities for tests. In particular when tests concern a project written also in Python. So the technical knowledge is settled.
* A really good effort is done to provide some typical test material, like pseudo-fixtures with `tests/integration/common.sh`. But again, this is Bash, and there is not match against the galaxy of features offered by the `pytest` project. Setup/teardown, fixtures, module instrospection, hook and so on. Not only to talk about the excellent pytest plugins available and used by the community, test reruns or code coverage. And like for Python, every unit test is written with unittest or pytest, so here again, the technical knowledge is here.
* Current integration tests are not run in parallel, and we know that integration tests are slow: more than 18 mins in fact, on TravisCI. Adding more tests would lead to an unacceptable time to get feedback from the CI.
* The association of theses tests with TravisCI in fact, is poor: a lot of specific code is required, out of `tox`, and the logs generated are, honestly, unusable. As everything is logged, no matter a test succeeded or failed, you have typically more than 23000 lines of logs. If a test fail in this, you will have a hard time to find what is going on.

In general, I believe more in the integration tests than in the unit tests to provide valuable insight for a CI. So I want to make them faster, more maintainable, better designed in general, and make them as easy to execute than the unit tests.

So this is PR is a complete rewrite of theses tests, using `pytest`, and all python techniques I know to ease the test env setup and the tests execution. Here are the general features:
* tests are now written in Python with `pytest`, giving all the good values of this framework: fixtures, assertion insights, modularization and so on
* migration to execute the integration tests on Windows is now possible (future PR) 
* thanks to all the `pytest` power, each test is know executed independently from each other: fixtures will handle the setup/teardown of all the context required to run Certbot
* on top of that, I have written a superset over `pytest` to offer a nice CLI accessible both to users and CI systems, and that makes sense for integration tests (like offering a definition of a test campaign, and so on)
*  tests can now be executed against either Boulder (V1/V2), or Pebble, specifically designed for integration tests
* integration in `tox`: running `tox -e integration` will setup and launch everything.
* and, finally, the most important: the tests are *parallelized*: it has been quite difficult, because to maintain the containerization between tests, several ACME CA servers need to be setup on-demand. But thanks to Docker, pytest and its fixtures, and all high end Python capabilities, it has been possible. So on TravisCI, the typical campaign that required 18 min before, can be executed in less than 8 min. This duration drops to 5 or 6 mins if Pebble is used. And as TravisCI offers only VM with 2 VCPUs, you can go even beyond with a proper dev machine: on a VM on my machine with 4 VCPUs, I go to 2.5. On the bare machine that have 8 CPUs, I cross the 2 min border.

Note that the logic of the integration test themselves is almost untouched, besides the necessary modifications to make them independent from each other.

I hope that this PR will make the integration tests a first class citizen on the daily developer workflow.

Final note about the packaging: the project is structure as a module `certbot_integration_tests`, inside a distribution name `certbot-ci`. This distribution is intended to host all the dev/test material that I would migrate in future PRs.

### CODE REVIEW

**Comment by adferrand** [comment]
cc @ohemorange @bmw

**Comment by ohemorange** [comment]
Some relevant conversation logs:

[2018-11-19 11:00:47] <adferrand[m]> bmw: Hello! It would like to know, do you have a good knowledge of Boulder and Pebble?
[2018-11-19 11:02:01] <bmw> adferrand[m]: A little bit.
[2018-11-19 11:02:19] <bmw> Why? What's up?
[2018-11-19 11:02:22] <ccppuu> I'm lurking here too if it helps!
[2018-11-19 11:03:03] <bmw> thanks ccppuu 
[2018-11-19 11:03:08] <adferrand[m]> Oh, ccppuu, I think I saw you in several discussions indeed ;)
[2018-11-19 11:03:11] <bmw> adferrand[m]: ccppuu is a developer on boulder and pebble
[2018-11-19 11:03:26] <adferrand[m]> Like, what I was just about to say ^^
[2018-11-19 11:03:48] <adferrand[m]> Perfect!
[2018-11-19 11:03:53] <bmw> ccppuu: adferrand[m] has been helping out with Certbot in his spare time and has been doing most of the work to make Certbot compatible with Windows
[2018-11-19 11:04:12] <ccppuu> Awesome! I saw you were poking at POST-as-GET support too
[2018-11-19 11:04:24] <adferrand[m]> And of course, it is about Windows ^^
[2018-11-19 11:04:40] <adferrand[m]> Yes indeed, I made the PR for the acme module
[2018-11-19 11:05:00] <adferrand[m]> So it is about the integration tests
[2018-11-19 11:05:42] <adferrand[m]> First, maybe more for bmw: there is a reason why certbot do not try the integration tests also against Pebble?
[2018-11-19 11:06:14] <bmw> adferrand[m]: See https://github.com/certbot/certbot/issues/6305
[2018-11-19 11:06:39] <adferrand[m]> And more for ccppu: I would like also to settle integration tests for certbot against an acme ca server on Windows
[2018-11-19 11:06:41] <ccppuu> Do you still have ACME v1 tests? That might be a blocker
[2018-11-19 11:07:09] <bmw> Yeah. Half of our integration tests are ACMEv1 tests.
[2018-11-19 11:07:10] <adferrand[m]> And tls-sni challenges.
[2018-11-19 11:07:46] <adferrand[m]> But with a good refactoring, I could extract the integrations tests that are relevant for an up-to-date acme v2
[2018-11-19 11:07:54] <ccppuu> adferrand[m]: Have you tried running Pebble on Windows? Does it explode? :-)
[2018-11-19 11:08:10] <adferrand[m]> Well, I did not tried yet
[2018-11-19 11:08:26] <ccppuu> Ok
[2018-11-19 11:08:30] <adferrand[m]> In theory, I would like to do something similar to the Unix part
[2018-11-19 11:09:09] <adferrand[m]> The idea is that AppVeyor as windows machines to run the CI system
[2018-11-19 11:09:13] <adferrand[m]> And they have docker on it
[2018-11-19 11:09:30] <adferrand[m]> Both Windows container and Linux container
[2018-11-19 11:09:49] <adferrand[m]> But Linux containers are quite experimental, and costly
[2018-11-19 11:10:02] <adferrand[m]> Windows containers are free however
[2018-11-19 11:10:24] <adferrand[m]> So I would like to build and run an acme server on a windows container, and run it
[2018-11-19 11:10:34] <ccppuu> Makes sense
[2018-11-19 11:10:38] <adferrand[m]> Boulder seems way to complex to make the transition
[2018-11-19 11:10:52] <adferrand[m]> But Pebble seems way more simple and quite suited for that
[2018-11-19 11:11:06] <adferrand[m]> There are official dockers with a go env
[2018-11-19 11:11:30] <adferrand[m]> That are available as native Windows containers.
[2018-11-19 11:12:07] <adferrand[m]> So is there a known blocker about building and running Pebble on Windows?
[2018-11-19 11:12:28] <ccppuu> In theory the Pebble code should be pretty platform independent but I've never tried :-) I have no experience building Go code on Windows generally
[2018-11-19 11:12:35] <adferrand[m]> I want to give it a try, but I would like to know if it is a dead end
[2018-11-19 11:12:59] <adferrand[m]> Seems quite platform independant thanks to the dockers
[2018-11-19 11:13:21] <adferrand[m]> Clearly oriented for the builds, if I follow the documentation
[2018-11-19 11:13:32] <ccppuu> I don't think its a dead end. I'd be interested in hearing if you run into any blockers. I'd be happy to try and help fix them
[2018-11-19 11:13:37] <adferrand[m]> So in theory, I have everything to build a go app with them
[2018-11-19 11:13:50] <adferrand[m]> OK great! So I will try!
[2018-11-19 11:14:26] <adferrand[m]> On Linux it was just so easy, you did not lie on the documentation, you can set up it really quickly ^^
[2018-11-19 11:14:47] <ccppuu> Glad to hear it! :-)
[2018-11-19 11:16:00] <adferrand[m]> So now bmw, then there is already a thinking about this as I see
[2018-11-19 11:16:24] <adferrand[m]> For POST-as-GET, I set up a Pebble integration tests
[2018-11-19 11:16:36] <adferrand[m]> On Linux, using the test suite ready for Boulder
[2018-11-19 11:16:50] <adferrand[m]> Working great, and blowing accordingly
[2018-11-19 11:17:06] <adferrand[m]> No acme v1, and no tls-sni
[2018-11-19 11:17:33] <adferrand[m]> And no bare get requests of course, only post-as-get
[2018-11-19 11:17:43] <adferrand[m]> As it was my primary concern.
[2018-11-19 11:18:06] <adferrand[m]> My idea know, is to rewrite the bash tests in python
[2018-11-19 11:18:19] <adferrand[m]> And more precisely, as tests for pytests
[2018-11-19 11:18:29] <adferrand[m]> To take fully advantage of this framework
[2018-11-19 11:19:00] <adferrand[m]> And have a plateform independant, integration test suite
[2018-11-19 11:19:12] <adferrand[m]> Available both for Pebble and Boulder
[2018-11-19 11:19:36] <adferrand[m]> I think we need to keep the Boulder tests, because Certbot needs to deal with legacy stuff
[2018-11-19 11:20:00] <adferrand[m]> But clearly running against Pebble will allow to anticipate any improvement on the acme protocol.
[2018-11-19 11:21:00] <bmw> I think that's a good idea!
[2018-11-19 11:21:28] <bmw> We probably want to pin the pebble version for most of our tests so a change there doesn't suddenly cause everything to fail.
[2018-11-19 11:21:45] <bmw> Having an unpinned version run as part of our test-everything tests would be nice though.
[2018-11-19 11:22:03] <bmw> And I agree that we need to continue testing against boulder.
[2018-11-19 11:22:05] <adferrand[m]> ccppuu: In your opinion, is it worth to run against Pebble in strict mode, or is it too much anticipation?
[2018-11-19 11:22:08] <adferrand[m]> Yes, like with Boulder
[2018-11-19 11:22:46] <adferrand[m]> It will solve a lot of things, to use pytest in fact
[2018-11-19 11:23:00] <adferrand[m]> How you setup teardown the acme server
[2018-11-19 11:23:18] <adferrand[m]> How you handle the logs output verbosity
[2018-11-19 11:23:20] <ccppuu> adferrand[m]: I would start by getting things nice & happy without -strict. Adding -strict is nice but it will mean your builds could break more often.
[2018-11-19 11:23:41] <adferrand[m]> How you define which tests is for which acme protocol version, and so the server behind it
[2018-11-19 11:24:27] <adferrand[m]> Yes indeed ccppuu. In the scope of a continuous integration test, it would be making the tests too unstable
[2018-11-19 11:24:54] <adferrand[m]> But as a recurrent tests, like test-everything approach for certbot, it make sense
[2018-11-19 11:25:03] <ccppuu> exactly
[2018-11-19 11:25:07] <adferrand[m]> It could even be a not required success
[2018-11-19 11:25:22] <adferrand[m]> Just to know when certbot is diverging from the future of acme
[2018-11-19 11:25:52] <ccppuu> Fingers crossed ACME will be an RFC soon and we won't have to add new things to -strict for a bit
[2018-11-19 11:26:12] <adferrand[m]> That would be great!

Two days later...

[2018-11-21 11:05:24] <adferrand[m]> bmw: There is something I do not understand in the integration tests
[2018-11-21 11:05:43] <bmw> what's that?
[2018-11-21 11:05:50] <adferrand[m]> It is how the test for a manual dns challenge is working
[2018-11-21 11:06:23] <adferrand[m]> It calls tests/manual-dns-auth.sh
[2018-11-21 11:06:50] <adferrand[m]> That make a POST request against http://localhost:8055/set-txt
[2018-11-21 11:07:13] <adferrand[m]> I do not see any service set up for that
[2018-11-21 11:07:32] <adferrand[m]> And I do not understand how boulder could validate against that
[2018-11-21 11:07:44] <adferrand[m]> Except if it is a test feature in Boulder itself
[2018-11-21 11:07:56] <adferrand[m]> But I do not see anything about that
[2018-11-21 11:08:09] <bmw> Ah! That's something set up by boulder.
[2018-11-21 11:08:14] <bmw> Here's documentation for it https://github.com/letsencrypt/boulder/blob/a6597b9f120207eff192c3e4107a7e49972a0250/test/challtestsrv/README.md.
[2018-11-21 11:11:29] <adferrand[m]> All right I see!
[2018-11-21 11:11:55] <adferrand[m]> I did not catch the relevant config lines in the docker-compose.yml
[2018-11-21 11:12:25] <adferrand[m]> OK, so it will work out of the box with Boulder. Now, I will try to do the same with Pebble.
[2018-11-21 11:13:05] <bmw> Yeah it's not very clear what we're doing in those scripts.
[2018-11-21 11:13:13] <bmw> We should probably add comments explaining it.
[2018-11-21 11:13:33] <bmw> And yeah. I've never played with Pebble, but if they don't have anything similar, it could be a little tricky.
[2018-11-21 11:14:19] <adferrand[m]> Yes it seems.
[2018-11-21 11:14:19] <bmw> Only having manual DNS tests against boulder could be OK as a starting point.
[2018-11-21 11:14:30] <adferrand[m]> Yes I think also.
[2018-11-21 11:14:54] <adferrand[m]> Do not worry about comments. I am rewriting everything, so I will take the occasion.
[2018-11-21 11:15:15] <adferrand[m]> Pytest is just the best test framework in the world ^^
[2018-11-21 11:15:32] <adferrand[m]> So easy to setup things that are really nasty with bash
[2018-11-21 11:15:59] <adferrand[m]> If you are interested, you can follow on certbot-ci branch on my fork
[2018-11-21 11:17:16] <bmw> Nice!
[2018-11-21 11:17:20] <bmw> Thanks for working on it.
[2018-11-21 11:17:24] <adferrand[m]> ccppuu do you have an idea to use challtestsrv with Pebble and validate dns challenges during a test?
[2018-11-21 11:21:21] <adferrand[m]> Your welcome bmw ^^ At one point, you need to build a against a real framework your integration tests, I think that porting them to be platform independant is a good occasion.
[2018-11-21 11:21:50] <bmw> Definitely.
[2018-11-21 11:22:05] <bmw> Not only does having a framework like pytest help a lot, using Python instead of bash is also much nicer most of the time.
[2018-11-21 11:25:49] <adferrand[m]> Indeed, like structured objects ^^
[2018-11-21 12:46:51] → eht joined (~eht@c-73-118-141-207.hsd1.wa.comcast.net)
[2018-11-21 14:46:48] <adferrand[m]> bmw?
[2018-11-21 14:46:59] <bmw> hello
[2018-11-21 14:47:13] <adferrand[m]> I was studying challtestsrv
[2018-11-21 14:47:58] <adferrand[m]> In theory, this tool should act as a dns server, in case of dns challenges, right?
[2018-11-21 14:49:02] <adferrand[m]> And Pebble has a dnsserver parameter, to specify which dns server to use to validate dns challenges
[2018-11-21 14:49:40] <adferrand[m]> So, if I setup a challtestsrv docker along pebble one, with docker-compose for instance
[2018-11-21 14:50:05] <adferrand[m]> I would have everything needed to make dns challenge integration tests
[2018-11-21 14:50:35] <bmw> Nice.
[2018-11-21 14:50:45] <bmw> That sounds good to me.
[2018-11-21 14:50:49] <adferrand[m]> Just have to make post requests on the relevant management port
[2018-11-21 14:51:01] <adferrand[m]> And it would work like with Boulder
[2018-11-21 14:51:22] <adferrand[m]> It is only in theory, if I understood correctly ^^
[2018-11-21 14:51:23] <bmw> I think Certbot and LE development is going to be a little quiet until next week with the holiday in the U.S., but I'd be interested in hearing what ccppuu thinks when he's around.
[2018-11-21 14:52:02] <bmw> I think a set up like this would be useful to other ACME clients that support DNS challenges for testing.
[2018-11-21 14:52:05] <adferrand[m]> Yes ^^
[2018-11-21 14:53:49] <bmw> With that in mind I think it's fine to either make a setup like this and we will potentially replace it later with something set up by Pebble or a tool the devs recommend we use with it.
[2018-11-21 14:54:12] <bmw> Or just wait to do manual DNS challenge testing with Pebble until we hear back.
[2018-11-21 14:54:36] <bmw> But the idea you proposed seems sane to me.
[2018-11-21 14:58:16] <adferrand[m]> Yes I will try, but not push to hard until a complete answer ^^

One day later...

[2018-11-22 05:41:03] <ccppuu> adferrand[m]: bmw: I'm OOO for the tail end of this week but I wanted to drop in quickly to say +1 to using challtestrv with Pebble as you described.
[2018-11-22 05:41:37] <ccppuu> adferrand[m]: I have 50% of a PR finished to move the challtestsrv package out of Boulder entirely and into Pebble's repo, making a `pebble` command and a `pebble-challtestsrv` command
[2018-11-22 05:42:04] <ccppuu> it'll work the same as it does in Boulder but its a better fit there. We heard from another client dev that wanted to use it but didn't want to pull it in along with Boulder's heavy deps
[2018-11-22 05:42:43] <ccppuu> Should make your life a little bit easier when that lands ~next week. Pebble will have everything you need in one place.
[2018-11-22 05:54:13] ⇐ ErikRose quit (~ErikRose@grinchcentral.com): Ping timeout: 245 seconds
[2018-11-22 06:22:03] <adferrand[m]> Alright thanks a lot ccppuu! Then I will use temporarily my approach to write my tests, and I will move to your integrated solution next week before submitting a PR.

Four days later...

[2018-11-26 10:56:04] <adferrand[m]> Hello bmw! Great news, I have finished to rewrite the integration tests of Certbot!
[2018-11-26 10:56:18] <bmw> That's awesome :)
[2018-11-26 10:56:23] <bmw> Thanks for doing that.
[2018-11-26 10:56:29] <adferrand[m]> Working both for Boulder and Pebble, in pure pytest python ^^
[2018-11-26 10:56:59] <adferrand[m]> Aaaand go PARALLELIZE ALL THE THINGS
[2018-11-26 10:57:38] <adferrand[m]> Pytest is just awesome, tonight I will be able to run the tests with pytest-xdist
[2018-11-26 10:57:52] <bmw> How does that work with Certbot's lockfiles?
[2018-11-26 10:58:27] <adferrand[m]> They do not see them each others!
[2018-11-26 10:58:43] <adferrand[m]> They do not even run on the same acme server ^^
[2018-11-26 10:59:35] <NCommander> bmw, I'm doing apache right now, I'll have an upload within an hour
[2018-11-26 10:59:59] <adferrand[m]> And all the tests are independant from each other, you can run them in any order
[2018-11-26 11:00:53] <ccppuu> adferrand[m]: nice work!
[2018-11-26 11:01:19] <adferrand[m]> Hello ccppuu!
[2018-11-26 11:01:30] <adferrand[m]> Yes, it worked like you described, challengesrvtest is acting as a dns server
[2018-11-26 11:01:48] <adferrand[m]> So I can manipulate the DNS lookup from the local pebble instance as I want
[2018-11-26 11:01:52] <bmw> NCommander: Thanks! I'll try and test today but at the very least I can do it in the next few days.
[2018-11-26 11:02:18] <NCommander> adferrand[m], I have a set of handy tools that can create a fake root zone and whatever TLD/SLDs you want
[2018-11-26 11:02:22] <NCommander> might be useful for DNS testing
[2018-11-26 11:05:01] <adferrand[m]> Thanks NCommander! I could be interested to run some certbot dns plugin integration tests ^^
[2018-11-26 11:05:33] <NCommander> adferrand[m], it's very rough around the edges, but lets you do DNSSEC and publish CAA records as well
[2018-11-26 11:05:45] <NCommander> adferrand[m], https://github.com/NCommander/idn-root-zone

**Comment by adferrand** [comment]
I understand @ohemorange. Will figure out to simplify the code readability. But before anything, I did not put the comments yet!

I was planning to do that quickly, but I did not have the time. I will do that tomorrow.

**Comment by adferrand** [comment]
So @ohemorange, here is my elaborated response.

In understand that the code here is really hard to review. It has, as a very specific characteristic compared to my other PRs, and other PRs in Certbot in general, to be a plain thousand lines of totally new code. It is not like modifying a class, or some methods, then propagate their impact to the all objects that call it.

Here, it is just a new piece of software, that uses the existing integration tests as an operational specification, but that is technically totally different. We were talking about some huge bash scripts, it is now a huge python software.

What I mean here, is that I need to be extremely strict about my documentation, to allow people to understand what is going on. It means also that I will need to provide substantial guidance for the code review.

However, I mean also that the existing code, as a classic approach in code review to make a comparison between old code and new code, will be of very limited use for you here. It is just not the same thing. The only substantial thing that the bash scripts provide here, is, as I said, the operational specification of what needs to be tested. More about that later.

So I could split the PR, but I think it will be counterproductive in this situation. First, splitting should allow to mutate a part without the other, and make possible to compare the mutate part with the existing one. But as I said, here, the comparison is of very limited interest. And second, splitting would require intermediate code to make new part work with old parts. But as they are really different, this intermediate code will be huge and cumbersome. And it is a garbage, as this intermediate code should disappear once everything have been migrated. So we will end up to review code that add complexity before removing it.

**Comment by adferrand** [comment]
All things said, I think the review can be divided, without splitting effectively the code.

Indeed, my PR can be conceptually divided into three relatively independent blocks (all files are relative to `certbot-ci`:
* the setup of the integration tests, that implies to parse the arguments given on the CLI, mount Boulder/Pebble instances, preparing the pytest environment, and launch it: there are the files `setup.py`, `launch-integration-tests.py` and `certbot_integration_tests/utils/acme.py`
* the construction of the fixtures that make a repeatable and contained integration test environment for each test method: there are the files `certbot_integration_tests/certbot_tests/fixtures.py`, `certbot_integration_tests/certbot_tests/conftest.py`, `certbot_integration_tests/nginx_tests/fixtures.py`, `certbot_integration_tests/nginx_tests/conftest.py`, `certbot_integration_tests/nginx_tests/nginx_config.py` and `certbot_integration_tests/utils/misc.py`
* finally, the tests themselves, that are the files `certbot_integration_tests/certbot_tests/test_main.py`, `certbot_integration_tests/certbot_tests/assertions.py`, `certbot_integration_tests/nginx_tests/test_main.py`

Note that the fixtures and tests blocks can be divided themselves into two blocks for certbot core on one side, and certbot + nginx on the other side.

So what I propose you, is to make a code review for each block.
* I write all necessary comments, and provide a general description of the block architecture
* you make the code review of theses specific files, I make the corrections, and we loop until gaining the expected quality
* (if it requires to modify code in other blocks, I do it but you do not review it)
* then we move to the next block

**Comment by adferrand** [comment]
Last thing about what I just mentioned before: about bash scripts and what they represent in term of operational specifications.

It is a point where you will need to trust me in some extent. I mean the tests are just not the same. Before, it was a chain of tests written in bash, that would rely on each other in a particular order to test the logic. Now it is pytest tests, independent from each other, that focuses each on a particular aspect, can be run in any order, and provide way more advanced assertions thanks to python.

By construction, the code in the tests would break for the slightest divergence from what is expected. SO the very fact the tests execute successfully is a proof that the logic have been tested, and that tests are working. Furthermore, you will see that the code coverage is the same between the bash tests and the pytest tests.

**Comment by ohemorange** [comment]
Thanks for explaining all this Adrien!

I actually think that your suggestion of how the code is logically separated into chunks makes for a good way to split up the PR.

PR 1:

The first bullet:
> the setup of the integration tests, that implies to parse the arguments given on the CLI, mount Boulder/Pebble instances, preparing the pytest environment, and launch it: there are the files setup.py, launch-integration-tests.py and certbot_integration_tests/utils/acme.py

PR 2:


PR 2:

`certbot_integration_tests/certbot_tests/test_main.py`, and all the fixtures in their respective files needed to get that working

PR 3

PR 4:

`certbot_integration_tests/nginx_tests/test_main.py`, and all the fixtures in their respective files needed to get that working

the construction of the fixtures that make a repeatable and contained integration test environment for each test method: there are the files certbot_integration_tests/certbot_tests/fixtures.py, certbot_integration_tests/certbot_tests/conftest.py, certbot_integration_tests/nginx_tests/fixtures.py, certbot_integration_tests/nginx_tests/conftest.py, certbot_integration_tests/nginx_tests/nginx_config.py and certbot_integration_tests/utils/misc.py
finally, the tests themselves, that are the files certbot_integration_tests/certbot_tests/test_main.py, certbot_integration_tests/certbot_tests/assertions.py, certbot_integration_tests/nginx_tests/test_main.py

**Comment by bmw** [comment]
> First, splitting should allow to mutate a part without the other, and make possible to compare the mutate part with the existing one. But as I said, here, the comparison is of very limited interest.

@adferrand, I'm not sure if I totally understand the concern here. The comparison to existing code may have little value but there are other reasons to value in breaking PRs into smaller, logical pieces.

> splitting would require intermediate code to make new part work with old parts.

I don't think you need to do this. I checked with Erica and she's fine with the split PRs adding unused code until the final PR (or close to it) flips the switch to use the new integration test setup over the old one.

With this in mind, splitting up this PR as Erica describes doesn't seem too hard to me. Sure, git history might get a little weird, but since we squash PRs before merging them anyway, this doesn't seem like a big deal to me personally.

If I'm missing something though and splitting things up is a lot of work or you have other concerns about doing so, please share!

**Comment by adferrand** [comment]
I will let this PR open for now, to retro-integrate modifications made on each part of the splitted PRs, and see if the big picture is working.

I will close it when all the logic is merged from the splitted PRs.

**Comment by adferrand** [comment]
Merging my current version of the work, associated to the specifications given on https://docs.google.com/document/d/1G1b1psbvjg0mLdFXzo70eXQuyv3WsVVB9hv5ob4H7tg/edit?usp=sharing

**Comment by bmw** [comment]
@adferrand, thanks for putting the lines covered from tests/certbot-boulder-integration.sh in each of the part 3 PRs.

I want to suggest that @ohemorange and I to verify that when reviewing the PRs and then edit the section below in this comment to mention the lines we've merged equivalent tests for. At the end, we can see if any lines are missing and if there are, we can decide if we want to add tests for them.

#### Lines from tests/certbot-boulder-integration.sh covered by certbot-ci tests in master:

**Comment by bmw** [comment]
My suggestion above ended up not being necessary. I double checked this as I went through the split PRs and commented about any lines in tests/certbot-boulder-integration.sh without equivalents in certbot-ci.

**Comment by bmw** [comment]
Once the last piece of part 3 lands, we should be able to increase the minimum coverage percentage to at least 64 or we've missed something translating the tests to Python.

**Comment by bmw** [comment]
I think all pieces of this have now been merged right?

**Comment by adferrand** [comment]
Yes. Only diff here is either irrelevant modifications, or deletion of remaining bash scripts.

I close the PR.

**Pull request closed without merging**
