### PR TITLE
Remove CentOS 6 tests

### PR DESCRIPTION
**Pull request by bmw**
Fixes https://github.com/certbot/certbot/issues/8490.

Adrien had already done most of this in https://github.com/certbot/certbot/pull/8489, but that PR contains other changes that we wouldn't want to add the the point release branch. Because of this, I started with his work in that PR, squashed the commits, and cleaned things up.

This PR should be merged and not squashed to preserve authorship.

You can see tests passing with these changes https://dev.azure.com/certbot/certbot/_build/results?buildId=3094&view=results.

### CODE REVIEW

**Review by alexzorin — DISMISSED** [review]
There are some unit tests and fixtures related to CentOS 6 remaining in `certbot-apache`.

Did you want to remove those separately?

**Comment by adferrand** [comment]
> There are some unit tests and fixtures related to CentOS 6 remaining in `certbot-apache`.
> 
> Did you want to remove those separately?

In #8489 I did not remove them (and several useless code from certbot-auto) to avoid having too much big PRs and avoid unexpected failures.

**Comment by bmw** [comment]
Yes I would like to do that later. I think removing support for CentOS 6 (and Apache 2.2 more generally) requires a new major release of Certbot and I think we should keep the code testing it around until we've removed the user facing code in the plugin.

**Review by adferrand — APPROVED** [review]
OK, good for me!

**Pull request merged**
