### PR TITLE
No domains in cli.ini

### PR DESCRIPTION
**Pull request by schoen**
This is a small set of changes to the example `cli.ini` to mitigate a recurring bug where people list their domains there with `domains =` and then are unable to renew at all (due to the renewer rejecting `-d`). This tries to make clear that this is for systemwide defaults that apply to every cert on the system.

### CODE REVIEW

**Comment by schoen** [comment]
@SwartzCr, I seem to remember that there was somewhere else that I was also supposed to change this in the documentation; do you remember where?

**Comment by SwartzCr** [comment]
@schoen maybe you're referring to #4152 ? I'm not sure if that specifies anywhere else to share this info, but this PR should be mentioned in it

**Comment by SwartzCr** [comment]
I'm going to merge this since I don't see any issues with it. In the future I do hope to write a documentation section about the cli.ini file

**Comment by pde** [comment]
Trying to mitigate #4096 by documenting around it.

**Pull request merged**
