### PR TITLE
Use verbose=3 in sample dev cli.ini now that count is allowed in config

### PR DESCRIPTION
**Pull request by ohemorange**
This was enabled in https://github.com/bw2/ConfigArgParse/pull/216.

### CODE REVIEW

**Review by bmw — COMMENTED** [review]
I'm personally somewhat tempted to delete a lot of these example files since I don't think they're really used or maintained, but that's out of scope of this PR. Thanks a lot for finding that this is supported now and updating this.

When I made this change to my own cli.ini file though, I hit a problem. I think this value doesn't work with our "default detection" of our CLI parser. When I run `certonly --standalone`, Certbot crashes with the output:
```
...
Writing certificate to /etc/letsencrypt/live/bmw.cbtesting2.com/cert.pem.
Writing private key to /etc/letsencrypt/live/bmw.cbtesting2.com/privkey.pem.
Writing chain to /etc/letsencrypt/live/bmw.cbtesting2.com/chain.pem.
Writing full chain to /etc/letsencrypt/live/bmw.cbtesting2.com/fullchain.pem.
Writing README to /etc/letsencrypt/live/bmw.cbtesting2.com/README.
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: Unexpected value for verbose: '3'. Expecting 'true', 'false', 'yes', 'no', '1' or '0'
```
I'm not sure how you want us to handle this, but I personally think we shouldn't update this file while this bug exists. What do you think?

**Comment by ohemorange** [comment]
Delete and recreate your venv to update the version you're pulling in, it now works in mine.

**Comment by bmw** [comment]
`certbot certonly` is able to issue a certificate for you? On `master` with a new venv, I get the error described above.

To maybe clarify the issue though, the initial parsing works just fine for me and `verbose = 3` is clearly working, it just breaks when creating the lineage presumably due to default detection hacks.

**Comment by ohemorange** [comment]
Ahhhh what! I had that error then it disappeared, but now you're right, it shows up later on. That's so weird!

**Comment by ohemorange** [comment]
Deprecating in favor of #8900.

**Pull request closed without merging**
