### PR TITLE
Drop Python 3.6 support

### LINKED ISSUE #9205: Drop Python 3.6 support
We said we'd do this in our next release at https://github.com/certbot/certbot/pull/9160.

For reference, here's [the PR that did this for Python 3.5](https://github.com/certbot/certbot/pull/8206).

### PR DESCRIPTION
**Pull request by osirisinferi**
Fixes #9205.

Basically, I just used #8206 as a "template" for Python version removal.

The only thing I didn't really understand was the reference in `acme/acme/challenges.py` regarding some typing stuff to be changed once support for Python 3.6 was dropped. Above my pay grade :stuck_out_tongue:

Also, `typing.SupportsIndex` is available since 3.8, so that part is still needed I guess.

### CODE REVIEW

**Comment by adferrand** [comment]
No big deal about the TODO in challenge.py, it is just that Python 3.6 was not allowing to define some typing logic on abstract classes, and I can manage that in a dedicated PR once Python 3.6 support is dropped.

**Comment by osirisinferi** [comment]
Not sure why the linux-oldest-tests fail.. It's complaining about deprecated `collections` imports with e.g. `name = 'MutableMapping'` and `name = 'Mapping'`, but I don't see any imports of those kinds from `collections`?

**Comment by adferrand** [comment]
The error is not due to your code. It is caused by an old version of `pyparsing`  that is using a deprecated API in `collections`.

The thing is that the deprecation warning is caught by the Certbot unit tests and raised as an error accordingly to the policy defined by https://github.com/certbot/certbot/blob/master/pytest.ini which basically consider any warning as an error by default.

You can circumvent the issue by adding a line to the `pytest.ini` file under `filterwarning=` with something like `ignore:Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated:DeprecationWarning` + an appropriate inline comment.

Or we can just drop the oldest tests potentially as @bmw started to propose here https://opensource.eff.org/eff-open-source/pl/ci1usweaxpgpbpid7sikenrhcw ;)

**Comment by osirisinferi** [comment]
> The error is not due to your code. It is caused by an old version of `pyparsing` that is using a deprecated API in `collections`.
> 
> The thing is that the deprecation warning is caught by the Certbot unit tests and raised as an error accordingly to the policy defined by https://github.com/certbot/certbot/blob/master/pytest.ini which basically consider any warning as an error by default.

Hm, but why is my PR failing, but are other PRs fine with it? The deprecation warning mentioned in the current failing tests were already deprecated in Python 3.3.. I don't see why it would work when the "oldest" tests were using Python 3.6, but failing now with Python 3.7?



> You can circumvent the issue by adding a line to the `pytest.ini` file under `filterwarning=` with something like `ignore:Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated:DeprecationWarning` + an appropriate inline comment.

I'll probably do this :slightly_smiling_face: 



> Or we can just drop the oldest tests potentially as @bmw started to propose here https://opensource.eff.org/eff-open-source/pl/ci1usweaxpgpbpid7sikenrhcw ;)

I'll leave that to someone else :wink:

**Comment by bmw** [comment]
I started working on this when I assigned myself https://github.com/certbot/certbot/issues/9205. My work so far is in the [no-py36 branch](https://github.com/certbot/certbot/tree/no-py36).

In addition to the "oldest" test failures, there are [other failures](https://dev.azure.com/certbot/certbot/_build/results?buildId=5125&view=results) in our test farm tests. These will all need to be resolved before merging something like this.

For `test_sdists` test farm test, my plan was to look through the history of that script in GitHub and Mattermost to see why we created it in the first place. I think we can likely delete it or modify it to better fit our current distribution methods.

For the Apache test farm tests, I was leaning towards automatically installing a new version of python through something like `pyenv`.

Finally, for the oldest tests, while I would love to get rid of them, for now I was leaning towards keeping them to ensure that the dependencies we declare in `setup.py` are accurate, however, I was going to remove the comment about CentOS 8 and say that we can bump these dependencies however we want, whenever we want.

If anyone wants to work on any of these pieces, let me know so we can avoid duplicating work.

**Comment by osirisinferi** [comment]
> I started working on this when I assigned myself #9205.

Hm, missed the assignment in the issue. Or didn't grasp the fact that also meant you were going to write the code for it. Either one of those :slightly_smiling_face: 

I'll close my PR as everything here is, as far as I could tell, already done in the `no-py36` branch. Nothing to see here, move along now.

**Pull request closed without merging**
