### PR TITLE
Please add support for Devuan-based OSes

### PR DESCRIPTION
**Pull request by linuxitux**
It works. Tested on Devuan Jessie.

https://devuan.org/

### CODE REVIEW

**Comment by endelwar** [comment]
@linuxitux Please port your editing to certbot-auto too

**Comment by SwartzCr** [comment]
@linuxitux agreed, we've let this sit for a while, would you be willing to add this to certbot-auto as well as fix the merge conflicts?

**Comment by linuxitux** [comment]
I just send the pull request to certbot-auto:

https://github.com/certbot/certbot/pull/4515

**Comment by bmw** [comment]
Closing in favor of the newer #4515 because the changes have to be made in lockstep for tests to pass.

**Pull request closed without merging**
