### PR TITLE
Add certbot-dns-godaddy

### PR DESCRIPTION
**Pull request by Shinrai**
Similar to https://github.com/certbot/certbot/pull/4748 But updated for the current master

### CODE REVIEW

**Comment by schoen** [comment]
Thanks @Shinrai, is this building on #4748 or starting over from scratch?

@zjs, would you have time to take a look at this?

**Comment by sydneyli** [comment]
GoDaddy as a provider is actually now supported by Lexicon-- it may be worth porting this to use lexicon.

**Comment by adferrand** [comment]
@sydneyli, @Shinrai I coded the godaddy provider in Lexicon. Do not hesitate to ping me if you need something.

**Comment by m0namon** [comment]
Just a note that we're not accepting DNS plugins at the moment -- we want to make a decision on #6464, #6503, and #6504 first.

I'm going to close this PR since I think if we did want one, we'd probably prefer a version based on Lexicon. But realistically, we probably won't be able to give any feedback on it for a while. In the meantime, you are welcome to release this as 3rd party plugin like others have done. See https://github.com/coldfix/certbot-dns-netcup for one example of that.

**Pull request closed without merging**
