### PR TITLE
Only respect LE_PYTHON inside USE_PYTHON_3 if we know a user must have set it

### LINKED ISSUE #5388: Properly handling user set LE_PYTHONs for RHEL/CentOS 6
LE_PYTHON is always set during phase 2 because this variable is exported. Even worse, at this point we can't differentiate between the case where this value was set by the user and one where it was set by a previous version of the script. This is a problem because we won't know which Python executable to use to run Certbot and whether an unsupported value was manually set by the user or not. As the script is right now, this can cause us to create the venv using Python 2.6 or continue to use Python 2.6 to run fetch.py.

A couple potential fixes are:

Fix 1:
* Before we ever set --cb-auto-has-root or --le-auto-phase2, if LE_PYTHON is set, complain about deprecation and tell people to use a new var like CB_PYTHON.
* When bootstrapping for Python 3, overwrite/unset LE_PYTHON.

Fix 2:
* Quietly overwrite/unset LE_PYTHON

The properties I would like are:
 * If in the future, when someone manually sets LE_PYTHON to Python 2.6, we tell them their python is too old like we do for other versions.
* If we can't tell whether the value was user set or not, we ignore the value. There is a tradeoff to be made between printing a warning about this and just doing it quietly. By printing a warning, how many users will get a warning/cron email when most of them haven't set LE_PYTHON as it isn't formally documented anyway.

### PR DESCRIPTION
**Pull request by ohemorange**
Fixes #5388.

### CODE REVIEW

**Comment by bmw** [comment]
I don't think this meets this property that I wrote:

* If in the future, when someone manually sets LE_PYTHON to Python 2.6, we tell them their python is too old like we do for other versions.

In the `USE_PYTHON_3` case, unless we're upgrading, we never respect `LE_PYTHON`.

**Comment by ohemorange** [comment]
I interpreted that as "let's plan to make that change for future versions"; is that not the case?

**Comment by bmw** [comment]
My plan to make that happen though was to just change the min version number to 2.7. This approach requires us doing more work later than that, but if you can describe the changes we'd make to do it, I'm fine with it.

**Comment by ohemorange** [comment]
How do you feel about saving $PRE_UPGRADE_LE_VERSION to a file?

**Comment by bmw** [comment]
Proposal: At the top of phase 1, have code like:
```
if [ -z "$PRE_UPGRADE_LE_VERSION" ]; then
  export PRE_UPGRADE_LE_VERSION="$LE_AUTO_VERSION"
fi
```
and remove setting it elsewhere. If we rebootstrap during phase 2, we have to unset the value, but otherwise, I think with this and your `DeterminePythonVersion` changes, this works. I might also change the name to `PHASE_1_VERSION` but I don't care too much.

If you don't like this proposal though, I'm potentially fine with us putting a file somewhere, with my main concern being where to put the file (especially if haven't created the venv yet).

**Comment by bmw** [comment]
Closing in favor of #5402.

**Pull request closed without merging**
