### PR TITLE
Documentation update to certbot/main.py

### PR DESCRIPTION
**Pull request by jonasbn**
In relatation to issue #4736 this is the first shot at addition of missing documentation to a single file. There are a few things I have not yet understood about certbot and some Python aswell, so the work is not complete and the PR require a review.

I need to know if I am pulling in the right or wrong / direction and I have asked some questions on issue #4736. I might have addressed some of these based on assumptions. Please provide some feedback on this PR and let me know if you want me to continue the documentation work - and if so I just need a push in the right direction.

### CODE REVIEW

**Comment by jonasbn** [comment]
Questions addressed, peer review most welcome

**Comment by SwartzCr** [comment]
I think this looks good, but want to wait for @bmw to look at it to give a final okay.
The one thing I'd point out is that it seems like in some of the previous doc strings we have things of the form:
`:param str cert_path: path to cert`
rather than of the form
```
:param cert_path: path to cert
:type cert_path: str
```
I have a mild preference that these be uniform. Additionally it looks like some of the previous doc strings could use expanding, it might be worth it to look at the ones you didn't touch and make sure they look as thorough as the ones you wrote

**Comment by jonasbn** [comment]
Hi @SwartzCr 

Thanks for the feedback, much of the existing documentation is written on the short form

`:param str cert_path: path to cert`

I do however prefer the long form

```
:param cert_path: path to cert
:type cert_path: str
```

Makes it easier to scan using `ack`, `grep` or similar and with a shorter definition, et leaves more room for the descriptive string - the above example does not demonstrate this, but for classes etc it is more clear, but it is your call - I can change all definitions to the short form.

**Comment by SwartzCr** [comment]
Hmm - I wonder if @bmw has a preference
Also, sorry for having this sit in limbo for so long - hopefully we can get it merged soon, but feel free to pick up another issue while we're waiting to get this one merged

**Comment by jonasbn** [comment]
Hi @SwartzCr 

I have [other projects](https://github.com/jonasbn?tab=repositories) to work on so I am in no hurry. I am doing a PR per file as requested by @ynasser in #4736 and I almost have the next PR branch completed, but I will not make the PR until this one is addressed.

**Comment by SwartzCr** [comment]
Looks good to me! Thanks for doing all this work.
I think it'd be awesome if along with this you made type annotations that mypy could use for type checking

**Comment by jonasbn** [comment]
Hi @SwartzCr 

Thanks I will have a look at `mypy` annotations, please inform me of any relevant resources, since I am very much a Python _n00b_

**Comment by SwartzCr** [comment]
Sure!
Here's a good blog post by the zulip team introducing the concept: http://blog.zulip.org/2016/10/13/static-types-in-python-oh-mypy/
The official project website: http://mypy-lang.org/
And here's the official documentation: https://mypy.readthedocs.io/en/latest/

You can also look at the parent issue for this #4244 as well as the PRs that @toolness worked on (#4728 and #4707)
Also it's possible that either @toolness or @dokazaki would be interested in helping you get started with it since it seems that they were both pretty involved in the earlier mypy thread.
That should be a good start, but let me know if you want me to find you other resources!

**Pull request merged**
