### PR TITLE
Fix run Let's Encrypt on host-system with running containers inside [needs revision]

### PR DESCRIPTION
**Pull request by kharkevich**
System with OpenVZ, Virtuozzo, Docker is affected

In case with some software runned in container and listen required port

### CODE REVIEW

**Comment by kharkevich** [comment]
Errors in travis-ci is not related to my changes

**Comment by kharkevich** [comment]
Fix for #1515

**Comment by bmw** [comment]
Looking at Travis failures, I believe they are related to the changes in this PR. All failures are lint/unit test failures against `util.py`, the file modified in this PR.

**Comment by bmw** [comment]
This PR was marked as "needs revision" back in February and hasn't seen any updates. Due to this, I'm closing this issue, but if you'd like us to reconsider, please fix test failures and open a new PR.

**Pull request closed without merging**
