### PR TITLE
Disable certbot-auto upgrade on RHEL-like systems

### LINKED ISSUE #8637: Disable upgrades on RHEL systems in certbot-auto
This is the piece of the initial plan at https://github.com/certbot/certbot/issues/8615 for this release.

As part of this, I think we may want to remove the tests on Amazon Linux I added in https://github.com/certbot/certbot/pull/8623. Not only could this simplify the test code, but [Amazon Linux is past its EOL](https://aws.amazon.com/blogs/aws/update-on-amazon-linux-ami-end-of-life/).

### PR DESCRIPTION
**Pull request by adferrand**
Fixes #8637

### CODE REVIEW

**Comment by bmw** [comment]
Can you add a changelog entry about this and link to a run of these test farm tests passing?

**Comment by adferrand** [comment]
The full test suite is directly associated to the github checks if this PR.

**Comment by adferrand** [comment]
Changelog updated. To keep track, the associated full test suite is here: https://dev.azure.com/certbot/certbot/_build/results?buildId=3421&view=results

**Review by bmw — APPROVED** [review]
Ah I missed the initial test run in the GitHub checks.

This LGTM!

**Pull request merged**
