### PR TITLE
Pin back setuptools-rust

### PR DESCRIPTION
**Pull request by bmw**
This is a temporary workaround for https://github.com/certbot/certbot/issues/9111. I think the long term solution here requires more work, but this gets tests passing for now by using an old version of `setuptools-rust` (which is what we would have been doing anyway if all of our build dependencies were pinned).

`tools/requirements.txt` was updated by making the changes to `tools/pinning/current/pyproject.toml` and rerunning `repin.sh` from that directory.

The changes to `.pylintrc` were needed to make new versions of `pylint` happy. Pinning back `josepy` was needed because newer versions of `josepy` declare more accurate/strict types which makes our `mypy` tests unhappy. Adrien is fixing this in https://github.com/certbot/certbot/pull/9073 where you can see tests passing with `josepy==1.11.0`.

This isn't needed for our oldest pinnings because `cryptography` isn't new enough to use rust.

The failing test passed for me [here](https://dev.azure.com/certbot/certbot/_build/results?buildId=4783&view=logs&j=23275d9a-33b0-57f8-5f28-197fe2e5b9cd) but I kicked off a full test suite run to make sure nothing else broke at https://dev.azure.com/certbot/certbot/_build/results?buildId=4787&view=results.

EDIT: I fixed lint and mypy tests and hoping it all works now.

### CODE REVIEW

**Review by ohemorange — APPROVED** [review]
If you'd like to never be bothered by lint's style suggestions again, we can add `consider-using-in` and `consider-iterating-dictionary` to the `disable` list, but I just fixed the couple instances we had since they are actually reasonable suggestions. Otherwise, lgtm.

**Comment by bmw** [comment]
Thanks Erica. My last commit here should fix things.

I opened https://github.com/certbot/certbot/pull/9115 to disable the pylint checks we were fighting here.

**Review by ohemorange — APPROVED** [review]
Solving the open problem of discovering build dependencies to pin incrementally through failures :+1:

**Comment by bmw** [comment]
> Solving the open problem of discovering build dependencies to pin incrementally through failures 👍

Yep. Eventually we'll get there (although this problem nerd snipes me really hard so if anyone wants to talk about it more, let me know :smile: ).

**Pull request merged**
