### PR TITLE
mageia bootstrap [needs revision]

### PR DESCRIPTION
**Pull request by olivluca**
I added a simple script in bootstrap to use letsencrypt-auto with mageia.
I tested it in mageia 5 with the webroot plugin.

### CODE REVIEW

**Comment by akien-mga** [comment]
+1

**Comment by ErwanAliasr1** [comment]
Thanks for this patch @olivluca, I was looking to make it also.

If someone can merge it that's very useful for many.
Thanks

**Comment by doktor5000** [comment]
+1

**Comment by schoen** [comment]
Can another Mageia user confirm that this patch currently works for them?

**Comment by doktor5000** [comment]
@schoen Yep bootstrap works fine here. Although bootstrap/_mageia_common.sh needs to be made executable beforehand, obviously.

**Comment by alejandro-anv** [comment]
Bootstrap works OK, but only manual cert is available.

/letsencrypt-auto 
Updating letsencrypt and virtual environment dependencies.......
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt
No installers are available on your OS yet; try running "letsencrypt-auto certonly" to get a cert you can install manually

**Comment by bmw** [comment]
Sorry this PR has been sitting so long @olivluca. I'd be happy to merge this, but we're currently putting all community written bootstrap scripts behind a call to the `ExperimentalBootstrap` function in `letsencrypt-auto`. You can see examples of this in the code for Manjaro, Gentoo, etc. The reason for this is we want to make sure that all of our bootstrap scripts are well tested and maintained.

If you make this change, I'll merge this PR. After it's been used by people a bit, if anyone would like to take responsibility for maintaining the script, we could consider removing the call to `ExperimentalBootstrap` for mageia.

I'm appending [needs revision] to the title of this PR. Please remove it when you'd like another review. Thanks for the PR @olivluca!

**Comment by waclaw66** [comment]
It works for me. Mageia 5 x64

**Pull request merged**
