### PR TITLE
More thoroughly rename during `certbot rename`.

### PR DESCRIPTION
**Pull request by ohemorange**
Addresses #3998.

### CODE REVIEW

**Comment by ohemorange** [comment]
Fun fact! Because the plugin selector checks that the config files are valid, we now get a lineage duplicator for free. Congratulations us!

**Comment by ohemorange** [comment]
Ready for review! It probably only needs one person -- @ynasser, @bmw, do either of you have time?

**Comment by ynasser** [comment]
I can take a look within the next few days, but am not sure when. Definitely before end of day on Monday.

**Comment by ohemorange** [comment]
Hm, just noticed that coveralls is confused about what changed in this PR, so I'm ignoring it yelling at me for bad coverage.

**Pull request merged**
