### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by bmw**
this fixes the only dependabot alert for `tools/requirements.txt` (even though it doesn't seem particularly important for us)

the other dependabot alerts are for `tools/pinning/oldest/pyproject.toml` which i don't think we need to worry about https://github.com/certbot/certbot/blob/d2a13c55f2ba5083d7b1791573576bcaa6811070/tools/pinning/oldest/pyproject.toml#L1-L2

i plan to submit another PR with documentation and quality of life improvements related to this soon, but i wanted to make sure that any potentially necessary upgrades were handled in time for the release

### CODE REVIEW

**Review by wgreenberg — DISMISSED** [review]
thanks @bmw! feel free to merge once the CI stops yelling

**Comment by bmw** [comment]
unfortunately the test failures seem real here. the output from `snap_dns_run` isn't very helpful, but `snap_run` contains tracebacks like the following after a bit of cleanup:
```
An error occurred while fetching Certbot snap plugins: make sure the snapd service is running.    
Exiting abnormally:    
Traceback (most recent call last):     
File "/snap/certbot/x1/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn conn = connection.create_connection(    
File "/snap/certbot/x1/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):    
File "/snap/certbot/x1/usr/lib/python3.8/socket.py", line 918, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags):    
socket.gaierror: [Errno -3] Temporary failure in name resolution                                                                                                           
During handling of the above exception, another exception occurred:                                       
Traceback (most recent call last):    
File "/snap/certbot/x1/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen httplib_response = self._make_request(    
File "/snap/certbot/x1/lib/python3.8/site-packages/urllib3/connectionpool.py", line 416, in _make_request conn.request(method, url, **httplib_request_kw)    
File "/snap/certbot/x1/lib/python3.8/site-packages/urllib3/connection.py", line 244, in request super(HTTPConnection, self).request(method, url, body=body, headers=headers)    
File "/snap/certbot/x1/usr/lib/python3.8/http/client.py", line 1256, in request self._send_request(method, url, body, headers, encode_chunked)    
File "/snap/certbot/x1/usr/lib/python3.8/http/client.py", line 1302, in _send_request self.endheaders(body, encode_chunked=encode_chunked)                                                                                                                                    File "/snap/certbot/x1/usr/lib/python3.8/http/client.py", line 1251, in endheaders self._send_output(message_body, encode_chunked=encode_chunked)    
File "/snap/certbot/x1/usr/lib/python3.8/http/client.py", line 1011, in _send_output self.send(msg)    
File "/snap/certbot/x1/usr/lib/python3.8/http/client.py", line 951, in send self.connect()    
File "/snap/certbot/x1/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect conn = self._new_conn()    
File "/snap/certbot/x1/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f856c10d070>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution                                                                                                               
During handling of the above exception, another exception occurred:                                       
Traceback (most recent call last):    
File "/snap/certbot/x1/lib/python3.8/site-packages/requests/adapters.py", line 667, in send resp = conn.urlopen(    
File "/snap/certbot/x1/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen retries = retries.increment(    
File "/snap/certbot/x1/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='snapd', port=80): Max retries exceeded with url: /v2/connections?snap=certbot&interface=content (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f856c10d070>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))        
During handling of the above exception, another exception occurred:                                       
Traceback (most recent call last):    
File "/snap/certbot/x1/bin/certbot", line 8, in <module> sys.exit(main())    
File "/snap/certbot/x1/lib/python3.8/site-packages/certbot/main.py", line 19, in main return internal_main.main(cli_args)    
File "/snap/certbot/x1/lib/python3.8/site-packages/certbot/_internal/main.py", line 1864, in main cli_args = snap_config.prepare_env(cli_args)    
File "/snap/certbot/x1/lib/python3.8/site-packages/certbot/_internal/snap_config.py", line 69, in prepare_env raise e    
File "/snap/certbot/x1/lib/python3.8/site-packages/certbot/_internal/snap_config.py", line 57, in prepare_env response = session.get('http://snapd/v2/connections?snap=certbot&interface=content',    
File "/snap/certbot/x1/lib/python3.8/site-packages/requests/sessions.py", line 602, in get return self.request("GET", url, **kwargs)    
File "/snap/certbot/x1/lib/python3.8/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs)    
File "/snap/certbot/x1/lib/python3.8/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs)    
File "/snap/certbot/x1/lib/python3.8/site-packages/requests/adapters.py", line 700, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPConnectionPool(host='snapd', port=80): Max retries exceeded with url: /v2/connections?snap=certbot&interface=content (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f856c10d070>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))        
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log-v0gpg4hh/log or re-run Certbot with -v for more details. 
```
i'm not sure what's going on here. i think we should fix this, but i don't think we need to worry about it for the release next week after reading https://github.com/certbot/certbot/security/dependabot/69

i was planning to fix snap failure emails and improve some of the tooling and documentation around updating dependencies in general so if anyone else can take this new found problem (or some of the other certbot work i just mentioned), i'd appreciate it

**Comment by bmw** [comment]
i also just noticed that there are more immediately readable tracebacks at the top of the `snap_run` logs

**Comment by wgreenberg** [comment]
Turns out this was because of a sneaky deprecation (and breaking change) introduced in the latest `requests` minor version: https://github.com/psf/requests/pull/6710. Added a commit that switches our `http://snapd` adapter to the new API.

I noticed a bunch of other `requests` users with similar issues/confusion in that PR, and opened https://github.com/psf/requests/issues/6733 to describe the problem we had.

**Pull request merged**
