### PR TITLE
Handle merge conflicts in #3675

### PR DESCRIPTION
**Pull request by bmw**
Fixes merge conflict preventing #3675 from being merged, caused by #3651.

@ohemorange, @pde, or @schoen, I've reviewed #3675 and approved changes, but I also need a review from one of you to merge this PR (since we've turned on GitHub enforcing PRs are reviewed by another org member before they can be merged). I'd like this sooner rather than later because I want to make some follow up commits on the website repo.

### CODE REVIEW

**Comment by ohemorange** [comment]
Any chance this commit could go on the end of #3675 so that when we squash, master is always in a valid state?

**Comment by bmw** [comment]
I don't understand the concern. Why wouldn't `master` be in a valid state after merging this PR?

**Comment by ohemorange** [comment]
Oh, I meant under the assumption that the merge order goes the other way. Isn't this PR replicating most of the work from the other one? Why is it over here separately?

**Comment by bmw** [comment]
This PR is built on #3675. All commits in that PR are also here. I created this because I can't push to that PR and I didn't want to make the author deal with the problem.

GitHub **should** be smart enough to recognize this is the case and will automatically close #3765 when this PR is merged. If not, we can do that manually.

**Comment by ohemorange** [comment]
Ah, didn't realize you can't push to that PR (I find this strange?). But in that case, that sounds good!

**Pull request merged**
