### PR TITLE
Remove deprecated features:`--manual-public-ip-logging-ok`

### PR DESCRIPTION
**Pull request by ldlb9527**
Remove deprecated features:`--manual-public-ip-logging-ok`
#9988

### CODE REVIEW

**Review by bmw — CHANGES_REQUESTED** [review]
Thanks for the PR!

For added context, these two items from #9988 were described as something we could **maybe** remove because there may have been a reason we didn't remove them in the first place.

After playing with things a bit, I think we can remove `--manual-public-ip-logging`, but not `certbot-route53:auth`, at least not as it's done in this PR. Completely removing the plugin under the old `certbot-route53:auth` name breaks `certbot renew` for people who referenced the plugin that way which I don't think is worth it or appropriate.

If you want to remove the route53 changes here and add a changelog entry about the removal of `--manual-public-ip-logging`, I'll approve and merge this.

**Comment by ldlb9527** [comment]
@bmw 

> Thanks for the PR!
> 
> For added context, these two items from #9988 were described as something we could **maybe** remove because there may have been a reason we didn't remove them in the first place.
> 
> After playing with things a bit, I think we can remove `--manual-public-ip-logging`, but not `certbot-route53:auth`, at least not as it's done in this PR. Completely removing the plugin under the old `certbot-route53:auth` name breaks `certbot renew` for people who referenced the plugin that way which I don't think is worth it or appropriate.
> 
> If you want to remove the route53 changes here and add a changelog entry about the removal of `--manual-public-ip-logging`, I'll approve and merge this.

@bmw Thank you for your response,I have already made changes to the PR.

**Comment by bmw** [comment]
Thanks! Can you just add the changelog entry? Maybe something like:

> ``The `--manual-public-ip-logging-ok` command line flag was removed.``

under the "changed" section at the top?

**Comment by ldlb9527** [comment]
> Thanks! Can you just add the changelog entry? Maybe something like:
> 
> > `` The `--manual-public-ip-logging-ok` command line flag was removed. ``
> 
> under the "changed" section at the top?

Changelog entry for the removal of `--manual-public-ip-logging-ok` has been added.

**Review by bmw — APPROVED** [review]
thanks!

**Pull request merged**
