### PR TITLE
[Unix] Create a framework for certbot integration tests: PART 3e

### PR DESCRIPTION
**Pull request by adferrand**
Following #6821, this PR continues to convert certbot integration tests into certbot-ci.

This PR add tests covering checks on L430-447 in `tests/certbot-boulder-integration.sh`. Previous lines are covered with existing tests, or by #6946, #6947, #6948, #6949.

### CODE REVIEW

**Comment by adferrand** [comment]
Blocking on #6947 to get the methods `generate_csr` and `read_certificates` from `misc` module.

**Comment by bmw** [comment]
Actually, I'm going to skip reviewing this for now until #6947 is merged so I have something I can run here.

**Comment by adferrand** [comment]
Unblocking from #6947 as it has been merged.

**Comment by adferrand** [comment]
Indeed, Pebble has not support for OCSP in fact. I disabled the test for Pebble. The coverage on it stays beyond 64%.

**Pull request merged**
