### PR TITLE
acme: move setuptools from install_requires to setup_requires

### PR DESCRIPTION
**Pull request by sbraz**
## Pull Request Checklist

- [x] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [x] Add or update any documentation as needed to support the changes in this PR.
- [x] Include your name in `AUTHORS.md` if you like.

Hi,

I didn't touch the changelog because I wasn't sure this was worth listing as the majority downstream consumers won't notice it. Please let me know if I need to add an entry there.

The change may also apply to other components. Generally speaking, I don't think any of the code needs setuptools at runtime, it is just required during installation.

### CODE REVIEW

**Comment by bmw** [comment]
Hey @sbraz.

To remove `setuptools` as a runtime dependency, I think we'd at least (also) need to include `setuptools` in the `test` extras because acme's tests uses `pkg_resources` which is part of `setuptools`. If you want to make this change, feel free, however, if we're declaring the dependency in both places, I think we should store `setuptools>=x.y.z` in a variable and reuse it.

As for the other components, I think you're mostly right. I think there are some packages also relying on it for tests and `certbot` uses `pkg_resources` at runtime to find any Certbot plugins declared using the approach [here](https://packaging.python.org/guides/creating-and-discovering-plugins/#using-package-metadata). I assume that most of our plugins don't need a runtime `setuptools` dependency for this to work but I've never tested it.

**Comment by sbraz** [comment]
Hi @bmw, thanks for the reply. I completely overlooked the use of `pkg_resources`, I assumed everything could be done with `importlib.*` nowadays but I guess I was wrong.

> If you want to make this change, feel free, however, if we're declaring the dependency in both places, I think we should store `setuptools>=x.y.z` in a variable and reuse it.

Do you think this change is worth it? If so, I'll change my PR to add setuptools to `extras_require`. Otherwise, I'll simply close the PR.

> I assume that most of our plugins don't need a runtime setuptools dependency for this to work but I've never tested it.

All I know is that `console_scripts` can use `importlib.metadata`, but no idea about plugins.

**Comment by bmw** [comment]
> I assumed everything could be done with `importlib.*` nowadays but I guess I was wrong.

It probably can, but our code was initially written to support Python 2.6+ with us only have dropped Python 2.7 support in the last few months.

> Do you think this change is worth it? If so, I'll change my PR to add setuptools to `extras_require`. Otherwise, I'll simply close the PR.

Unless you personally have a use case where this significantly matters, I think we should just close the PR. Your approach is more correct, however, just requiring `setuptools` at runtime is simpler, users almost certainly have it anyway nowadays, and even if they don't, I doubt the extra dependency actually significantly matters.

**Comment by sbraz** [comment]
> Unless you personally have a use case where this significantly matters

Well I noticed that the Gentoo package required setuptools at runtime and I wondered why, but I don't think it's much of an issue, let's close this for now, thanks for the feedback.

**Pull request closed without merging**
