### PR TITLE
Completely deprecate certbot-auto

### LINKED ISSUE #8296: Fully deprecate certbot-auto
This is step 7 of https://docs.google.com/document/d/174ILmAfVlqWvYH9n8gkQnLc-FECiIsKpa2nZCxEklik/edit?usp=sharing. We should make sure to deprecate certbot-auto on Amazon Linux as part of the fix for this too.

This is blocked on https://github.com/certbot/certbot/issues/8358, however, we could get the PR ready/merged before then.

As part of this, we'll have to stop doing any testing of certbot-auto. This includes the tests using the Dockerfiles under `letsencrypt-auto-source` and our test farm tests. There may be other tests that need to be modified too.

### PR DESCRIPTION
**Pull request by adferrand**
Fixes #8296

What else to say? ;)

### CODE REVIEW

**Comment by adferrand** [comment]
I did not remove every code that could be with this deprecation. I made the minimal decent modifications for certbot-auto (as usual for this touchy script), and deleted only the assets directly linked to the tests removed because of this deprecation.

There is a lot more code to clean here, but I think what is done here is sufficient for a PR, and I plan to make dedicated PR(s) for the remaining parts. If someone disagree I can extend this PR though.

**Comment by adferrand** [comment]
Farm tests are passing (https://dev.azure.com/certbot/certbot/_build/results?buildId=3087&view=results), this PR is ready for a review.

I run a full test suite to double check.

**Comment by bmw** [comment]
Are you 110% sure that environment variables like `USE_PYTHON_3`, `INTERACTIVE_BOOTSTRAP`, and `RPM_USE_PYTHON_3` as set in the RHEL branches of this script no longer need to be set? I didn't take the time to dig into it myself yet, but I'd suspect at least `USE_PYTHON_3` needs to be set so it can run things like `fetch.py`.

Unless you're extremely confident, I'd personally prefer a more conservative change here that leaves these branches and environment variables largely unmodified.

**Comment by adferrand** [comment]
You may be right. Given the history of certbot-auto, and the fact that I do not want to break certbot for the nth time because of this script, I will take the most possible conservative approach.

**Comment by adferrand** [comment]
Ok, I made more conservative changes, changes for which I am 200% sure that is not used anymore. It is base on this branch that is executed after the boostrap definition phase:
```
if [ "$DEPRECATED_OS" = 1 ]; then
  Bootstrap() {
    error "Skipping bootstrap because certbot-auto is deprecated on this system."
  }
  unset BOOTSTRAP_VERSION
fi
```

From this I am sure that when `"$DEPRECATED_OS" = 1`, `Boostrap` and `BOOTSTRAP_VERSION` are overwritten/unset. So I removed that from the remaining branches when `DEPRECATED_OS` is set to `1`.

**Comment by bmw** [comment]
LGTM! The full test suite passed at https://dev.azure.com/certbot/certbot/_build/results?buildId=3127&view=results.

@ohemorange, are you able to give this a 2nd review when you get the chance? You were always the 3rd person helping on the quest to kill this beast before, so I think it'd be nice if you were able to help largely finish the job.

**Review by ohemorange — APPROVED** [review]
Also lgtm. I feel like we should say some final words or something...

**Comment by adferrand** [comment]
So long, and thanks for all the fish 🐟 !

**Pull request merged**
