### PR TITLE
Start sending coverage data to codecov

### PR DESCRIPTION
**Pull request by bmw**
You can see the page on codecov for this PR at https://app.codecov.io/github/certbot/certbot/pull/9544 but there isn't much there right now. I think that's due to not having data on `master` and although I'm not 100% sure on that, I think this PR is very conservative and getting it merged would make it easier for us to continue to play with things.

### CODE REVIEW

**Review by alexzorin — APPROVED** [review]
>I think that's due to not having data on master

Having a look around codecov, I agree. LGTM, hopefully this will work?

**Comment by alexzorin** [comment]
I got an email from Azure:

>[Build succeeded] pr-test-suite - certbot/certbot:master - certbot - c79a5d44

Not sure if it was related to this changeset.

**Comment by bmw** [comment]
Hmm...I think it may have been a fluke.

Right after this was merged, I started playing with the name of the pipeline. I changed it to `main-test-suite` since it also runs on commits to `master` now, but doing that has effects like changing the name of the status reported to GitHub which I also briefly changed before realizing it'd require tests on all PRs to be rerun.

In the end, I changed everything back, but I think things got weird during the transition (see https://github.com/certbot/certbot/runs/10888557520 for instance). Looking at https://learn.microsoft.com/en-us/azure/devops/organizations/notifications/manage-team-group-global-organization-notifications, I believe we have all notifications turn off, but if you get another one of these, please let me know and I'll dig into it.

**Comment by alexzorin** [comment]
I've still been getting emails, e.g. after merging https://github.com/certbot/certbot/pull/9554 a short while ago. Everything was enabled in https://dev.azure.com/certbot/_usersSettings/notifications so I've turned them off there. Maybe it was me logging into Azure the other day that triggered it, idk.

**Comment by bmw** [comment]
That's so weird. Since [it seems to only have affected you](https://opensource.eff.org/eff-open-source/pl/9xdapocw4bdojjxzc4tsugkm1e) and no other explanation is making sense to me right now, I'm going to assume it was you logging in, but regardless I'm still happy to help you fight Azure if you continue to have issues.

**Pull request merged**
