### PR TITLE
Improve non root error message [revision requested]

### PR DESCRIPTION
**Pull request by DownMoney**
This PR aims to add a more verbose message when running certbot without root privileges, as mentioned in #2734.

### CODE REVIEW

**Comment by pde** [comment]
@jsha recently made a change related to this; assigning him for review

**Comment by jsha** [comment]
Thanks! Under what conditions do you run into this issue? I think the change in https://github.com/certbot/certbot/pull/3164/files should cover the most common case, since we try to write to /var/log/letsencrypt.log very early on.

I think it definitely makes sense to have a similar message in multiple places. Can you pull out the message in #3164 to a shared variable to we can return the same message here?

**Comment by pde** [comment]
Since @DownMoney seems to have disappeared, assigning this to Brad who's doing a non-root error sweep for 0.9.0.

**Comment by DownMoney** [comment]
Sorry I was just moving house and only just now got the internet connection. I get the error message when running certbot on Mac without sudo If you still wan tI can update the error message.

**Comment by bmw** [comment]
Sorry this has sat around so long.

The common cases of error messages resulting from running Certbot without root were addressed in #3265. In general, we shouldn't be saying that Certbot needs root as it's possible to run the client without those privileges (see [this](https://certbot.eff.org/faq/#does-certbot-require-root-administrator-privileges)). Additionally, we shouldn't be telling people to use `sudo` which isn't present on all systems.

If you'd like to help further improve these messages, I wrote up what I think should be done in #3429. If you make the changes described there in this or another PR, I'd be happy to review.

**Comment by DownMoney** [comment]
Brad,

Ok sure I will have a look over the weekend and get back to you.

**Comment by jsha** [comment]
@DownMoney: Any update? @bmw: Is this still a live issue or has it been fixed elsewhere?

**Comment by bmw** [comment]
@jsha: see #3429

**Comment by bmw** [comment]
Closing as this PR hasn't seen any progress in quite some time. If you'd like to continue work on #3429, please open another PR when it's ready for review.

**Pull request closed without merging**
