### PR TITLE
Kill current snapcraft build when a "Chroot problem" is encountered

### PR DESCRIPTION
**Pull request by adferrand**
It appears that when a "Chroot problem" is encountered during a snapcraft remote build, the snapcraft process does not exit and so the entire build in Azure stales until the timeout is reached.

See https://dev.azure.com/certbot/certbot/_build/results?buildId=2975&view=logs&j=ca2aa996-3000-528f-2c15-4e35d6e2aaa9&t=6b8d8f83-a960-5842-1f93-f9b9a106898f for instance

This PR manages this situation by force-exiting the impacted snapcraft call when this error is detected in the output.

Technically this procedure may kill a snapcraft process while other builds are still running, since one snapcraft call handles builds of a given certbot component for _all_ architectures. However, I think it is ok because in this case, the snapcraft remote build will be relaunched as stated by our retry mechanism, and then the snapcraft remote build reconnects to the current builds running on snapcraft servers, which effectively resumes builds.

### CODE REVIEW

**Comment by adferrand** [comment]
Azure build with snap jobs is available here: https://dev.azure.com/certbot/certbot/_build/results?buildId=2977&view=results

**Comment by bmw** [comment]
It looks to me like something weird is going on here.

If you look at https://dev.azure.com/certbot/certbot/_build/results?buildId=2977&view=logs&j=12858cd7-3d40-52d0-d7b4-b054b2a1304c&t=3f748897-cdc5-5bc3-9bb1-36687aabe9ae, the build for `certbot-dns-route53` exits 3 times with status -9. For some reason, we report the build status as "Successfully built" after that though despite a route53 snap not being found in https://dev.azure.com/certbot/certbot/_build/results?buildId=2977&view=artifacts&pathAsName=false&type=publishedArtifacts. It's especially not great that neither the snap build or the DNS plugin tests caught this.

I think we should try and figure out what's going on here.

Also, my understanding based only on our experience is once the build reaches the "Chroot problem" state, every future build will be stuck in that state until either we manually delete the build off launchpad or the source changes. With this in mind, I think we may want to consider aborting the whole build and I think it'd be ideal if we could print some text at the end of the build to explain the problem and how to fix it.

**Comment by adferrand** [comment]
Note to myself to continue the work here.

**Comment by adferrand** [comment]
We have an infinite loop in that job, despite all builds marked as successful: https://dev.azure.com/certbot/certbot/_build/results?buildId=3336&view=logs&j=d7dde72a-62e2-55de-4246-ba0eba76b0d6

**Comment by bmw** [comment]
Is this ready for another review or are you still working on this?

**Comment by adferrand** [comment]
I am still working on it for now to figure out more what bad can happen during the build. But I think I will just finish that PR with the solely purpose of handling better "Chroot problem" by:
* killing the build when it is encountered
* display a message explaining what should be done to clean up the build stack (new source or build delete from Launchpad).

Then I will study more in depth the behavior of snapcraftctl as explained in Mattermost independently from this PR.

**Comment by adferrand** [comment]
OK PR is ready to review. Four actions here:
* added mypy annotations
* setup `XDG_CACHE_HOME` environment variables so the `.cache/snapcraftl/build` folders do not overlap each other when multiple `snapcraftctl` commands are launched
* kill a `snapcraftctl` instance when `Chroot problem` is encountered in the build status
* print a message to explain what to do after this kind of problem to clean up the build stack on Launchpad

**Comment by adferrand** [comment]
Azure pipeline with the snap jobs is here: https://dev.azure.com/certbot/certbot/_build/results?buildId=3560&view=results

**Review by bmw — APPROVED** [review]
LGTM!

**Pull request merged**
