### PR TITLE
Conditionally suggest the community forum on failure

### PR DESCRIPTION
**Pull request by bmw**
I wrote this in response to https://community.letsencrypt.org/t/ecdsa-certificates-by-default-and-other-upcoming-changes-in-certbot-2-0/177013/16.

### CODE REVIEW

**Comment by ohemorange** [comment]
So, this change will adjust the output in all cases where we originally referenced the community forum. But, some of these failures might be certbot failures and have nothing to do with the protocol at all, in which case that is the correct place to ask. I wonder if we can modify only some of them, such that things that are likely to be caused by local failures will still print the message.

**Comment by bmw** [comment]
So you'd like to still send people to the community forum if they're using another ACME server, but we think the problem is on Certbot's end? We could maybe do something like wrap network requests and only change the message about failures that occur there, but we'd also have to be careful around places like polling timeouts where the server may be the problem despite never getting an error response. Propagating this information to `certbot/certbot/_internal/log.py` where this message is usually printed may be a little tricky though...

I wonder if we couldn't/shouldn't just take a simpler approach though and say that if another ACME server is being used, we never send them to the community forum. This seems to me to satisfy the request on the community forum and avoids people making posts about using alternate CAs at all.

In the case of a Certbot problem unrelated to the use of a different CA, I'm not sure how a help post like this would be received:

> ...
> I ran this command: certbot ... --server https://acme.example.org
> 
> It produced this output: 😢
> ...

Even if it is a Certbot problem, the user still isn't using Let's Encrypt at which point I'm not sure the community forum is the right place per the community forum thread I linked to. What do you think? Do you still have a preference for your approach?

**Comment by ohemorange** [comment]
Well, I think it depends on the extent to which that's also the forum for certbot support, as well as LE support, which I think it is. But like maybe even just remove it from `_rollback_and_restart`, because that's more likely to be a local issue. In truth I saw the first two places and didn't realize the rest is plumbing and tests and thought we said it explicitly elsewhere.

**Comment by bmw** [comment]
> But like maybe even just remove it from _rollback_and_restart, because that's more likely to be a local issue.

I'd be OK with this approach (and updating the changelog entry to say something like "Certbot no longer recommends posting to https://community.letsencrypt.org for help if it crashes and an ACME server other than one run by Let's Encrypt is the potential cause.") although please check out the private Certbot channel in our public mattermost when you get a chance. After some comments from Alex, I proposed just closing this PR entirely.

I'm pretty open to whatever approach here. I was mainly motivated by a desire to cross another thing off our todo list.

**Comment by bmw** [comment]
I posted https://community.letsencrypt.org/t/ecdsa-certificates-by-default-and-other-upcoming-changes-in-certbot-2-0/177013/23 so I'm closing this.

**Pull request closed without merging**
