### PR TITLE
[Windows] Create a Certbot installer

### PR DESCRIPTION
**Pull request by adferrand**
There were installation methot for Certbot on Windows. The only way was to use `pip`.

But as it is said for Linux environment, `pip` is more a package manager for developpers, not for end users. On Linux, there is `certbot-auto` for that. However, it is planned to move to full packages for Linux distributions. So do Certbot on Windows.

Then this PR proposes a stable method to install Certbot on Windows for end users. In general, this means to be able to freeze an application and its dependencies, and provide a self-contained package to install the application. For Windows, two of the most known solutions to freeze an application are `pyinstaller` and `py2exe`. But theses solutions have a major drawback for me: they provide the application as a self-contained executable file.

Nobody on Windows, to get an application, downloads its executable and run it as is. Maybe some developpers or tech user, and even, if there is nothing better available. The real way to get an application on Windows is to install it: I mean, download an installer, launch it (with a UI or without), and let it deploy the application in one of the standard install paths, add entries to the Registry to know that the application is installed, add some shortcuts, and provide an uninstaller.

In fact, this is quite similar to what you expect from packages for Debian (`.deb`) or Red Hat (`.rpm`).

In that perspective, this PR uses the NSIS installer, one of the most used software to build Windows installers. NSIS is configured through a brilliant project called `pynists`: it orchestrates NSIS specifically to build an installer for a Python application. The built installer, when launched, do the following things:
* copy in the install path a full python distribution used exclusively for Certbot
* copy all Python requirements gathered from the `setup.py` procedure in the GitHub repository
* copy `certbot`, `acme` and all dns plugins
* pre-build python binary assets
* create a shortcut on the start menu to open a command line with administrator privileges (required to create symbolic links)
* register the application correctly in the Windows system
* prepare a procedure to uninstall Certbot
* and of course, expose `certbot` executable to the Windows command line, as on Linux, to be able to launch it as any CLI application.

The installer can be built by executing the Powershell script on `.\windows-installer\construct.ps1`. Administrator privileges, a python distribution and chocolatey need to be available. After the build, the NSIS installer is available in directory `windows-installer\build\nsis`. Its name is `certbot-[CERTBOT_VERSION]-win32_install.exe`. Only 32 bits installer, 64 bits is useless here.

Finally, the certbot Windows installer must be built and deployed taking advantage of the existing CI/CD system. To do that, `appveyor.yml` is improved: any tag in the form of `vX.X.X` (tags used to create a new stable certbot version) pushed to GitHub will trigger the NSIS installer build and deployment on AppVeyor. The deployment consists in pushing the NSIS installer on the relevant GitHub release, making it available for anyone: this is covered by the GitHub provider available on AppVeyor.

Currently the encrypted token registered in the `appveyor.yml` is for my forked repository. Once this PR is merged, `appveyor.yml` with an encrypted token for the Certbot GitHub repository. Two steps, for an admin owning the repository:
* on GitHub, under https://github.com/settings/tokens, create a token with the access `repo`
* encrypt the token in AppVeyor UI under Settings > Encrypt YAML
* copy the encrypted token content in `appveyor.yml`:
```
deploy:
  auth_token:
    secure: ENCRYPTED_TOKEN_CONTENT
```

Future steps:
* auto update from Certbot can be handled easily: if a procedure is built to detect a new version of the installer, it can be downloaded and executed silently. This will update every assets needed to run the new version of Certbot, including dependencies and the Python distribution itself
* as a stable installer is available, it is quite easy to provide Certbot through Chocolatey and Scoop, the most well-known packaging systems for Windows
* integration tests on the installer itself should be done
* finally, Certbot web site needs to be updated to advertise about the availability of Certbot on Windows, and provide an installation procedure that involves the build NSIS installer.

### CODE REVIEW

**Comment by bmw** [comment]
I was planning on holding off reviewing this until we were closer to encouraging users to test our Windows support, but if you'd prefer I reviewed it sooner rather than later, let me know!

**Comment by adferrand** [comment]
No it's OK. Once file lock mechanism, files permissions and windows integration tests are merged, we will talk about making windows support for certbot official.

**Comment by bmw** [comment]
We probably need something more complex than what is at this link, but I just came across this and hadn't seen it before: https://docs.python.org/3.7/distutils/builtdist.html#creating-windows-installers

Are you familiar with this?

**Comment by adferrand** [comment]
No, I was not aware of this capability from distutils, it did not appear in my initial review last year, maybe it is recent. When I used the pynsist solution we worked with the maintainer of pynsist, and one of the distutils to improve things, maybe some functionalities have been merged.

Anyway definitely I will test this solution!

**Pull request closed without merging**
