### PR TITLE
Add a Scaleway plugin

### PR DESCRIPTION
**Pull request by remyleone**
Be sure to edit the `master` section of `CHANGELOG.md` with a line describing this PR before it gets merged.

### CODE REVIEW

**Comment by sieben** [comment]
@bmw Could I have some help? I can't reproduce this error on my local setup. Could you review my code?

**Comment by sydneyli** [comment]
@sieben To reproduce the errors, does running `TOXENV=py27-dns-oldest tox -e py27` or `tox -e py34` or `tox -e py37` work? These are the Tox environments in the failed tests.

**Comment by flavou45** [comment]
I would like to use this plugin.
Do you know when will it be available in certbot ?

**Comment by bmw** [comment]
It won't be officially added to Certbot anytime soon.

https://certbot.eff.org/docs/contributing.html#writing-your-own-plugin:

>The Certbot team is not currently accepting any new DNS plugins because we want to rethink our approach to the challenge and resolve some issues like #6464, #6503, and #6504 first.
>
>In the meantime, you’re welcome to release it as a third-party plugin. See certbot-dns-ispconfig for one example of that.

If you do package a third-party plugin, you could add it to the list here: https://certbot.eff.org/docs/using.html#third-party-plugins

**Pull request closed without merging**
