### PR TITLE
Remove zope from Certbot

### LINKED ISSUE #8331: Delete reporter.py and IReporter interface
Certbot's code no longer uses reporter.py as of #8852. We should now remove the parts that require a breaking change in the next major version.

Keep in mind that depending on how this is done, this may be a breaking change requiring Certbot 2.0. See https://github.com/certbot/certbot/blob/95a6b61cdc630dff91b9e9368914c04bd2a6a146/certbot- apache/certbot_apache/_internal/configurator.py#L1517. Our plan for dealing with API changes like this is at https://certbot.eff.org/docs/compatibility.html.

We may not actually want to rip it out, especially until after we've looked at renewal. Basically the problem is that we stick too much stuff in there that would be better put contextually; we should have little enough output that important information is clear in context, as it's logged.

We may want to block this on the renewal work described in https://github.com/certbot/certbot/issues/8330.

### LINKED ISSUE #8434: Deprecate IDisplay interface and/or all of IDisplay
Having these causes more problems than they're worth; plugins can build their own display. Motivated by the discussion [here](https://github.com/certbot/certbot/pull/8432#discussion_r517731885). It's more of a code health thing than super urgent, so let's plan to deprecate it at some point and then remove it before 2.0.

### PR DESCRIPTION
**Pull request by adferrand**
Zope-related tooling have been deprecated in Certbot 5 months ago.

I propose here to remove this tooling for the next release.

Fixes #8434.

Fixes #8331.

### CODE REVIEW

**Comment by bmw** [comment]
Thanks for working on this Adrien. We definitely want this, but I think this would require a new major version of Certbot. I don't want to delay shipping that very long, but we're currently working on other backwards incompatible changes like switching to ECDSA keys by default and I think we should try to do all that in the same release instead of doing 2 new major versions.

What do you think about delaying reviewing this until we're ready for Certbot 2.0?

**Comment by adferrand** [comment]
Totally fine with this ! I will keep the PR up to date until it is the time for the new major version.

**Comment by alexzorin** [comment]
I've forced pushed this because there was quite a bit of overlap with #9337 to work around new complaints from pylint and mypy. I've also re-pinned current and latest in that commit. After that, only the original commit was really remaining.

For when we need the changelog entries again, they were:

```markdown
* Deprecated attributes in `certbot.display.util` are removed.
* `zope` based interfaces in `certbot.interfaces` module are removed.
* `zope` dependencies are removed from Certbot.
```

**Review by wgreenberg — DISMISSED** [review]
LGTM! the only thing i noticed were some zopey lines still in `.pylintrc`, but we shouldn't block merging this on that.

**Comment by adferrand** [comment]
Thanks for the rework on my PR @alexzorin and the validation @wgreenberg. Happy to see this moving out of Certbot codebase :)

**Comment by alexzorin** [comment]
Sorry @wgreenberg I had to change the base branch so may as well fix the pylintrc thing!

**Review by alexzorin — APPROVED** [review]

**Review by alexzorin — APPROVED** [review]

**Pull request merged**
