### PR TITLE
#3355: Updated certbot-auto source files to check for free memory

### PR DESCRIPTION
**Pull request by surya-v**
-> Ran "tox"  : Result Successful

### CODE REVIEW

**Comment by benileo** [comment]
would a better option be to create enough swap space so that `cryptography` can be installed? we are running as root, but maybe that is too risky.

**Comment by surya-v** [comment]
i am not sure if clearing swap space would be a good idea or not ? need more insights on this.

**Comment by pde** [comment]
Fixes: #3355 Obsoletes? #2370

**Comment by pde** [comment]
Sorry, was confused here but this should be fixed by #3473

**Pull request closed without merging**
