### PR TITLE
webroot: unset existing mime type in web.config

### LINKED ISSUE #9088: windows: webroot web.config can cause an HTTP 500 due to duplicate mimeMap
The feature we added in #9054 [is causing problems](https://community.letsencrypt.org/t/certbot-1-21-webroot-http-500-1-20-works/164870/6?u=_az).

If there is another `web.config` file, higher in the webroot directory tree than `acme-challenge/`, which also defines a `mimeMap` for extensionless files, then IIS will crash on  the duplicate `mimeMap` as it merges the configs.

I think this probably a likely scenario for our Windows users to encounter, because I recall seeing (and have posted myself) advice to create `web.config` files in the `.well-known` directory rather than the `acme-challenge` directory.

Rather than traversing the filesystem looking for other `web.config` files, one way to fix this could be to use the `remove` element to remove any existing `mimeMap` for extensionless files, before we add ours:

```xml
      <staticContent>
	  <remove fileExtension="."/>
          <mimeMap fileExtension="." mimeType="text/plain" />
      </staticContent>
```

That seems to work on Windows Server 2019.

One thing that makes me nervous is that `remove` is conspicuously missing from the documentation for `mimeMap` and `staticContent`. I'm guessing it's some kind of generic element and I'm looking in the wrong place. I found the solution on some random blog.

cc @adferrand

### PR DESCRIPTION
**Pull request by alexzorin**
Fixes #9088.

### CODE REVIEW

**Comment by bmw** [comment]
@adferrand, do you have the time and interest to review this or would it be better for me to take it?

**Comment by adferrand** [comment]
I can take it. Thanks !

**Review by adferrand — CHANGES_REQUESTED** [review]
Your proposition works totally fine, so it basically LGTM.

But since I like to study the alternatives and you expressed some concerns about the lack of documentation on the `remove` node, what about an approach consisting in disabling the `web.config` inheritance for the ACME folder ? https://github.com/certbot/certbot/pull/9092/files

It is less straightforward, but it has the advantage of beeing quite documented in the wild.

**Comment by alexzorin** [comment]
> what about an approach consisting in disabling the web.config inheritance for the ACME folder ? https://github.com/certbot/certbot/pull/9092/files

I think you maybe meant to link something else? 

But I did a little reading on the `inheritInChildApplications` option, if that's what you were referring to. It seems that it has to be included in the parent `web.config` and does not provide a way to control inheritance from the child `web.config`. If that's the case, then I think I prefer the `remove` approach better.

**Comment by adferrand** [comment]
Sorry the link was: https://stackoverflow.com/questions/782252/avoid-web-config-inheritance-in-child-web-application-using-inheritinchildapplic

**Comment by adferrand** [comment]
Indeed you are right. There is also the `<clear/>` node mentionned in the same thread. This one is officially refered in Microsoft documentation: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/appsettings/clear-element-for-appsettings

**Comment by alexzorin** [comment]
Yeah, I think `<clear />` is going to be the superior option. I'll give it a test tomorrow.

**Comment by adferrand** [comment]
By extension, the `<remove/>` node documentation: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/appsettings/remove-element-for-appsettings

Basically `web.config` is an XML configuration following the .Net framework that IIS implements. So even if the documentation is not directly linking the .Net XML syntax for configuration files in IIS, I think we are covered by an official specification and this key word will not vanish.

In that perspective I also think that your approach with `<remove/>` is better than `<clear/>` because its action is better scoped.

**Review by adferrand — APPROVED** [review]

**Comment by alexzorin** [comment]
Well, my thinking was that `<clear />` would have the advantage of removing all possible interference under `staticContent`. 

May as well see how this goes first. You're right that it's probably sufficient on its own. Thanks.

**Pull request merged**
