### PR TITLE
Refactored get_file_path

### PR DESCRIPTION
**Pull request by joohoi**
Instead of fiddling with predefined apache statement strings, do an actual file path verification for augeas paths. 

This eliminates the problem of having to predefine all possible Apache configuration file categories.

Also even though nobody(?) has hit it before, allows people to use vhost config file names starting with strings "ifmodule", "virtualhost" and "macro".

Fixes: #3377 #3319

### CODE REVIEW

**Comment by SwartzCr** [comment]
This looks good - boulder integration is failing, but it might be a fluke so I re-ran it.
I will note that you don't add back the leading slash so the `self.aug.get("/augeas/files%s/path" % get_file_path(path))` command will result in something like "/augeas/filesetc/apache2 ..." instead of "/augeas/files/etc/apache2..." - so that should be fixed
Otherwise I'm fine with this method, though still would be happy to see a check for .startswith("/files/" at the beginning of get_file_path

**Comment by joohoi** [comment]
The leading slash is re-added here on the first pass of the loop: https://github.com/certbot/certbot/blob/filepath_refactor/certbot-apache/certbot_apache/configurator.py#L1815

I actually made sure that the method returns the exact same values (as per tests) for the working preconditions than the previous implementation. (Had originally both methods in, and compared the results).

**Comment by joohoi** [comment]
The boulder integration tests are failing because of:
```
./tests/boulder-fetch.sh: line 9: docker-compose: command not found
```
https://travis-ci.org/certbot/certbot/jobs/151073313#L1838

That's something outside of this PR.

**Comment by SwartzCr** [comment]
Ah yes, looks good to me, let's see if it fixes the problem for people - but I'm happy to merge once the tests pass

**Comment by pde** [comment]
This was stuck needing a merge with master. Weirdly, I didn't see any conflicts when I did that manually?

**Comment by SwartzCr** [comment]
looks like travis is fixed! merging

**Pull request merged**
