### PR TITLE
letstest: bump ubuntu groovy to impish

### PR DESCRIPTION
**Pull request by alexzorin**
Fixes failing CI.

### CODE REVIEW

**Review by adferrand — CHANGES_REQUESTED** [review]
Do you have the associated full test suite ?

**Comment by alexzorin** [comment]
Azure was being flaky when I submitted this. I'm not sure how to trigger the full test suite. It should have happened automatically based on the branch name, right?

**Comment by adferrand** [comment]
Normally indeed any branch matching the pattern `test-*` triggers a full test suite. However the fact that the branch is associated with a PR predates the trigger of the full test suite in favor of the standard PR test suite.

Usually I create a first branch `groovy-eol` on my fork on which I create a PR, then a second branch named `test-groovy-eol` directly on the certbot repository on the same commit. This way both suites are launched and reported in the PR page (because they are on the same commit).

**Comment by alexzorin** [comment]
Here it is passing: https://dev.azure.com/certbot/certbot/_build/results?buildId=4949&view=results

**Review by adferrand — APPROVED** [review]
Works for me!

**Pull request merged**
