### PR TITLE
certbot-dns-exoscale: initial implementation

### PR DESCRIPTION
**Pull request by greut**
this was #6192 but I managed to delete my fork... since then.

----

This is a first attempt to provide a plugin for the Exoscale DNS api (which is already in [xenolf/lego](https://github.com/xenolf/lego/)). As it's very similar to the old DNSimple API and using [dns-lexicon](https://pypi.org/project/dns-lexicon/). It was easy to build it re-using the code from the DNSimple plugin.

```console
% certbot certonly --dns-exoscale --dns-exoscale-credentials exoscale.ini \
       -d lexicontest.us
```

screenshot from 2018-07-10 11-36-46

**disclaimer:** Exoscale is my employer.

### CODE REVIEW

**Comment by greut** [comment]
@zjs I've rebased it.

**Comment by greut** [comment]
yet again, is @zjs still involved with the certbot?

**Comment by bmw** [comment]
He still volunteers from time to time, but he is not regularly working on the project anymore.

With that said, we're actually not accepting any new DNS plugins right now.

We want to make a decision on some of the issues like #6464, #6503, and #6504 first.

You're welcome to leave your PR open, but we probably still won't be able to give any feedback on it for a while. In the meantime, you're welcome to release it as 3rd party plugin if you want like others have done. See https://github.com/coldfix/certbot-dns-netcup for one example of that.

**Comment by greut** [comment]
@bmw great, thanks for taking the time to provide a thorough answer.

**Comment by bmw** [comment]
Thanks for being understanding!

**Pull request closed without merging**
