### PR TITLE
Add netcup DNS authenticator

### PR DESCRIPTION
**Pull request by coldfix**
This PR adds a DNS authenticator plugin for [netcup](https://www.netcup.eu/)'s [CCP API](https://www.netcup-wiki.de/wiki/CCP_API).

Things to note:
- apart from unittest, I have tested the plugin manually on my account to work in a live environment
- I have independently [released the plugin on PyPI](https://pypi.org/project/certbot-dns-netcup/) to already make this plugin available to others in case it will take longer to be considered for inclusion, or if in case netcup is not considered a big enough backend for upstream support. If this is merged I will gladly yield control over the PyPI entry.

Best, Thomas

### CODE REVIEW

**Comment by bmw** [comment]
Thanks for the PR @coldfix!

I assume netcup doesn't have an official Python library for their DNS API. Is that correct?

If that's the case and you'd like to see this plugin taken over by us, I would like to see support for netcup added to https://github.com/AnalogJ/lexicon and this plugin modified to use that.

Alternatively, you're of course welcome to continue to support this yourself as a third party plugin. If you go this route and have any issues due to being a third party plugin, please let me know!

**Comment by coldfix** [comment]
Hi, thanks a lot for your pointers! I will update the PR to go the lexicon route and report back when that's done.

> If you go this route and have any issues due to being a third party plugin, please let me know!

In fact, I would like to point out that I find the prefix that certbot imposes on all parameter names for all external plugins to be a somewhat big incentintive to not make/use external plugins at all:

- it's one step harder to find out (as a developer) what the actual parameter names are, since they are inconsistent with all the documented ones from included plugins and you will have to look at `certbot/plugins/disco.py` for that
- they are more inconvenient to use
- there is an inconvenience if the plugin is merged later, since then both the command line options as well as the config file parameters change suddenly

If it weren't for the fact of prefixes for external plugins, I would go so far that I would prefer to maintain many DNS plugins externally - which makes it much more dynamically.

**Comment by bmw** [comment]
I agree that the way we mangle third party plugin flags is a major inconvenience. If you'd prefer to fix that instead of or in addition to other work for this specific plugin, see https://github.com/certbot/certbot/issues/4351. That issue is on our TODO list, but the Certbot team hasn't had the time to get to it ourselves.

**Comment by bmw** [comment]
@coldfix, we're going through and cleaning up our PR queue a bit. Did you decide on the approach you wanted to take here?

**Comment by coldfix** [comment]
Hi, I'll close for now and as soon as I have time to do the lexicon based PR, I will open a new one. Thanks!

**Pull request closed without merging**
