### PR TITLE
Add JSON output to `certbot certificates`

### LINKED ISSUE #3909: "certbot certificates --json"
The `certificates` subcommand should have a `--json` flag for output that's easily ingestible by other programs.

### PR DESCRIPTION
**Pull request by osirisinferi**
Fixes #3909

My current JSON format is as follows:

```
{
    "certificates": [
        {
            "cert_name": "example.com",
            "domains": [
                "example.com",
                "www.example.com"
            ],
            "expiry_date": 1605350161,
            "renewal_configuration": {
                "archive_dir": "/etc/letsencrypt/archive/example.com",
                "cert": "/etc/letsencrypt/live/example.com/cert.pem",
                "chain": "/etc/letsencrypt/live/example.com/chain.pem",
                "fullchain": "/etc/letsencrypt/live/example.com/fullchain.pem",
                "privkey": "/etc/letsencrypt/live/example.com/privkey.pem",
                "renewalparams": {
                    "account": "1234567890abc",
                    "authenticator": "webroot",
                    "installer": "apache",
                    "must_staple": "True",
                    "rsa_key_size": "4096",
                    "server": "https://acme-v02.api.letsencrypt.org/directory",
                    "webroot_map": {
                        "example.com": "/var/www/vhosts/example.com/htdocs",
                        "www.example.com": "/var/www/vhosts/example.com/htdocs"
                    }
                },
                "version": "1.8.0.dev0"
            },
            "serial": "000000000000000000000000000000001",
            "status": {
                "reason": [],
                "validity": "valid"
            }
        },
        {
            "cert_name": "example.org",
            "domains": [
                "example.org"
            ],
            "expiry_date": 1405350161,
            (...)
            "serial": "000000000000000000000000000000002",
            "status": {
                "reason": [
                    "expired"
                ],
                "validity": "invalid"
            }
        },
        {
            "cert_name": "test.example.org",
            "domains": [
                "test.example.org"
            ],
            "expiry_date": 1505350161,
            (...)
            "serial": "000000000000000000000000000000003",
            "status": {
                "reason": [
                    "expired",
                    "test_cert"
                ],
                "validity": "invalid"
            }
        },
        {
            "cert_name": "example.net",
            "domains": [
                "example.net"
            ],
            "expiry_date": 1605350161,
            (...)
            "serial": "000000000000000000000000000000004",
            "status": {
                "reason": [
                    "revoked"
                ],
                "validity": "invalid"
            }
        },
        {
            "cert_name": "test.example.net",
            "domains": [
                "test.example.net"
            ],
            "expiry_date": 1605350161,
            (...)
            "serial": "000000000000000000000000000000005",
            "status": {
                "reason": [
                    "revoked",
                    "test_cert"
                ],
                "validity": "invalid"
            }
        }
    ],
    "parse_failures": [
        {
            "error": "renewal config file /etc/letsencrypt/renewal/example.edu.conf is missing a required file reference",
            "renewal_file": "/etc/letsencrypt/renewal/example.edu.conf"
        },
        {
            "error": "expected /etc/letsencrypt/live/foo.example.com/chain.pem to be a symlink",
            "renewal_file": "/etc/letsencrypt/renewal/foo.example.com.conf"
        }
    ]
}
```

and just:

```
{
    "certificates": [],
    "parse_failures": []
}
```

if no certs are found and there is no error.

I've used UNIX timestamps (or rather POSIX timestamps according to the `datetime` Python module), as this output is supposed to be machine parsable/readable and not for humans to read directly. The same applies to the reason why I've left out the amount of time left until expiry: this can be easily computed from the expiry_date. No need to include it in the output IMO.

Earlier, I had a `cert_count` item, but I've removed it. This made fixing ToDo-item number 5 below *way* more easily and the same argumentation as above for the "time left until expiry" is also valid here: a simple `count()` or `len()` on the certificates item gives the same information. Isn't necessary to include this as a separate item in the JSON output.

(The name `expiry_date` is a little bit silly when the value is a timestamp.. Just noticing now..)

I've used JSON objects for "static" parts of the output: parts with a known amount of values. And arrays for parts which can have a multitude of values.

TODO:
1. <s>write tests (coverage has dropped to 89&nbsp;% for `cert_manager.py`)</s> **PARTLY FIXED**: coverage has dropped from 99 to 97&nbsp;%, which is substantially better than the previous 89&nbsp;%.. One new miss is from the Python 2.7 compatibility issue. Not sure if it warrents the effort when 2.7 is being deprecated anyway.
2. <s>Suppress the "Saving debug log to ..." line</s> **WONTFIX**: logger output can be suppressed by using `2>/dev/null`, too much trouble to fix it in this PR IMO..
3. <s>Suppress the "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -" from `disp.notification()` somehow.. Or use another function to display the JSON output. But I'm not sure if `logger` is the correct way to handle that</s> **FIXED** by using `display_util.notify() which has just landed in #8432.
4. <s>Also output parse failures in the JSON output? Currently if `parse_failures` is `True`, there isn't any JSON specific code, just the old one;</s> **FIXED**.
5. <s>Fix bug when no certificate is found if `--cert-name` is supplied. (Currently, it lists empty dicts for the amount of certs available, i.e., if there are 5 certs available to `certbot` but none apply for the requested `--cert-name`, it outputs a list of 5 "" certificates)</s> **FIXED** for JSON output.

### CODE REVIEW

**Comment by osirisinferi** [comment]
I've got issues with todo item number 1:

I'm trying to rebuild `test_report_human_readable()`, but with the to-be JSON output (in that stage its just a list with dicts). However, for some reason I can't seem to get a hang of it. The `"foo" in bar` style of code which works for strings doesn't work on the list/dict objects.. But that doesn't matter, there are other comparison methods.. However:

```
(venv3) osiris@erazer certbot-venv $ python certbot/tests/cert_manager_test.py 
...........> /home/osiris/github/certbot-venv/certbot/tests/cert_manager_test.py(272)test_report_human_readable_json()
-> self.assertTrue("invalid" in out['status']['validity'] and "expired" in out['status']['reason'])
(Pdb) print("invalid" in out['status']['validity'] and "expired" in out['status']['reason'])
True
(Pdb) c
F.............................
======================================================================
FAIL: test_report_human_readable_json (__main__.CertificatesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "certbot/tests/cert_manager_test.py", line 272, in test_report_human_readable_json
    self.assertTrue("invalid" in out['status']['validity'] and "expired" in out['status']['reason'])
AssertionError: False is not true

----------------------------------------------------------------------
Ran 41 tests in 6.528s

FAILED (failures=1)
(venv3) osiris@erazer certbot-venv $ 
```

Why would the assert fail, while clearly the output is `True`?

As for todo item number 5:

This seems to be a generic issue with `certbot certificates` when specifying a non-existing certificate with `--cert-name`.

**Comment by osirisinferi** [comment]
Funny, it seems `datetime.datetime.timestamp()` doesn't exist in Python 2.7, but the 2.7 tests only started to complain when I added the test function?

**Comment by osirisinferi** [comment]
I have included the whole renewal configuration file as this contains rather important information such as key sizes, used plugins et cetera, which is probably a nice thing to have if you want to parse the current available certificates in certbot.

**Comment by osirisinferi** [comment]
Also, thinking about me adding the entire renewal configuration file in the way I did this now:

We probably want to have a ***FIXED*** JSON output for compatibility reasons. For example, with the current code if we change the renewal  configuration file contents in the future, the JSON output would also change, possibly leading to backward compatibility issues.

I would like to see a suggestion for a *hardcoded* JSON output. Of course we could just hardcode the current JSON items tho.

**Comment by ohemorange** [comment]
Thanks for doing this! 

Hopefully we'll find the time to review it at some point, but I don't think we can fit it in right now.

JSON output has value, but as far as I can tell, it is very rarely asked for and I think there are more impactful uses of our coding/reviewing time.

**Comment by WilliamDEdwards** [comment]
Showing some interest for JSON output here :)

**Comment by atombrella** [comment]
I can work on polishing this to get it mergeable :)

**Comment by joshua-bn** [comment]
I would love JSON output btw. Not sure if there's a better way to upvote this.

**Review by adferrand — COMMENTED** [review]
Hello @osirisinferi ! Looking at your PR, I see that you basically introduced a dedicated new output function for the JSON format, that, as for the plain text format, takes the internal Python objects to generate the appropriate output.

I am a little woried that this design may create a maintainance overhead that could lead to some inconsistencies in the internal logic of the two functions, and so to the related outputs.

So I have an alternate design that I think could reduce this risk. Basically, I think that `certbot certificate` should always generate the JSON representation of the certificates from Certbot internal objects, then, depending on the flags passed:
* if `--json` is passed, output the JSON directly
* if not, call the "plain text" function, and generate the output *from the JSON*.

This way, the two outputs are strongly coupled and consistency is stronglier ensured.

What do you think ?

**Comment by kellyjonbrazil** [comment]
@osirisinferi I am the author of `jc`(https://github.com/kellyjonbrazil/jc) which is a tool that converts the output of many commands/filetypes/strings to JSON/YAML for easier parsing in scripts. 

I believe your approach of building JSON format into the certbot command is superior, but I think the community would [see great value](https://github.com/kellyjonbrazil/jc/issues/385) in a certbot parser with `jc`.

Let me know if there is any interest in pursuing a `jc` parser for certbot. Parsers are typically a single python file: https://github.com/kellyjonbrazil/jc/tree/master/jc/parsers

**Comment by kellyjonbrazil** [comment]
`jc` v1.23.2 now has a `certbot` parser which will convert `certbot show_account` and `certbot certificates` command output to JSON or YAML. UNIX Epoch and ISO timestamp fields are also added for convenience.

https://github.com/kellyjonbrazil/jc

```
% certbot show_account | jc --certbot -p
{
  "account": {
    "server": "https://acme-staging-v02.api.letsencrypt.org/directory",
    "url": "https://acme-staging-v02.api.letsencrypt.org/acme/acct/12345679",
    "email": "some@example.com"
  }
}
```
```
% certbot certificates | jc --certbot -p
{
  "certificates": [
    {
      "name": "example.com",
      "serial_number": "3f7axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "key_type": "RSA",
      "domains": [
        "example.com",
        "www.example.com"
      ],
      "expiration_date": "2023-05-11 01:33:10+00:00",
      "validity": "63 days",
      "certificate_path": "/etc/letsencrypt/live/example.com/fullchain.pem",
      "private_key_path": "/etc/letsencrypt/live/example.com/privkey.pem",
      "expiration_date_epoch": 1683793990,
      "expiration_date_epoch_utc": 1683768790,
      "expiration_date_iso": "2023-05-11T01:33:10+00:00"
    },
    {
      "name": "example.org",
      "serial_number": "3bcyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
      "key_type": "RSA",
      "domains": [
        "example.org",
        "www.example.org"
      ],
      "expiration_date": "2023-06-12 01:35:30+00:00",
      "validity": "63 days",
      "certificate_path": "/etc/letsencrypt/live/example.org/fullchain.pem",
      "private_key_path": "/etc/letsencrypt/live/example.org/privkey.pem",
      "expiration_date_epoch": 1686558930,
      "expiration_date_epoch_utc": 1686533730,
      "expiration_date_iso": "2023-06-12T01:35:30+00:00"
    }
  ]
}
```

**Pull request closed without merging**
