### PR TITLE
Repin dependencies to fix security alerts

### PR DESCRIPTION
**Pull request by alexzorin**
Fixes https://github.com/certbot/certbot/security/dependabot/35.
Fixes https://github.com/certbot/certbot/security/dependabot/37.

### CODE REVIEW

**Comment by alexzorin** [comment]
I have no idea what the test failure is about. I can't reproduce it on my Mac.

**Comment by alexzorin** [comment]
While investigating, I found that pinning back `pip` to `<23.1` avoided the `python-augeas` wheel building crash. I suspect that the implicated change is:

> When the `wheel` package is not installed, pip now uses the default build backend instead of `setup.py install` and `setup.py develop` for project without `pyproject.toml`. ([#8559](https://github.com/pypa/pip/issues/8559))

What doesn't make sense to me about this regression is that`wheel` is installed in the tox env, so it shouldn't crash. Instead it should successfully build the wheel using the legacy method, as per normal. 

Indeed that's what happens on my macOS laptop. Though my local environment is not exactly the same as CI, because M1 vs x86_64, and `pyenv` vs `UsePythonVersion`.

I think that there is something bum around the Python distribution that CI is using. I have seen some vague mentions in GitHub comments that build isolation is broken on macOS in some Python distributions recently, but no documented bugs. Maybe `pip>=23.1.0` triggered this latent issue. 

After trying a many, many ideas, I discovered that `--use-pep517` seems to work around the crash. However, it is a heavy hammer to use and I don't understand why it fixes anything.

We could probably also modernize `python-augeas` with a build backend/`pyproject.toml` as a more permanent and proper fix, but I anticipate there may be issues there with upstreaming the change and maintaining compatibility with older versions of `python-augeas`. 

@bmw since you and Adrien worked on build isolation, would you be able to lend a hand here?

**Comment by bmw** [comment]
Sure! It make take me a couple days to get around to taking a look, but I will soon and well before our next release (which is going to be pushed back at least a week due to 'Merica Day.)

**Comment by bmw** [comment]
I'm taking a break and plan on picking this up again either today or tomorrow, but here's what I did:

1. Did a super verbose tox run based on master so we could get more info about the Augeas installation process at https://dev.azure.com/certbot/certbot/_build/results?buildId=6902&view=results.
2. I made a verbose version of the initial version of this PR at https://dev.azure.com/certbot/certbot/_build/results?buildId=6901&view=results.
3. I also tried this on my personal x86_64 Macbook (as opposed to the M1 I use for work) and was unable to reproduce this :sob:

Comparing the logs from (1) and (2) though, I think the relevant pip change is:

> Remove `setup.py install` fallback when building a wheel failed for projects without `pyproject.toml`. ([#8368](https://github.com/pypa/pip/issues/8368))

It's not clear to me why `--use-pep517` would fix this though? I may need to refresh my memory on the various PEPs and systems at play here.

**Comment by bmw** [comment]
After more digging, here's what I got:

For comparison, a similarly verbose run on the current state of this branch can be found at https://dev.azure.com/certbot/certbot/_build/results?buildId=6907&view=results.

I think the "warning" we got about this problem from the previous logs based on `master` is https://dev.azure.com/certbot/certbot/_build/results?buildId=6902&view=logs&j=27a3daac-5920-5704-3aeb-4a7266ba51f9&t=3e16700b-0075-5f2b-1fc2-b821438ad08e&l=30779.

I do not currently fully understand what effect setting `--use-pep517` has on the build process when a project does not have a `pyproject.toml` file. Alex, if you feel you already understand this point and think you can explain it to me, please do so, but I'll otherwise plan to keep digging. I suspect setting it is fine as it seems to work and it seems to be the direction `pip` is going, but I definitely do not fully understand what's going on here. Are the wheels built differently in a way we expect to matter?

I also searched around for similar errors and found a few other Python projects hitting this on macOS, but I didn't see any generalizable fixes or explanations of the problem.

The best alternative fixes I currently have that could replace this `--use-pep517` approach in the long run are:

1. [Deprecate Apache on macOS](https://github.com/certbot/certbot/issues/9078#issuecomment-1432666005).
2. Take over and modernize `python-augeas` as I suggested at https://opensource.eff.org/eff-open-source/pl/5mm4a3f5pfft7d7sxq7gduphne as it's currently unmaintained, we heavily rely on it, and continue to be the main project that does so.

**Comment by alexzorin** [comment]
> Alex, if you feel you already understand this point 

I do not.

> The best alternative fixes

I think we should do both 👍 .

**Comment by alexzorin** [comment]
One more fun observation:

I created a branch off this PR where I install Python via `pyenv` instead of `UsePythonVersion` (and commented out `PIP_USE_PEP517`) : https://github.com/certbot/certbot/compare/repin-cryptography-41...test-ci-macos-pyenv#diff-8775fa4f5203df4609360897dc07cabe3b32703523bdb2d60b2f5e989b52da45

The macOS tests pass: https://dev.azure.com/certbot/certbot/_build/results?buildId=6909&view=logs&j=2086af5b-e16b-58e3-01f8-b9b463176d26&t=ae2e5a5b-df0e-5790-de34-130c3039f118

I was not surprised by the outcome. I am convinced that the Python distribution is defective.

**Review by bmw — DISMISSED** [review]
> I think we should do both 👍 .

OK. I will start pushing these issues along soon.

> I created a branch off this PR where I install Python via pyenv instead of UsePythonVersion (and commented out PIP_USE_PEP517) : https://github.com/certbot/certbot/compare/repin-cryptography-41...test-ci-macos-pyenv#diff-8775fa4f5203df4609360897dc07cabe3b32703523bdb2d60b2f5e989b52da45
> 
> The macOS tests pass: https://dev.azure.com/certbot/certbot/_build/results?buildId=6909&view=logs&j=2086af5b-e16b-58e3-01f8-b9b463176d26&t=ae2e5a5b-df0e-5790-de34-130c3039f118
> 
> I was not surprised by the outcome. I am convinced that the Python distribution is defective.

Very nice find! I wonder if the Pythons in the much more popularly used GitHub Actions has this problem.

In that case, since this is meant to be a temporary fix that we do not entirely understand the effects of, how do you feel about just setting this on macOS for now like I did at https://github.com/certbot/certbot/commit/06a7c0102d81226acc814d2550b2d5a7c206df9d? This passed at https://dev.azure.com/certbot/certbot/_build/results?buildId=6916&view=results. I think we should keep the comment you added explaining why we're setting this variable, but I personally like this a bit better because it limits the scope of our nonstandard behavior.

If you like your approach better for whatever reason though, feel free to merge this as is.

**Comment by alexzorin** [comment]
> how do you feel about just setting this on macOS

Yep sounds good. Done.

I also put in a `brew` workaround to avoid the git CI failures that have been plaguing us recently. It should become unnecessary eventually once the macOS CI environment catches up, but it seems to be reliable for now.

**Review by bmw — APPROVED** [review]
Looks great. Thanks Alex.

**Pull request merged**
