### PR TITLE
Cleanup test farm tests and add test_sdists

### LINKED ISSUE #4050: Prevent regressions of problems like #4044
The cause of #4044 is that although `setUpClass` wasn't added until Python 2.7, [nose manually runs this method for us](https://github.com/nose-devs/nose/blob/master/nose/suite.py#L308). We should make sure our tests catch problems like this in the future.

Options:

1. Stop using `nose` and rely either on standard Python scripts for running tests or use another program to run our tests.
2. Use another test (perhaps like my hacky script [here](https://github.com/certbot/certbot/pull/4043#issuecomment-272350209)) and make sure it runs regularly on a Python 2.6 system.
3. ???

### PR DESCRIPTION
**Pull request by bmw**
Fixes #4050 (at least once #2189 is also resolved).

### CODE REVIEW

**Comment by pde** [comment]
Reasons for deleting the OCSP test farm test rather than getting it working or at least leaving it around for future repair?

**Comment by pde** [comment]
Otherwise LGTM.

**Comment by bmw** [comment]
> Reasons for deleting the OCSP test farm test rather than getting it working or at least leaving it around for future repair?

The test is still around in `tests/letstest/scripts/test_letsencrypt_auto_certonly_standalone.sh`. If you remember, we just wrote `test_ocsp_experimental.sh ` because the feature wasn't testable using `certbot-auto` until we released 0.10.0.

**Comment by pde** [comment]
Ah yes.

**Pull request merged**
