### PR TITLE
Detect private DNS zones in Google and skip them

### LINKED ISSUE #6874: Support Google DNS Private Zones
## My operating system is (include version):
Ubuntu 18.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Docker certbot/dns-google

## I ran this command and it produced this output:
```console
$ sudo docker run --rm -ti -v /etc/letsencrypt/:/etc/letsencrypt -v /var/lib/letsencrypt/:/var/lib/letsencrypt certbot/dns-google certonly  --test-cert --dns-google -n -d '*.privatesd.public.domain'
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-google, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for privatesd.public.domain
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dns/v1/rest
URL being requested: GET https://www.googleapis.com/dns/v1/projects/XXX/managedZones?alt=json&dnsName=privatesd.public.domain.
URL being requested: GET https://www.googleapis.com/dns/v1/projects/XXX/managedZones/XXX/rrsets?alt=json
URL being requested: POST https://www.googleapis.com/dns/v1/projects/XXX/managedZones/XXX/changes?alt=json
URL being requested: GET https://www.googleapis.com/dns/v1/projects/XXX/managedZones/XXX/changes/12?alt=json
Waiting 60 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dns/v1/rest
URL being requested: GET https://www.googleapis.com/dns/v1/projects/XXX/managedZones?alt=json&dnsName=privatesd.public.domain.
URL being requested: GET https://www.googleapis.com/dns/v1/projects/XXX/managedZones/XXX/rrsets?alt=json
URL being requested: POST https://www.googleapis.com/dns/v1/projects/XXX/managedZones/XXX/changes?alt=json
Failed authorization procedure. privatesd.public.domain (dns-01): urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.privatesd.public.domain.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: privatesd.public.domain.
   Type:   None
   Detail: DNS problem: NXDOMAIN looking up TXT for
   _acme-challenge.privatesd.public.domain
```

## Certbot's behavior differed from what I expected because:
Certbot Google DNS is using the wrong zone, the private instead of public zone. We have private zones (https://cloud.google.com/dns/docs/overview#concepts) to serve different DNS to some of the VPC networks. However, Certbot needs to use the public zone, otherwise the _acme-challenge entry it's added can't be seen by Letsencrypt servers.

While the first query (https://www.googleapis.com/dns/v1/projects/XXX/managedZones?alt=json&dnsName=privatesd.public.domain.) works, we need to look at the privateVisibilityConfig, as this is present in private zones. If it's a private zone, we need to continue our search for the correct managedZone (public.domain) until we find a public domain that matches.

### PR DESCRIPTION
**Pull request by timwsuqld**
Fix #6874 by detecting if the zone we have gotten is a private zone, and if it is, continue looking through the rest of the zones

### CODE REVIEW

**Comment by ohemorange** [comment]
@schoen, loooks like you were discussing this on the issue -- do you think you'd be able to give it a review?

**Comment by timwsuqld** [comment]
@schoen It would be great if we can get this merged in. Thanks

**Comment by schoen** [comment]
Hi @timwsuqld, I would like to get this merged. Right now it has a conflict about the CHANGELOG.

@ohemorange, have we found a more orderly or convenient way to handle CHANGELOG merge conflicts? Should we fix them ourselves manually when merging?

**Comment by timwsuqld** [comment]
@schoen I've fixed the merge conflict again.

@ohemorange I personally would suggest whoever is merging can fix CHANGELOG conflicts, otherwise, you may find the requester having to fix the conflicts multiple times as merge requests are merged in.

**Comment by ohemorange** [comment]
I've just been fixing them myself when I approve the code, that seems to be working fine enough.

**Comment by ohemorange** [comment]
Other than that changelog merge conflict, were there other outstanding issues with the code?

**Comment by schoen** [comment]
Thanks!

**Pull request merged**
