### PR TITLE
snap: Fix "stack smashing" error in wrapper

### LINKED ISSUE #8245: Fix "stack smashing" problem in the Certbot snap
A couple times now I've seen people report seeing the following output from the Certbot snap:
```
*** stack smashing detected ***: <unknown> terminated
```
I just reproduced this myself on a clean CentOS 8 DigitalOcean droplet (with `httpd` installed) after following the [snapd installation instructions](https://snapcraft.io/docs/installing-snap-on-centos), installing the Certbot snap, and running (almost) any command such as `certbot plugins` or `certbot --version`.

What's going on here? Is there a problem in the snap that needs to be fixed? I think we should take the time to understand the root cause here and at a minimum squelch this output, but there may be a more significant problem that needs to be fixed here.

### PR DESCRIPTION
**Pull request by alexzorin**
Fixes #8245

### CODE REVIEW

**Comment by alexzorin** [comment]
I've made a binary available here as well: https://tools.letsdebug.net/certbot_1.7.0-64-gd62d853ea_amd64.snap, which I've tested against CentOS 8. The inclusion of `gawk` appears to have increased the archive size by around 1MB.

**Comment by adferrand** [comment]
@alexzorin is there some ongoing work that prevents your PR to be ready for review ? Because at a first look, it goes quite well !

**Comment by alexzorin** [comment]
OK, ready now.

As decided in #8245, I removed the changes related to #8250, they will arrive in a follow-up PR.

These changes fix #8245 and #8251.

**Review by adferrand — APPROVED** [review]
I did various local tests to check if the snap is working as expected with plugins connected, with or without libaugeas and gawk installed on the host. Everything is working.

LGTM!

**Comment by adferrand** [comment]
As a side note, I expect the build this night to fail on snap build. It is not because of this PR, it was also the case in the latest nightly build, because it seems that the remote build is staling forever currently. I will open a issue about this.

**Pull request merged**
