### PR TITLE
Allow relative URIs for `Link` headers

### LINKED ISSUE #434: Relative links
https://github.com/letsencrypt/acme-spec/issues/128; if relative links are not allowed, we should at least log an appropriate error message and notify the user, or be clever and try to normalize them based on `Location` or request URI if the former is not present.

### PR DESCRIPTION
**Pull request by osirisinferi**
[`urllib.parse.urljoin()`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin) is a very cool function. Almost feels like "if it's too good to be true, it probably is"! What am I missing here? :stuck_out_tongue: 

<s>Maybe write some tests?</s><small>Done.</small>

Fixes #434

### CODE REVIEW

**Comment by osirisinferi** [comment]
Uch, I always think about running the test suite locally when I've already opened the PR.. Even when I thought about adding tests! Sigh.

**Comment by osirisinferi** [comment]
I've added tests for five different types of relative URLs which are all properly converted to regular URLs by `urljoin()`. I couldn't think of any other form(s) of relative URLs. And even if one exists, I doubt if it's necessary to add more :stuck_out_tongue:

**Comment by osirisinferi** [comment]
Another test situation: `urljoin()` should never modify an absolute URL. Its behaviour probably won't change, but lets make sure we'll have the situation covered if it unexpectedly changes anyway.

**Comment by alexzorin** [comment]
Hi @osirisinferi,

Do you know if there are any ACME servers which use relative link relations?

**Comment by osirisinferi** [comment]
> Do you know if there are any ACME servers which use relative link relations?

I do not. Had to modify Pebble for it. But I guess the issue was kept open for a reason.

**Pull request closed without merging**
