### PR TITLE
Use apache2ctl modules for Gentoo systems.

### LINKED ISSUE #5344: Can't install new certificates with certbot-apache under Gentoo since version 0.20.0
It seems that version 0.20.0 has a major architecture revision from 0.19.0, in particular regarding OS specific overrides. But the Gentoo overrides have a flaw when trying to install a new certificate : at one point it tries to run "apache2ctl -t -D DUMP_MODULES", which is no good at all under Gentoo because apache2ctl is a dummy script redirecting to /etc/init.d/apache2. It generates this error :

`Error in checking parameter list: /etc/init.d/apache2: invalid option -- 't'`

## My operating system is (include version):
Gentoo

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager (emerge) with testing (~amd64) flag

## I ran this command and it produced this output:
```
certbot -d test.example.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for test.example.com
Waiting for verification...
Cleaning up challenges
Error in checking parameter list: /etc/init.d/apache2: invalid option -- 't'

Apache is unable to check whether or not the module is loaded because Apache is misconfigured.
```

## Certbot's behavior differed from what I expected because:
Certbot did not install the certificate because it failed to run apache2ctl -t -D DUMP_MODULES

### PR DESCRIPTION
**Pull request by joohoi**
Fixes #5344

### CODE REVIEW

**Comment by bmw** [comment]
This seems simple enough but two questions:

1. What's the behavior of `apache2ctl` on systems with systemd? 
2. Could we use `apache2ctl modules` on Gentoo? I'm not sure how new this functionality is, but at least on an up to date system, this works. The relevant snippet from `/etc/init.d/apache2` is:
```
modules() {
        checkconfig || return 1
        ${APACHE2} ${APACHE2_OPTS} -M 2>&1
}
```

**Comment by joohoi** [comment]
Nice catch! Now this PR is doing exactly that, using `apache2ctl modules`, for the modules call. 

Unfortunately I think that systemd version is completely unable to use apache2ctl, as it pretty much calls the OpenRC script directly, the whole contents of `apache2ctl` being:
```
#!/bin/sh
exec /etc/init.d/apache2 "$@"                          
```

And this has also been the main issue for Gentoo systems with systemd. I'm trying to figure out the correct things to do for these systems in #5263

**Comment by bmw** [comment]
Then my only concern with this PR is will trying to use `apache2ctl modules` make things worse for systemd users?

I tried to test this myself, but after waiting an hour for things to compile, I'm not sure I did it right. OpenRC was still installed and `/etc/init.d/apache2` still works. After Googling around, maybe it OpenRC is always installed unless the user does a lot of work on their end to rip it out of Gentoo. See https://forums.gentoo.org/viewtopic-t-994660.html?sid=2d4170a3eda7addd8e2883e402af733d.

Since I struggled to make this work, I'm trusting your judgement here.

**Comment by joohoi** [comment]
We don't currently have a reasonable support for Gentoo systems running systemd at all. Even though systemd might be officially supported by Gentoo, the Apache package unfortunately isn't. This is discussed in #3411 . 

We need to clean up the constants throughout Apache plugin at some point, and this will also include making the user able to provide the Apache control commands on the command line which in turn will help to alleviate this problem.

**Pull request merged**
