### PR TITLE
No conflicting declarations

### LINKED ISSUE #574: Option to exclude options-ssl-nginx.conf
If one has already setup SSL the letsencrypt options-ssl-nginx.conf will prevent nginx restart.
In my case it's the ssl_session_cache which is already defined in my config.

### PR DESCRIPTION
**Pull request by olabini**
This pull request does two things - it stops using the options-ssl-nginx.conf and instead reads it and adds the declarations directly. The reason for doing this is to stop potential conflicting declarations, and make it easier to deal with other requirements, such as providing the possibility of upgrading cipher suites.

It also changes the name of the session cache used. That means that even if an ssl_session_cache is defined at the http{} level, this cache will not conflict with it.

This should fix #574, #921 and #1743

### CODE REVIEW

**Comment by pde** [comment]
Interesting approach.  This is rather different from what we do in Apache, but it might be workable.  Some questions:

* Do you defer to existing directives, override them, or offer a switch between the two?
* If you defer, there's probably no elegant way for us to update the SSL options we've set, which seems bad.
* Overriding is a better default, though we should think about how to let the user know, and give them an option to cancel (I think we can improve the current Easy / Secure UI step to achieve that).

Related: #1123. CC'ing @joohoi and @sagi for their thoughts.

**Comment by pde** [comment]
The other option to consider is commenting out existing conflicting declarations, but continuing to keep our options in a separate file, so that people can see where they came from and we can update the file under appropriate circumstances.

**Comment by olabini** [comment]
Yeah, the main reason I went with this approach was because it felt like if we want support two modes of ssl_ciphers, one "low" and one "high" - dealing with having them all in a shared include file seemed like a bad idea.

**Comment by olabini** [comment]
Incidentally, @pde - have you considered doing something along the lines of marking each line that LE is responsible for with a comment of some kind? Something like

    ssl_prefer_server_ciphers on; #LE-line - please don't remove this comment

**Comment by olabini** [comment]
In terms of your questions:
    Do you defer to existing directives, override them, or offer a switch between the two?
Currently, the code uses the existing method of adding directives, which uses add_server_directives with replace=False - thus, right now we defer to existing ones.

    Overriding is a better default, though we should think about how to let the user know, and give them an option to cancel (I think we can improve the current Easy / Secure UI step to achieve that).
Sure, that's an easy change if that's what we want to do.

**Comment by pde** [comment]
OK, here are a few approaches that I think make sense:

* Keep "existing directives take precedence" as the default behaviour, but add a comment like `# Set by LetsEncryptPythonClient" to each directive that we add, so they can be updated later.
* Switch to "new directives take precedence", and then add a UI option (we can do that in another PR) to disable that if the user wants to.  Directive comments are still nice in this case, but less necessary.
* Continue putting all of our security directives in our own separate file, and deal with the issue by commenting out any directives that conflict with ours.  If we want to support high-security and high-compatibility ciphersuite options, we can make two different config files, and include the one that the user requested.

I think any of these paths are workable, and I'm willing to merge whichever one the nginx team thinks is most elegant.

**Comment by pde** [comment]
@diracdeltas is mostly swamped with other work at the moment but might also have thoughts on this.

**Comment by olabini** [comment]
I think all three of these are workable. The final one I think might be trickier, since then we have to keep track of what we commented out, etc.

For now, I'll update this PR with approach number one.

**Comment by pde** [comment]
@olabini why would we need to keep track of what we commented out in case 3?  (I guess we could need to do that for reverting changes, but I assume in that case we just keep an old copy of the entire configuration).

**Comment by olabini** [comment]
True, that might be easier.

**Comment by olabini** [comment]
This one is now waiting for the new parser.
This one also fixes #543 and #939, once the new parser is in, and I can add comments.

**Pull request merged**
