### PR TITLE
certonly: hide "NEXT STEPS" for dry-runs

### PR DESCRIPTION
**Pull request by alexzorin**
The good part about this is that practically nobody will see this mistake, except snap `--csr` users and our `pip` users who did their installations after 1.16.0 was released.

### CODE REVIEW

**Review by ohemorange — CHANGES_REQUESTED** [review]
Code looks good but can we have a teensy unit test just to make sure and prevent regressions in this branch-heavy part of the code?

**Comment by alexzorin** [comment]
I sort of hate how I ended up with a mish-mash of control flow (sometimes `config.whatever` is checked inside the callee, sometimes it is checked by the caller). Hopefully it is not too gross, but maaaybe worth a refactor separately.

**Comment by ohemorange** [comment]
Eh, it's like that because sometimes we use other things to calculate `new_or_renewed_cert`, so I'm not worried about it.

**Review by ohemorange — APPROVED** [review]
lgtm!

**Pull request merged**
