### PR TITLE
manual: deprecate --manual-public-ip-logging-ok

### PR DESCRIPTION
**Pull request by alexzorin**
@ohemorange indicated to me in [this doc](https://docs.google.com/document/d/1viiuYQafSxrTQtBI2a1_p3Q_IBVDAZAw8xkSWOQglHM/edit?usp=sharing) that we can safely remove this flag from the manual plugin. As it's a small self-contained change, may as well do it now.

There's still a reference to `manual_public_ip_logging_ok` in [a `cli.report_config_interaction` test](https://github.com/certbot/certbot/blob/a64e1f01291327ae16b412ee921fc6ac6aed8453/certbot/tests/cli_test.py#L508-L543) that I'm not sure about, but:

1. The actual choice of flags there doesn't seem to matter, and
2. `cli.report_config_interaction` appears to be dead code. It was introduced in 2016 doesn't seem to have ever been used. I wouldn't be surprised if we could just delete it and its tests.

### CODE REVIEW

**Comment by ohemorange** [comment]
Yeah, let's also delete `cli.report_config_interaction`.

**Review by ohemorange — APPROVED** [review]

**Comment by osirisinferi** [comment]
Does this mean Let's Encrypt won't public those IP addresses, *ever*? From the document linked above I cannot retrieve why this element should be deprecated if I'm honest.

**Comment by ohemorange** [comment]
This PR removes an unnecessary confirmation with the user that they're ok with the fact that running Certbot makes an external connection to a CA, essentially.

**Comment by osirisinferi** [comment]
But I still don't understand the argumentation why it's suddenly unnecessary after apparently it has been necessary for &plusmn; 4 years up until this PR? The confirmation was included for a reason.

Just stating it's unnecessary because it's unecessary isn't a very convincing plea IMO. I think it would be a good thing to have at least a paper trail pertaining to any argumentation to any decision made. At the moment, I'm missing those arguments, i.e., there's no paper trail. In a year when other people look back why this feature is removed, they'll find nothing but the statement that it was deemed unnecessary.

**Comment by ohemorange** [comment]
To flip it around, why was it necessary in the first place? Our goal is to streamline the CLI UX, and so unnecessary prompts that just act as roadblocks to getting a cert should be removed.

**Comment by alexzorin** [comment]
To elaborate further, the user has already been presented with the CA's Subscriber Agreement which covers the same thing anyway. In the case of Let's Encrypt, the IP is recorded as soon as you register your account anyway, not just upon requesting a certificate.

I proposed removing it (motivated by terminal output streamlining) both because it felt redundant (for the above reasons) and excessively cautious.

Wanting to know the justification for the change is reasonable and I hope that helps.

**Comment by osirisinferi** [comment]
> To flip it around, why was it necessary in the first place?

As an extra reminder. Or perhaps ask @jsha for more specifics as he opened the [issue back in 2015](https://github.com/certbot/certbot/issues/991).

> I proposed removing it (motivated by terminal output streamlining) both because it felt redundant and excessively cautious.

I guess it's fair now EFF is responsible for `certbot` and not Let's Encrypt/ISRG any longer to have other opinions in these matters. It was put in place exactly to be redundant and excessively cautions, but times change I guess.

**Pull request merged**
