### PR TITLE
Docs: Reset requirements.txt path

### PR DESCRIPTION
**Pull request by zoracon**
Readthedocs does not like relative paths. I believe it can just read down from the root of the repo (hopefully). There's no clear way to test this locally.

### CODE REVIEW

**Comment by zoracon** [comment]
Seeing that there is a way to test with the branches. I am assuming someone adjusted to see that. So putting merging on hold until I resolve the error.

**Review by bmw — DISMISSED** [review]
Progress! Using the same process to test this that I described [here](https://github.com/certbot/certbot/pull/9876#issuecomment-1897564059), I got [this build](https://readthedocs.org/projects/eff-certbot/builds/23200545/). Now it properly finds the file, but it fails to install everything in it because this file contains ALL possible Python dependencies of ours and readthedocs is missing non-Python dependencies like Augeas our project links to.

To suggest a possible path forward, I'd maybe use our requirements file as [constraints for pip](https://pip.pypa.io/en/stable/user_guide/#constraints-files) and then configure readthedocs to only install the parts of our code it needs. This is the kind of setup we had before in files like https://github.com/certbot/certbot/blob/7ca1b8f2867b252f8657b49a3fb4c374670a629d/certbot-dns-cloudflare/readthedocs.org.requirements.txt before readthedocs decided it no longer wanted to support it 🙁 I found an example of this kind of configuration with the new yaml files at https://github.com/readthedocs/readthedocs.org/issues/7258#issuecomment-1310582515 although I think it may work to just use these existing "readthedocs.org.requirements.txt" files as the requirements in each respective yaml file.

I think it's up to you if you'd like to merge this as a correct, incremental improvement or continue iterating on this here.

**Comment by zoracon** [comment]
@bmw Okay I redirected to the requirements.txt and have passing builds.

**Review by bmw — APPROVED** [review]
lgtm! Thanks for wrangling this Alexis.

**Pull request merged**
