### PR TITLE
Remove docker-compose dependency

### PR DESCRIPTION
**Pull request by bmw**
As described at https://www.docker.com/blog/announcing-compose-v2-general-availability/, the Python version of docker-compose has been deprecated and [hasn't seen updates in over a year](https://pypi.org/project/docker-compose/#history). This is causing problems in my work on https://github.com/certbot/certbot/issues/9370 because docker-compose relies on older versions of libraries than some of our other dependencies are happy with.

To fix this, my plan was to remove our dependency on the Python version of docker-compose in favor of using docker-compose from the external environment. I'm having trouble with this approach in CI though.

The only real change in this PR is the change to `certbot-ci/setup.py`. The rest of the changes in this PR are just to facilitate easier testing/debugging (although I do think we should keep changes like a timeout on `subprocess.Popen.wait` calls). With the change to use docker-compose from the external environment, the code [here](https://github.com/certbot/certbot/blob/test-remove-docker-compose/certbot-ci/certbot_integration_tests/utils/acme_server.py#L89-L98) no longer successfully shuts down boulder running in docker-compose. We call [`process.terminate` which sends SIGTERM to docker-compose](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.terminate) to initiate shutdown which [docker-compose supposedly still supports](https://docs.docker.com/engine/reference/commandline/compose_up/) but this doesn't seem to be working in CI despite working for me locally. Why?

You can see this failure [here](https://dev.azure.com/certbot/certbot/_build/results?buildId=5975&view=logs&j=c121f918-31e1-5a38-5825-6d6cfbed40ca&t=360ef6cc-e78a-544f-50f9-385ea532dee3&l=37811) and it passing [here](https://dev.azure.com/certbot/certbot/_build/results?buildId=5976&view=logs&j=c121f918-31e1-5a38-5825-6d6cfbed40ca&t=360ef6cc-e78a-544f-50f9-385ea532dee3&l=37760) for comparison on a branch containing all of my changes here besides the change to `setup.py`

### CODE REVIEW

**Comment by alexzorin** [comment]
I had a go but didn't find much of anything. 

Only way I could reproduce it was to use `docker-compose` v2 (i.e. `s/docker-compose/docker compose/g`). There, SIGINT/SIGTERM seem to get ignored on the outer `docker compose` process unless sent 3x. This is the case both when running through `tox` and when playing with `docker compose` manually.

Assuming Azure Pipelines uses the same images as GitHub actions, [`docker-compose` on that image is v1](https://github.com/alexzorin/imagetest/actions/runs/3276331630/jobs/5392263116), not aliased to v2, so it shouldn't explain anything.

Could be that the same cause is behind why v2 SIGTERM doesn't work and the failure in the v1 pipeline, but that seems like a long shot.

**Comment by adferrand** [comment]
@alexzorin I see that your test involved to use directly the plugin binary instead of the `docker compose` command. So the issue may be signal propagation  between `docker compose` and the `docker-compose` binary.

Anyway, this seems to be another decent workaround if everything is working on this test: having a function checking if the v2 plugin is installed, and use it, or fallback to whatever `docker-compose` command available in the PATH.

**Comment by bmw** [comment]
Thanks a lot for taking a look you two.

I think either of the approaches you describe should work, but I like the conventionality `docker(-/ )up -d`, `docker(-/ )compose down`, and a `docker(-/ )compose logs -f` process if `stdout` isn't captured. Unless there's major concerns here, I'll implement this soon.

**Comment by adferrand** [comment]
It was in fact my initial approach in this script. I do not remember a specific reason against it, except that the approach with a process was a little bit more simple and pythonic.

So if it works, good for me !

**Comment by bmw** [comment]
Closing in favor of https://github.com/certbot/certbot/pull/9436.

**Pull request closed without merging**
