### PR TITLE
obj.py was failing to write out all parameters. let's fix that.

### PR DESCRIPTION
**Pull request by ohemorange**
Be sure to edit the `master` section of `CHANGELOG.md` with a line describing this PR before it gets merged.

From the ashes of #6366.

### CODE REVIEW

**Comment by ohemorange** [comment]
For some reason, this is the PR that breaks tls-sni. No one's been complaining about this, it's just a correctness thing. So let's wait until then and not bothering fixing tls-sni.

**Comment by sydneyli** [comment]
@ohemorange any idea about the funky integration test failures?

**Comment by ohemorange** [comment]
Yes. It's because tls-sni copies over addresses wholesale. The easiest way to fix this is to remove tls-sni and not have to worry about it (see comment above).

**Comment by m0namon** [comment]
Closing this out and throwing it into an issue!

**Pull request closed without merging**
