### PR TITLE
Enable automatic PRs from dependabot

### PR DESCRIPTION
**Pull request by atombrella**
It's a proposal to enable dependabot in this repository. It has become an opt-in feature that automatically creates PRs. Since each of the dns plugins is essentially a package, the YAML file is rather long. There are different options that can be set to configure the intervals when the bot creates PRs with dependency updates, as well as labels and reviewers, as well as the maximum number of PRs it can create to avoid being spammed.

I don't think certbot nor the acme library themselves publish many package updates for security issues. All of the DNS plugins depend on these two components, as well as third-party libraries for DNS requests.

Please read the documentation to see if the file can be tweaked 
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates

## Pull Request Checklist

- [x] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [ ] Add or update any documentation as needed to support the changes in this PR.
- [x] Include your name in `AUTHORS.md` if you like.

### CODE REVIEW

**Comment by osirisinferi** [comment]
Maybe I'm missing it, but can Dependabot also check for availability of the suggested dependency upgrade in certain distribution package repositories? E.g. EPEL et cetera?

**Comment by atombrella** [comment]
> Maybe I'm missing it on the Dependabot page, but can Dependabot also check for availability of the suggested dependency upgrade in certain distribution package repositories? E.g. EPEL et cetera?

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates#supported-repositories-and-ecosystems These are the supported package systems, so it's for non-distribution specific package systems.

It uses the `setup.py` file to scan for the dependencies.

**Comment by osirisinferi** [comment]
> These are the supported package systems, so it's for non-distribution specific package systems.

I can imagine you'd like to also know if a suggested update is also available in distribution specific repositories. Otherwise you'd need to weekly check if a suggested update from Dependabot is feasable.

It seems to be possible to combine Dependabot with a Github Action: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions

Maybe write a Github action that does the distribution repository checking?

**Comment by adferrand** [comment]
To be clear, I do not think dependabot is really useful without a lock dependency system.

Indeed without it, what dependabot proposes is to upgrade the lower bound of setup.py declared dependencies. Which basically lock out everyone to the most revent versions of the dependencies, while the code is still compatible with old ones.

With a lock system, it makes better sense. For instance I use dependabot for projects managed by poetry: in this case it deduces from the initial dependencies from `pyproject.toml` to propose dependency lock upgrades for `poetry.lock` file. I find this approach quite elegant because it allows to still use older dependencies on third parties, but ensure that for yourself, you deliver up-to-date runtime artifacts (eg. docker images, snaps) and focus your official support (CI/CD, tests) on them.

So I would say that until certbot project is using a locking mechanism understandable by dependabot, we should avoid to use dependabot.

**Comment by atombrella** [comment]
OK. So should we close it?

**Comment by osirisinferi** [comment]
If the Certbot team thinks Dependabot is a good idea, but indeed requiring e.g. a lock dependency system, we could perhaps tag this PR with the "blocked" label until such a system is in place 🙂

**Comment by atombrella** [comment]
> > These are the supported package systems, so it's for non-distribution specific package systems.
> 
> I can imagine you'd like to also know if a suggested update is also available in distribution specific repositories. Otherwise you'd need to weekly check if a suggested update from Dependabot is feasable.
> 
> It seems to be possible to combine Dependabot with a Github Action: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions
> 
> Maybe write a Github action that does the distribution repository checking? I can't find any existing Github action for such a thing, but Repology offers [an API](https://repology.org/api), so perhaps it isn't hard to implement, if deemed useful.

Cool. I didn't think about that aspect of the security and external repositories. I probably naïvely just assumed that all PyPI would be available in all distributions. 

 Anyway, as adferrand said, maybe this isn't a big priority now to work with this.

**Comment by osirisinferi** [comment]
> I probably naïvely just assumed that all PyPI would be available in all distributions.

When using the packaging system of the distribution, usually PyPi is not involved at all. In the case of Gentoo for some packages only as the source of the source code, but the dependency tree is dependend on the repository of the distribution, not on the tree of PyPi.

**Comment by bmw** [comment]
I agree with Adrien's comment and since we have no plans to switch this repo to a lockfile based system (which I think is fairly challenging due to the number of different Python packages in this repo), I'm going to close this.

If someone would like me to reconsider, please don't hesitate to let me know!

**Pull request closed without merging**
