### PR TITLE
Added certbot-dns-azure to DNS plugin list

### PR DESCRIPTION
**Pull request by atombrella**
https://github.com/certbot/certbot/pull/8727 Just adding it to the list.

There's an alternative plugin, but there's no official documentation, https://github.com/dlapiduz/certbot-azure

## Pull Request Checklist

- [X] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [X] Add or update any documentation as needed to support the changes in this PR.
- [X] Include your name in `AUTHORS.md` if you like.

### CODE REVIEW

**Comment by atombrella** [comment]
https://github.com/certbot/certbot/pull/8180 is for the alternative.

**Review by alexzorin — CHANGES_REQUESTED** [review]
https://github.com/binkhq/certbot-dns-azure is already in the table; this PR ends up listing it twice. 

Did you mean to list the other Azure plugin as an alternative?

**Comment by atombrella** [comment]
> https://github.com/binkhq/certbot-dns-azure is already in the table; this PR ends up listing it twice.
> 
> Did you mean to list the other Azure plugin as an alternative?

Hmm. I overlooked this :/ I could add the other one as an alternative. I'll update this PR during the weekend.

Anyway, could some of the PRs for the DNS plugins be closed? They aren't going to be merged, so IMO they just create noise.

**Comment by atombrella** [comment]
Let's just close it.

**Pull request closed without merging**
