### PR TITLE
Minor bugfixes

### PR DESCRIPTION
**Pull request by karansthr**
- Remove usused imports
- Remove unnecessary comprehension.
- Fix mutable default argument
- Change methods not using its bound instance to staticmethods.
and few more

Signed-off-by: Karan karan@deepsource.io

### CODE REVIEW

**Comment by bmw** [comment]
Thanks for the PR @karansthr.

I don't think we want to add the `.deepsource.toml` file or refactor all assertions, but your other changes look good! If you'd like to remove those changes, we can probably merge this PR.

**Comment by karansthr** [comment]
> Thanks for the PR @karansthr.
> 
> I don't think we want to add the `.deepsource.toml` file or refactor all assertions, but your other changes look good! If you'd like to remove those changes, we can probably merge this PR.

This PR also adds `.deepsource.toml` configuration file to run static analysis continuously on the repo with DeepSource. Upon enabling DeepSource, quality and security analysis will be run on every PR to detect 500+ types of problems in the changes — including bug risks, anti-patterns, security vulnerabilities, etc.
**Autofix**: DeepSource also supports automatically fixing some of issues. In a couple of clicks, fixes would be genreated and a PR can be created.
DeepSource is free to use for open-source projects, and is used by teams at NASA, Uber, Slack among many others, and open-source projects like ThoughtWorks/Gauge, Masonite Framework, etc.

To enable DeepSource analysis after merging this PR, please follow these steps:

* [Sign up](https://deepsource.io/signup) on DeepSource with your GitHub account and grant access to this repo.
* Activate analysis on this repo [here](https://deepsource.io/gh/pyinvoke/invoke/).
* You can also look at the [docs](https://deepsource.io/docs) for more details. Do let me know if I can be of any help!


About assert refactor, including assert statements out of test files is not a good idea because when the Python interpreter is invoked with the -O (optimize) flag, the assert statements are removed from the bytecode? So is there any reason to keep them in non test files ?

**Comment by bmw** [comment]
Cool! Maybe we'll sign up for DeepSource in the future but I'm personally not interested in doing so right now so I don't think we need the configuration file. Thanks for writing one for us though.

For the assertions, I've never seen it be an issue, but you're right that ideally production code wouldn't use `assert`. My main reason for suggesting the change be removed is all the test failures it creates. You could fix those instead if you prefer.

**Comment by karansthr** [comment]
> Cool! Maybe we'll sign up for DeepSource in the future but I'm personally not interested in doing so right now so I don't think we need the configuration file. Thanks for writing one for us though.
> 
> For the assertions, I've never seen it be an issue, but you're right that ideally production code wouldn't use `assert`. My main reason for suggesting the change be removed is all the test failures it creates. You could fix those instead if you prefer.

@bmw I've removed `.deepsource.toml` file and assertion related changed from pull request.

**Pull request merged**
