### PR TITLE
Nginx parsing rehaul

### LINKED ISSUE #5823: Revamp Nginx parsing

### PR DESCRIPTION
**Pull request by sydneyli**
Fixes #5823 (eventually)

OOP-y revamp of nginx parsing utilities, so we can hopefully stop depending implicitly on structures of nested lists.

Code is all in new files but will eventually cannibalize `parser.py` entirely.

Still very WIP. There are very few comments, many typos, error messages are largely uninformative, I need to break things out into different files, and some of these things i'll want to break out into `plugins.common`.

Next courses of action:
 - Hook into `configurator.py` as primary parser, and fix any test issues
 - Run short experiment to see how much work implementing a dovecot parser would be in this world
    - I suspect we'll need a way to add custom parsing hooks.
 - Test coverage for new object code
 - General cleanup (comments, error handling)

### CODE REVIEW

**Comment by sydneyli** [comment]
After messing around with things, this object-tree approach seemed to be the nicest way to do things, but I'm open to other suggetsions.

The new nginx parser actually constructs an object tree.
Assumptions about parsed list structure should be mostly hidden away in `parser_obj.py`, although certain decisions do leak to objects which consume the parsing objects. For instance, since the parsed objects take care of adding whitespace to a directive (such that it matches existing context), it expects an unspaced list to be passed into its functions.

In essence, the tree looks like:

```
                 root_file
                     |
                 Statements
                list of ...
                 /      \
ServerBloc---Bloc       Sentence---Include
              /                       \
      [name, contents]                file (Statements)
         /        \
    Sentence    Statements
```

The basic building block for all of this is the `Sentence`, which is simply a collection of tokens and whitespace. It acts a lot like the `UnspacedList` object from the previous parsing design-- `Sentence.words` magically hides the associated whitespace and quotation marks.

For future block/statement-like parsing (cough Dovecot cough), the basic Statements/Block/Sentence structures will stay the same. In order to add configurability, you'll be able to introduce parsing hooks (i.e. if hook returns True => parse as some type) in order to parse and define configuration-specific objects (like ServerBlocs in nginx).

`Statements` is a collection of Blocs and Sentences (blocks and directives). With a little bit of type introspection, recursive tree-searching operations become pretty easy to build and query. The API for this has to be fleshed out a little bit more, but the gist is that you can query for either Blocks or Sentences that pass a given filter, either shallowly or recursively.

`Include` directives actually load in and parse the requested file. In order to avoid re-parsing files that may have been included twice, we use the global map in `Context`.

## parse and get_data

`parse` parses these objects from the raw parsed lists, from `nginxparser`. `get_data` does the reverse, and recursively dumps the class into the original parsed raw-lists. Functions that modify these objects should modify the underlying raw-list structures as well, so that they play nicely with existing code and dump correctly into files.

## Context

Each object also tracks a `Context`, which contains contextual information like
 - the object's parent, used when duplicate blocks to automatically add that block as a sibling
 - the file where the object is from
 - the current working directory, used to discover files at relative paths that are included
 - a global map of other parsed files, used to prevent object duplication when following `Include`s
 - tabbing information

## Nginx-specific parsing

Most of the nginx-specific logic should occur in `ServerBloc` (TODO: I haven't finished making this abstraction super clean, but it should be), an Nginx-specific types of directives that necessarily change the way that particular statement is parsed. 
 - `ServerBloc` parsing and changes need to track a parallel `VirtualHost` object. Eventually, we might be able to consolidate the `VirtualHost` and `ServerBloc` objects, rather than keeping the two constantly in parallel.

## How does this solve our other problems?
Besides removing explicit parsed-list indexing from most of the nginx codebase, this also:

Put new Nginx server blocks we create in a new file when appropriate: #5185
 - Change the `context.filename` of the appropriate block before dumping.

Unquote parameters in Nginx: #5543
Support multiline concatenated quotes in Nginx: #5774
 - These can be done automatically with the `Sentence` abstraction.

nginx _add_directive should figure out spacing automatically: #3417
add_server_directives should pick up whitespace from context rather than having the caller set it, and definitely for replace it should just replace the contents: #5157
 - Keeping track of tabbing guesses in objects solves both of these.

## Notes

Some of the abstractions are not perfectly fleshed out/mumbled in the current code, but this can be ironed out.

With some work, I've gotten the existing code to play nicely with `configurator` and `obj`, although it involved more changes to those files than I would have liked (mostly involved removing all explicit parsed-list indexing). **Before continuing to massage the rest of the nginx codebase to play nicely with the new parser, I'm looking for comments/iteration on the high-level design.** The nginx code feels a lot more intuitive without the explicit list-indexing; however, this does touch *a lot* of previous assumptions throughout the codebase and I'm currently trying to make these changes less intrusive (so we don't rehaul everything at once).

If you have any questions or maybe thoughts on smoothing over the transition to the new parser, things that seem not-so-nice, ideas on how to improve the existing high-level design, additional edge-cases that need to be worked into the design, please let me know.

**Comment by ohemorange** [comment]
Here are some thoughts and questions:

1. do changes need to be made to nginxparser?

2. "Functions that modify these objects should modify the underlying raw-list structures as well, so that they play nicely with existing code and dump correctly into files."
as in, in parser or in configurator?

3. "Most of the nginx-specific logic should occur in ServerBloc (TODO: I haven't finished making this abstraction super clean, but it should be), an Nginx-specific types of directives that necessarily change the way that particular statement is parsed."
what does this mean?

4. so what does add_server_directives look like? which nodes need to be updated, and does that propagation happen manually or automatically?

5. "Unquote parameters in Nginx: #5543
Support multiline concatenated quotes in Nginx: #5774
These can be done automatically with the Sentence abstraction."
The easiest way to fix #5543 is changing the options in nginxparser.py. Are we instead going to leave those, so we can better write things back out?

**Comment by sydneyli** [comment]
> do changes need to be made to nginxparser?

Nope!

> "Functions that modify these objects should modify the underlying raw-list structures as well, so that they play nicely with existing code and dump correctly into files."
> as in, in parser or in configurator?

I mean the parser. Might re-word this to avoid confusion (this confused me upon rereading, also)

> "Most of the nginx-specific logic should occur in ServerBloc (TODO: I haven't finished making this abstraction super clean, but it should be), an Nginx-specific types of directives that necessarily change the way that particular statement is parsed."
> what does this mean?

ServerBloc is an nginx-specific parsed object type, so functions that understand what Nginx directives are (beyond just a collection of tokens) should go in ServerBloc.

> so what does add_server_directives look like? which nodes need to be updated, and does that propagation happen manually or automatically?

`add_server_directives` on a vhost first updates the corresponding `ServerBloc` object. The `ServerBloc` handles parsing these directives and adding the resulting objects to its contents, and then updating the corresponding vhost.

> The easiest way to fix #5543 is changing the options in nginxparser.py. Are we instead going to leave 
 those, so we can better write things back out?

Since we still want to preserve the original configuration formatting, we should handle this kind of syntax at a level above `nginxparser`. The lowest-level `Sentence` object handles these nicely, by magically hiding spaces and quotations (similar to how `UnspacedList` does)

**Comment by ohemorange** [comment]
Ok actually I'm going to request that we break this PR into small pieces. Perhaps committing the building blocks first, then changing around higher-level pieces to use them, like we did with ACMEv2. Otherwise I'm going to keep trying to find a large-hour chunk of time to review this and continue to never manage to.

**Comment by sydneyli** [comment]
Splitting up.

**Pull request closed without merging**
