### PR TITLE
Add Azure DNS auth [WIP]

### PR DESCRIPTION
**Pull request by elmariofredo**
This is Work In Progress PR inherited from @eduvik I have to update/add tests same way as are in [dns cloudflare](https://github.com/certbot/certbot/blob/master/certbot-dns-cloudflare/certbot_dns_cloudflare/dns_cloudflare_test.py)

### CODE REVIEW

**Comment by schoen** [comment]
Thanks very much for working on this! Please let us know about your progress.

**Comment by dhilton** [comment]
Hey is there anything I can do / help with to get this PR merged? What work is remaining? 
Thanks for working on this 👍

**Comment by sydneyli** [comment]
Hi @elmariofredo -- there's actually another PR open for this here: #5221 ; is this PR building on top of that one?
Either way, both PRs are missing tests, and @joohoi gave advice for writing tests for this plugin in #5221. Let us know if you have further concerns/questions!

**Comment by raeder1986** [comment]
Thaks for working on this very usefull plugin! When we can hope for his appearance in the official certbot?

**Comment by sydneyli** [comment]
Closing this out in favor of #6261.

**Pull request closed without merging**
