### PR TITLE
[#5155] - replaces isinstance(x, str) with isinstance(x, six.string_types)

### PR DESCRIPTION
**Pull request by mvi-x**
as proposed by @ohemorange in #5155 to be Python3 safe.

### CODE REVIEW

**Comment by mvi-x** [comment]
mm something weird going on with the tests. I don't understand it fully, but I'd say the travis errors are not due to the changes in the pull.

**Comment by ynasser** [comment]
Hi @mvi-x! Thanks for the PR :)

You're correct, the Travis errors have nothing to do with you. I've submitted a PR to fix the underlying issue: https://github.com/certbot/certbot/pull/5214

**Comment by ynasser** [comment]
This looks great. Thanks @mvi-x!

**Comment by mvi-x** [comment]
Thanks @ynasser and @bmw: You've made it a wonderful experience to contribute.

**Comment by bmw** [comment]
I'm glad to hear it. If you want to continue working on Certbot and need help finding an issue to work on, please let me know!

**Comment by ynasser** [comment]
Thanks @mvi-x! I actually reviewed your PR in a Certbot Twitch livestream we did, which will soon be uploaded to Youtube. I'll let you know when we've uploaded it :)

**Comment by mvi-x** [comment]
@bmw: that is exactly the case. I went through issues with labels [area: documentation](https://github.com/certbot/certbot/labels/area%3A%20documentation) and [easy-fix](https://github.com/certbot/certbot/labels/easy-fix). I imagine, if any, these are the kind I may be able to help with at this point. 
I've been exploring #3867, but since I don't know the project structure yet and I'm worried it may be more than I can chew, I haven't posted to "claim" it or anything of the sort yet. If you can think of anything easier and/or higher priority, I'd be happy to give it a look.

@ynasser : Cool! I look forward to watching it.

**Comment by bmw** [comment]
If you'd prefer to work on another issue, I can help you find something, but #3867 is an important issue and shouldn't be too hard with a little guidance.

To accomplish that issue, you'd be working on `certbot/plugins/selection.py` and modifying `choose_configurator_plugins()`. I'd do this by creating a new function that takes the `config` parameter given to `choose_configurator_plugins()` and the `installer` that is returned at the bottom of the function. I'd have `choose_configurator_plugins()` call that function right before it calls `record_chosen_plugins()`.

Inside the function, you need to check that if `config.must_staple` is `True`, then the string "ocsp-stapling" is in the return value of `installer.supported_enhancements()`. If it's not, you should raise an exception. After that, you just need to write some simple unit tests in `certbot/plugins/selection_test.py`.

You can learn more about installer enhancements in `certbot/interfaces.py` if you're interested.

If you have any questions or would like me to help you find another issue, please let me know. Thanks for your continued interest!

**Pull request merged**
