### PR TITLE
Add flags to configure log rotation

### PR DESCRIPTION
**Pull request by sc-perth**
Provides a quick, and possibly keep-able, fix to certbot logging issues. Primarily: certbot handling log rotation on its own (--disable-log-rotation) & certbot keeping an insane number of logs (--max-log-count). Further details in #3602 
Thank you,

### CODE REVIEW

**Comment by sc-perth** [comment]
Honestly, I basically agree regarding syslog rotation. Once I made it so easy to have a single log file I lost all remaining motivation to integrate with syslog. The single, "static", log file will enable easy administration of the certbot logs, at least to the extent I desire. I've been wondering off and on if there's any reason to continue with integrating with syslog. I'm perfectly happy to go with: there isn't.

There probably is an off-by-one error with the `--max-log-count`, and it would be as trivial as you say to fix. You are also absolutely correct that the `--disable-log-rotation` is redundant and should be accomplished via setting the `--max-log-count` to one. Derp! :)

Currently I'm packing for vacation, but I'm taking my laptop so we'll see what happens.
Thank you for this quality CR, and your approach to push-back. Well said!

**Comment by St-Ranger** [comment]
Note that this change (`--disable-log-rotation`) will also address #2292

**Comment by bmw** [comment]
@sc-perth, I just wanted to check in. Are you still planning on working on this or would you like someone else to build on this PR and get it merged?

**Comment by sc-perth** [comment]
Will merge from master to resolve conflicts here soon.
Will likely need assistance w/ this round of test failures.

**Comment by sc-perth** [comment]
WELL, turns out development didn't wait on my slow self and you've all moved logging off into it's own file. :) Turns out I didn't need to fight w/ my system to install a 3 way merge tool after all! Oh well.

I've gotten my changes in log.py & cli.py against the current master HEAD. It's mostly passed testing.
Here's the current blockers I'm working on
1. `--max-log-count 1` appears to have a bug, or someone is doing something weird. When the argument of 1 is passed to the max-log-count flag I have certbot deleting the log target before creating the log handler. Yet _somehow_ that is causing a significant amount of debug logging to not appear in the log at the end of the run. I'm currently thinking it's because something is writing to the log prior to the creating of the log handler. See lines above line 546 in [this cli output](https://bpaste.net/show/d1b6c05df00d)
1. I'm assuming it will still fail QA testing

**Comment by sc-perth** [comment]
Yep `/certbot/main.py` is logging prior to calling for `cli.prepare_and_parse_args`.

**Comment by St-Ranger** [comment]
Just in case, - have you seen my https://github.com/certbot/certbot/issues/3602#issuecomment-288843538 , especially points 1) and 3)? 
(I didn't have a chance to look if others have done anything on those.)

**Comment by sc-perth** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I have seen your comments and consider them important. That said I'm ignoring them as they will/do cause me to overthink the options and delay progress. Once I have functioning & shipable code I will revisit them.
- --
Between A & B there's C.
GPG: 0xe818cb04b0a635fc
5b55 a483 138e 69e8 7be1
6bbe e818 cb04 b0a6 35fc
https://sks-keyservers.net/pks/lookup?op=get&search=0xe818cb04b0a635fc
Sent from my phone usind K9 Mail, pardon the typos (I hate autocorrect).

On May 11, 2017 9:12:52 PM EDT, St-Ranger <notifications@github.com> wrote:
>Just in case, - have you seen my
>https://github.com/certbot/certbot/issues/3602#issuecomment-288843538 ,
>especially points 1) and 3)?
>(I didn't have a chance to look if others have done anything on those.)
>
>--
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/certbot/certbot/pull/4195#issuecomment-300957446
-----BEGIN PGP SIGNATURE-----

iQFDBAEBCgAtJhxKb2huIEQuIEhhcmxhbiA8cGVydGhAc2VtaWNvc21pYy5uZXQ+
BQJZFQ4VAAoJELHPXx+MTRDUz4MH/0sdtqTH4tuhBwPgmLlhyVC7ihmhF6Bxv5g4
khAAZuWgo5h7nfrrUVCD1IeVTz/DMCrIMpfmeXiGq4BFwcfXYl0Qez6h2+e1IQZ0
odzDxZA4gaZWTvN4gmyevvYwp4yFLwOrGEpbe2wIq2Vdt8jVb/tereHqgiG9EXCN
snpU6HB3uUbB3Ho2KBWLnOYLKWkDsHxzKkXqqT1/a3cW8OzuiZBJOHuz1TmhRUj4
wm89wMbBLdRqAvfvcfcoRgf0i4uuv/cPykDSch+qFG3bbOYhnPBE/8Zp5NXCXITk
F+aURaH0VVn0NDLKKnyGzJbIUp7lNKwQCVckz0lHRgnD+o1Gcu8=
=1HBn
-----END PGP SIGNATURE-----

**Comment by bmw** [comment]
> Yep /certbot/main.py::main is logging prior to calling for cli.prepare_and_parse_args.

Yes there are logging calls, but logging is set up in `certbot.log.pre_arg_parse_setup` to properly handle this. No logging to a file is done until` certbot.log.post_arg_parse_setup` is called which is after the call to `prepare_and_parse_args`.

**Comment by bmw** [comment]
@sc-perth, I just wanted to check in again. Are planning to continue work on this or would you like someone to take it over?

**Comment by bmw** [comment]
Closing in favor of #4907.

Thanks for your work here! I used this PR as a base for #4907.

**Pull request closed without merging**
