### PR TITLE
Set permissions on private keys. [needs revision]

### PR DESCRIPTION
**Pull request by daztucker**

### CODE REVIEW

**Comment by schoen** [comment]
Thanks for looking into this issue -- I also saw on the forum that it was a topic of concern for people because private keys are indeed among the most sensitive files that may exist on the server.

@hlieberman, @pde suggested that you might have an idea about the Debian policy aspects of this (or already know of a plan for what our file permissions should be). In particular I'm wondering whether there are many systems where private keys ought to be group-readable, not just owner-readable, because the web server is running as e.g. user `httpd` group `httpd` (or `www`), while the `privkey.pem` might be owned by root. In that case it ought to be group-readable to allow the daemon to read it at startup.

@pde also suggested `440` instead of either `660` or `600` as a default (because there's normally no need to write to the privkey and because it would be helpful to warn people who are trying to delete it!) -- and finding a way to make the file modes configurable in addition to changing the default. (I don't know if there's work toward that in another PR yet.)

**Comment by schoen** [comment]
Tracked at #1473 which also shows @colincross is working on this problem too.

**Comment by hlieberman** [comment]
Debian policy doesn't specifically call out what the proper modes are for keys, if that's what you mean.

That being said, there's an example which we can probably steal wholesale, if not reuse: the snakeoil cert.

ssl-cert creates /etc/ssl/private, which is root:ssl-cert and 710, and the snakeoil cert inside is root:ssl-cert, 640.  That seems a reasonable choice to me to allow people to have daemons be able to read the certificates and keys.

Another option would be, for the nginx and apache plugins, to simply use whatever user that the thing is going to be running as, since we are parsing the config files anyway.  Not sure if I like that option more or less.

**Comment by colincross** [comment]
Sorry for the noise, I didn't realize github would put a note on the issue when I pushed to my local fork.  I'll put the issue in the pull request instead of the commit message next time.

Sendmail requires private keys to be at least 0600, which is what got me started on this:
STARTTLS=server: file /etc/letsencrypt/live/<domain>/privkey.pem unsafe: Group readable file

**Comment by schoen** [comment]
If someone else reviews this, note also the parallel PR #1760 for the same purpose.

**Comment by thomaszbz** [comment]
For symlinks from /etc/ssl/..., something like this would be nice:

    -rw-r--r-- 1 root root     2.1K Jan 17 17:54 cert1.pem
    -rw-r--r-- 1 root root     1.1K Jan 17 17:54 chain1.pem
    -rw-r--r-- 1 root root     3.2K Jan 17 17:54 fullchain1.pem
    -rw-r----- 1 root ssl-cert 3.2K Jan 17 17:54 privkey1.pem

These settings should be fine for e.g. Debian 8 / Apache.

I guess that users have different requirements (e.g. according to distro), so I think the permissions should be configurable via ``cli.ini`` and maybe via parameters (overwriting cli.ini settings).

I also want to note that wrong permissions (in the sense of user's requirements) cannot necessarily be healed by a later user interaction: Once the private key is readable after being written to disk with weak permissions, it could theoretically be stolen if the admin user changes permissions too late. Therefore, an _emtpy_ file with correct file permissions must be written to disk _before_ key material is written into the file.

I suggest to introduce three config values for cli.ini (including example settings):

    private-key-file-owner = root
    private-key-file-group = ssl-cert
    private-key-file-permisson = 640

Optionally, this could also be done for public key material (just for completeness).

**Comment by jsha** [comment]
This PR and #1760 both block on a design decision (#1473) about how exactly we want configuration of ownership and permissions to work. Closing for now; we can make or solicit a new PR once we've reached a conclusion on #1473.

**Pull request closed without merging**
