### PR TITLE
[Ignore] Testing augeas lens against full Travis suite

### PR DESCRIPTION
**Pull request by joohoi**

### CODE REVIEW

**Comment by bmw** [comment]
Can we close this PR?

(If there's any reason to keep it open, please do so.)

**Comment by joohoi** [comment]
Closing the pr, continuing testing.

**Comment by bmw** [comment]
Test farm tests pass and fail where expected using this branch. Failures were caused by other reasons. Output was:
```
0 ubuntu15.10 fail
1 ubuntu15.04LTS pass
2 ubuntu14.04LTS pass
3 ubuntu14.04LTS_32bit pass
4 ubuntu12.04LTS pass
5 debian8.1 pass
6 debian7.8.aws.1 pass
7 debian7.8.aws.1_32bit pass
8 amazonlinux-2015.09.1 fail
9 amazonlinux-2015.03.1 fail
10 RHEL7 fail
11 fedora23 pass
12 centos7 fail
13 centos6 pass
```

**Comment by joohoi** [comment]
Thanks for running the test farm against it. I'll continue digging in if it fixes some of our parsing problems, and would hence be an improvement over the existing one.

**Pull request closed without merging**
