### PR TITLE
update README

### LINKED ISSUE #4622: Update README.rst
This file hasn't really changed much in a long time and plenty of features have been added/removed. We should update it to reflect the current state of Certbot.

### PR DESCRIPTION
**Pull request by SwartzCr**
fixes #4622

### CODE REVIEW

**Comment by SwartzCr** [comment]
Do you know if that's a public list that people should be joining? I don't want to suggest it as another place where people can send bug reports, since we want that to happen on IRC and GitHub, in what way to do you imagine that people will be using it?

**Comment by bmw** [comment]
It is a public list but admins have to approve people joining/posting to the list. In my opinion, the purpose of the list should be Certbot development discussions (not bug reports), so with this in mind maybe we should list it in the developer guide rather than our README?

**Comment by SwartzCr** [comment]
Yeah, I think people would object to people joining it before contributing in other ways to the project

**Comment by bmw** [comment]
We've accepted people who were contributing for the first time by providing guidance on the list about things such as Debian updates, but I agree we don't want every Certbot user on the list.

**Pull request merged**
