### PR TITLE
Update pinned urllib3

### PR DESCRIPTION
**Pull request by bmw**
GitHub notified us about a security vulnerability in our pinned version of `urllib3` earlier this week. It doesn't affect us, but we might as well upgrade anyway. I checked:

* There are no backwards incompatible features we care about listed at https://github.com/urllib3/urllib3/blob/master/CHANGES.rst.
* urllib3's dependencies don't also need to be updated according to https://github.com/urllib3/urllib3/blob/1.24.1/setup.py.
* The hashes match when obtained from different network vantage points.

### CODE REVIEW

**Comment by adferrand** [comment]
Even extra secure? Because it requires cryptography 1.3, and currently we are pinned to 1.2. But it will not matter anymore soon.

**Comment by bmw** [comment]
> Even extra secure? Because it requires cryptography 1.3, and currently we are pinned to 1.2. But it will not matter anymore soon.

I think that's just our oldest tests where we also have an [older version of urllib3 pinned](https://github.com/certbot/certbot/blob/6c8652a0a68df61a59cc7edf2f813c69ed68df29/tools/oldest_constraints.txt#L24). Outside of that, we're currently using [cryptography 2.2](https://github.com/certbot/certbot/blob/6b145a480ef19309c84bfecc61465571172a4f3f/letsencrypt-auto-source/pieces/dependency-requirements.txt#L63).

**Comment by adferrand** [comment]
My bad, I mixed 1.x and 2.x...

**Comment by bmw** [comment]
No worries!

**Comment by bmw** [comment]
@ohemorange, are you able to review this simple change?

**Pull request merged**
