### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by noci2012**
Add description of credentials file.

### CODE REVIEW

**Comment by bodgit** [comment]
https://github.com/certbot/certbot/blob/master/certbot-dns-rfc2136/certbot_dns_rfc2136/__init__.py

**Comment by noci2012** [comment]
ah did try to find that ....
took good part of a day to find where the troubles might be.
As this info wasn't shown in the past.

Ok the documentatio is in the __init__.py

Thanks, that should make this change obsolete.

**Comment by noci2012** [comment]
This is a related issue: https://github.com/certbot/certbot/pull/5692

**Comment by noci2012** [comment]
this is not needed

**Pull request closed without merging**
