### PR TITLE
Remove dead autodeployment code

### LINKED ISSUE #4315: Remove dead autodeployment code
Remove dead code `autodeployment_is_enabled` and `should_autodeploy` in `certbot/storage.py` and relevant tests in `certbot/tests/storage_test.py`.

### PR DESCRIPTION
**Pull request by rishabhkumar296**
Removes deadcode in `autodeployment_is_enabled` and `should_autodeploy` and relevant tests

Fixes #4315

### CODE REVIEW

**Comment by adferrand** [comment]
It is not related to your PR, I am working on it on #6679.

**Comment by rishabhkumar296** [comment]
Ok, let me know if the commit requires changes and how to proceed further :)

**Comment by adferrand** [comment]
@rishabhkumar296, corrections have been merged to master to correct the integration tests. You can merge our master branch to your PR to fix the tests on it.

**Comment by rishabhkumar296** [comment]
Updated the commit.

**Pull request merged**
