### PR TITLE
Removed some unused imports.

### PR DESCRIPTION
**Pull request by atombrella**
## Pull Request Checklist

- [x] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [x] Include your name in `AUTHORS.md` if you like.

### CODE REVIEW

**Comment by ohemorange** [comment]
Thanks for making these changes! Any idea why we weren't warning about unused imports on this files previously?

**Comment by atombrella** [comment]
@ohemorange I don't know. Maybe @adferrand or @bmw would know? There are likely others, but they're rather difficult to find, since ` flake8` complains about imports that are ignored with `pylint` annotations, and also warns about type annotation imports.

Anyway, my PR is meant as something that I think looks wrong. I'd hope that someone who knows the code-base better than me is able to answer whether my intuition that these are unused imports is really true, or at least mark them as ignored.

**Comment by ohemorange** [comment]
What did you use to find these imports, `flake8`, `pylint`, something else? Could you check our lint code to see if it's run on these files, and if so, if we're accidentally including an option to ignore unused imports?

**Comment by atombrella** [comment]
PyCharm highlighted one or two when I had the files open, and then ran flake8 glancing over the results (you can instantly ignore a lot of the warnings from type annotations).

`pylintrc` has this, so I guess this would exclude `acme/__init__.py` I don't really know about the others. There's no explicit list of files that should be ignored. The `ignore-imports` setting guards against similarities in different files, e.g., `from __future__ import ...` across multiple files.

```ini
[VARIABLES]

# Tells whether we should check for unused import in __init__ files.
init-import=no

[SIMILARITIES]

# ...

# Ignore imports when computing similarities.
ignore-imports=yes
```

**Comment by ohemorange** [comment]
Looks like `certbot_ci` isn't in `tox.ini:source_paths`. To avoid this in the future, it should really be in there. If we run pylint on that though, there's several more errors. How do you feel about going through and handling those?

It's not surprising that it's not running on `certbot/tests`, that's a known issue.

That just leaves one file, but when I run `pylint` manually on `certbot/certbot/_internal/plugins/null.py`, it's not showing the errors. Any idea what could be happening there?

**Comment by atombrella** [comment]
> Looks like `certbot_ci` isn't in `tox.ini:source_paths`. To avoid this in the future, it should really be in there. If we run pylint on that though, there's several more errors. How do you feel about going through and handling those?

I already started a branch, and will open a PR with my fixes. Most of them are just silencing the errors, e.g., lots of `import os or 
`from ... import *`.

> It's not surprising that it's not running on `certbot/tests`, that's a known issue.

OK. 

> That just leaves one file, but when I run `pylint` manually on `certbot/certbot/_internal/plugins/null.py`, it's not showing the errors. Any idea what could be happening there?

No. I'll dig a bit :) I'm not so familiar with configuration of pylint. Ironically, PyCharm runs pylint in the background when analyzing the code, but completely ignores the annotations that something should be ignored.

**Review by adferrand — APPROVED** [review]
I wend ahead and tested this PR against master with lint, mypy and standard unit tests. LGTM!

**Pull request merged**
