### PR TITLE
Track 1.32.x dependencies

### PR DESCRIPTION
**Pull request by bmw**
This seems like a good idea to me personally but I'd love to hear others thoughts. Built docs look like:

Screenshot 2022-12-12 at 1 59 26 PM

### CODE REVIEW

**Comment by alexzorin** [comment]
What is the purpose of adding this file to `master`?

**Comment by bmw** [comment]
Check out the changed docs and the comments at the top of the file if you haven't already.

To build on that though, GitHub only scans for bad dependencies in your primary branch with no way I can find to configure it to really do anything differently.

**Review by alexzorin — APPROVED** [review]
Ah, I missed the explanation at the top of `requirements.txt`. Thanks.

It would be nice to place a reminder back to this file from `repin.sh` in the `1.32.x` branch, so that whoever updates the file does not forget to also update `master`. It may be so infrequent that we will forget or not know about this, depending who does it.

**Comment by bmw** [comment]
> It would be nice to place a reminder back to this file from `repin.sh` in the `1.32.x` branch, so that whoever updates the file does not forget to also update `master`. It may be so infrequent that we will forget or not know about this, depending who does it.

Since dependabot won't stop complaining about these warnings until this is done, I'm not sure how big of a problem this is, but messaging about it in `repin.sh` certainly wouldn't hurt. I can add this for the next 1.32.x point release.

**Pull request merged**
