### PR TITLE
Integrate the ECDSA certificates feature on master

### LINKED ISSUE #8366: Provide a documentation to migrate to ECDSA certificates
This issue concerns the ECDSA certificate generation feature provided by #8254. It is about to provide proper guidance to users in how to migrate to ECDSA certificates, as described in the design document: https://docs.google.com/document/d/18pr4F4SVim-bSR6izNV5ZYwolnvitTvmP6gqElDdZPU/edit?usp=sharing

Indeed we should write documentation with the recommended workflow for changing an existing certificate and an existing installation to use ECDSA keys, and also for requesting a new ECDSA certificate. This should include a warning that users who obtain certificates with ECDSA keys should be careful to not downgrade their Certbot version if they change installation methods because using ECDSA keys with older versions of the client is not supported by the Certbot team.

When this feature is released, someone from the core Certbot team should post this documentation to the community forum.

### PR DESCRIPTION
**Pull request by adferrand**
Fixes #8366 #2625

This PR integrates the `ecdsa` branch that includes five reviewed PRs (#8431, #8435, #8447, #8451 and #8464) into `master` to enable the ECDSA certificates feature officially in Certbot.

On top of this work remains only #8366 which is not related to code, but to documentation: once this PR is merged, a Certbot dev team member need to post on the Let'sEncrypt support forum to advertise about this new feature and describe the migration path to move from a RSA to an ECDSA key and warn about risks to downgrade Certbot in this case. The content of this post can be taken from the "Migrating to certificates based on ECDSA keys" section in `certbot/docs/using.rst`.

This PR should be **merged and not squashed** to preserve commits authorship.

### CODE REVIEW

**Comment by adferrand** [comment]
All features are integrated. As said by @bmw in https://github.com/certbot/certbot/issues/8366#issuecomment-729932486:

> If it lands, all I think we need to do here is to update the Certbot submodule on the website repo after our next release and add a comment to the thread for the release linking to these docs.

**Comment by bmw** [comment]
I started a run of the full test suite on this branch at https://dev.azure.com/certbot/certbot/_build/results?buildId=3042&view=results. If it passes, I think we can merge this 🎉

**Comment by adferrand** [comment]
It passes 💯

**Comment by adferrand** [comment]
One reminder: do not forget to merge it instead of squash.

**Review by bmw — APPROVED** [review]

**Comment by bmw** [comment]
Merged. Thanks to everyone who helped us work on this!.

**Pull request merged**
