### PR TITLE
Takes position in site-config-file in consideration when removing dup…

### PR DESCRIPTION
**Pull request by michi-roth**
Takes position in site-config-file in consideration when removing duplicates. This is a solution for #2275

### CODE REVIEW

**Comment by pde** [comment]
@michi-roth you have some [lint failures](https://travis-ci.org/letsencrypt/letsencrypt/jobs/104687557#L1795) but they should be easy to fix.

**Comment by michi-roth** [comment]
I modified the code to pass the pylint test. But no the Python2.6 build staled. Can someone please rerun the build.

**Comment by pde** [comment]
@SwartzCr  do you want to review this?

**Comment by SwartzCr** [comment]
@pde sure, I'd be happy to

**Comment by SwartzCr** [comment]
@michi-roth have you tested these changes? Can you give more detailed information about the type of situation that you're trying to code around. I'm afraid that there are other places where we don't support multiple vhosts per file - and allowing them to be parsed will cause other issues to arise that aren't addressed in this PR

**Comment by pde** [comment]
We don't have a clear positive review for this, and don't currently believe we have working support for conf files for multiple vhosts, so moving this out of the 0.5.0 train.

**Comment by SwartzCr** [comment]
@michi-roth would you mind fixing the merge conflicts, they likely sprouted after the rename but shouldn't be hard to resolve

**Comment by pde** [comment]
@SwartzCr you may want to evaluate whether this is a useful part of a #1042 solution, and use or close accordingly.

**Comment by bmw** [comment]
As I explained in #2275, our Apache plugin has never supported multiple vhosts per file. While we certainly appreciate the PR, a larger change has to be made to the Apache plugin to properly support multiple vhosts per file which we're currently working on in #3373. You can expect to see this feature added soon.

**Pull request closed without merging**
