### PR TITLE
Explained what is standalone mode in the documentation for #3451

### PR DESCRIPTION
**Pull request by muhammednagy**

### CODE REVIEW

**Comment by pde** [comment]
This travis failure in the `-oldest` environments looks unrelated to this PR, will investigate with @bmw tomorrow.

**Comment by bmw** [comment]
Sorry about the Travis failures. They were unrelated to this PR and have been fixed. Rerunning your Travis build.

**Comment by muhammednagy** [comment]
No problem

**Comment by bmw** [comment]
I agree with @pde that I'd prefer not to land this change as is. Since we haven't see any further revisions, I'm closing this PR, but feel free to open a new one with new proposed changes if you'd like to continue to work on it.

**Comment by muhammednagy** [comment]
Okay I will work on explaining it

**Pull request closed without merging**
