### PR TITLE
Update using.rst

### PR DESCRIPTION
**Pull request by charlyhong**
Add third-party plugin using SOLIDserver

## Pull Request Checklist

- [ ] The Certbot team has recently expressed interest in reviewing a PR for this. If not, this PR may be closed due our limited resources and need to prioritize how we spend them.
- [ ] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [ ] Add or update any documentation as needed to support the changes in this PR.
- [ ] Include your name in `AUTHORS.md` if you like.

### CODE REVIEW

**Comment by osirisinferi** [comment]
Note that the use of `zope.interface` is deprecated a long time now and support for it was removed in Certbot 2.0.0.

**Comment by alexzorin** [comment]
The story about `zope` is a little more complicated. See https://github.com/certbot/certbot/wiki/Certbot-v2.x-Plugin-Compatibility#supporting-new-and-old-versions-of-certbot-in-a-plugin. Basically, if you want to support both old Certbot and new Certbot, you should continue to declare the `zope` interfaces, but you will need to explicitly add it as a dependency  to your `setup.py`.

**Review by alexzorin — APPROVED** [review]
Thank you for your contribution.

**Comment by alexzorin** [comment]
We had to revert this PR because it was opened against the `2..6.x` branch rather than `master`. If you want to be included in the list, please create a new PR against the `master` branch.

**Comment by charlyhong** [comment]
Sorry for my mistake. I've recreated a new PR on master branch. Thank you.

**Pull request merged**
