### PR TITLE
Gandi DNS Authenticator

### PR DESCRIPTION
**Pull request by martinplaner**
This PR implements an authenticator for the Gandi LiveDNS API. Code is mostly based on the existing DNSimple authenticator. 

Some remarks:
- This should (partially) satisfy #5582.
- ~~Currently only the newer [Gandi LiveDNS API](https://doc.livedns.gandi.net/) is supported. The older [RPC API](https://doc.rpc.gandi.net/) is _not_, since I no longer have any domains managed through this API. Maybe someone else can implement this in the future, possibly with an appropriate command-line switch.~~
- I had to bump lexicon to 2.4.1 for it to support the LiveDNS API.

### CODE REVIEW

**Comment by liaohuqiu** [comment]
Hi, who can check this?

**Comment by jbauson** [comment]
Wooohoooo!! Waiting to get this implemented! 👍

**Comment by adferrand** [comment]
@martinplayer, just to let you know that I have an incoming PR on Lexicon for my Gandi provider: AnalogJ/lexicon#274. When merged, you should use auth_api_protocol instead of api_protocol. The parameter api_protocol will continue to work, but will generate a deprecation warning when used.

Furthermore I think I still have a domain on RPC, so we could do something to implement the old API.

**Comment by martinplaner** [comment]
@adferrand Thanks for the heads up! I wasn't quite sure how this project handles external dependencies, so I didn't bump the required lexicon version to the latest. But if we end up with the latest version and your PR is merged, I'll gladly change it to work with future lexicon versions.

Regarding the RPC API, it shouldn't be that complicated to support both APIs (except testing would have to be done by someone else, as mentioned before), but there are 2 smalls decisions to be made that I'd like the maintainers to comment on before implementing:

- How to switch between protocols, additional flag or some switch in the credentials file? ( Since 

- Which API should be the default one, if none is set by flag/config? Just mirror Lexicon behavior and use RPC by default?

**Comment by adferrand** [comment]
Just to keep informed here. With @AnalogJ we discussed a lot on AnalogJ/lexicon#274. We are going to an approach implying to keep --api-protocol, so there will be no `--auth-api-protocol`.

For you questions @martinplaner:
* About the protocol switch, you can check OVH plugin, also backed by Lexicon, were the parameter `endpoint` is exposed. It toggles which endpoint will be used to reach the OVH API. I think it is quite similar to problematic of choosing the protocol. So maybe you could use a parameter here also.
* In fact your second question is closely related to the first one: the procotol (RPC or Live) defines the endpoint to use and all the logic behing in the Lexicon provider. So if you have a parameter to choose between RPC or Live, you have everything you need.
* About which protocol to use by default, I choose in Lexicon the RPC one, with the idea to change someday to Live, when RPC support is dropped or usage becomes negligeable. For now it is not the case, so I would advise to use RPC by default.

**Comment by FauxFaux** [comment]
I rebased this PR, touching only `tox`/`venv` conflicts (`.sh` -> `.py` move).

**Comment by brandond** [comment]
What's blocking this from moving forward at this point?

**Comment by adferrand** [comment]
Currently most of the certbot team is on hollydays. So I think work will start again on January. There is also big discussions about how to integrate and maintain dns plugins in Certbot, so plans may change about PRs concerning DNS plugins.

In the mean time, if you need right now certificates validated against dns challenges using gandi, and have access to Docker, you may be interested by the container I maintain for that purpose by orchestrating Certbot and Lexicon together: https://github.com/adferrand/docker-letsencrypt-dns

**Comment by brandond** [comment]
Thanks @adferrand I'll take a look at that! I'd found the one that @martinplaner published a while back at martinplaner/certbot-dns-gandi on docker hub, which seems to be working so far.

**Comment by luyseyal** [comment]
:100: Thank you for making this.

**Comment by MTCoster** [comment]
Does anyone have an ETA for when this will be merged?

**Comment by adferrand** [comment]
As I said in my previous comment here, where are currently working to find the most relevant solution that will allow Certbot to interact with various DNS providers, while ensuring a sustainable support for the Certbot team.

So currently we are freezing integration of new DNS plugins, without an ETA for when the situation will change so far. We are really sorry about that.

In the mean time, you can have a look at the Docker project that I actively maintain. It could match your needs. See my previous post here for the link.

**Comment by wxcafe** [comment]
Hey! Is DNS plugins integration still frozen? Some of our customers have asked us why we (gandi) are not supported by the official client and they need to install a plugin to automate their certificate renewal

**Comment by vielmetti** [comment]
It's the end of the year, @adferrand - has there been movement on the planning for updating this?

**Comment by wxcafe** [comment]
Hey! Is DNS plugins integration still frozen? Some of our customers have asked us why we (gandi) are not supported by the official client and they need to install a plugin to automate their certificate renewal

**Comment by wxcafe** [comment]
Sorry to ping this again, but it's been four months. Any news?

**Comment by m0namon** [comment]
Apologies @wxcafe, we are still not accepting DNS plugins at the moment. We want to make a decision on #6464, #6503, and #6504 first.

@martinplaner -- you're welcome to leave your PR open, but we probably won't be able to give any feedback on it for a while. In the meantime, you're welcome to release it as 3rd party plugin if you want like others have done. See https://github.com/coldfix/certbot-dns-netcup for one example of that.

**Comment by martinplaner** [comment]
I'll close this PR for the time being. I've personally moved away from using certbot since creating this request, so I'm no longer in active need for this plugin.

Also I haven't touched it since then and I doubt it will still work as-is, or at least will require some rework after the blocking issues are resolved.

If anyone still requires this functionality and feels up to the task, please feel free to take this PR as your basis.

**Pull request closed without merging**
