### PR TITLE
Remove local-oldest-requirements files

### PR DESCRIPTION
**Pull request by bmw**
This is part of https://github.com/certbot/certbot/issues/8787. I got a +1 from our packagers at major distros in https://github.com/certbot/certbot/issues/8761. You can see the full test suite passing on this PR at https://dev.azure.com/certbot/certbot/_build/results?buildId=4074&view=results.

### CODE REVIEW

**Comment by adferrand** [comment]
I would like to challenge a bit the usage of variables in the `requires` section of the `setup.py` files. For sure it gives a fast and self-contained way to ensure that higher level components always require at least the same version for the lower level component that they depends on, thanks to the fact that `setup.py` is an actual interpreted Python file.

However I feel that this is not in sync with the recent evolutions of Python packaging, in particular the increasing usage of `pyproject.toml`. One of the main point to give this standard static file is indeed to stop having the possiblity to run arbitrary Python code during the setup of an sdist.

Since our `release.sh` already takes care to bump up the version of the packages themselves, and since you remove some logic about oldest requirements in it, giving space for other logic without an added overall complexity, how about write explicit versions requirements in the `setup.py`, and make `release.sh` bump them up alongside with the package versions ?

**Comment by bmw** [comment]
We could do that and I will if you still want me to after reading this post, but I'd honestly rather not. 

I agree with Python moving to a static file instead of `setup.py`, but while we still have a `setup.py`, I don't think limiting how we use it in this way buys us much. I also personally like that the plugin version is coupled to the acme/Certbot version since I think that this coupling is essentially what we want to accomplish here and it prevents the two versions from diverging.

Switching to declaring the acme/Certbot versions separately is some work that may make it slightly easier to switch to `pyproject.toml` in the future, but I personally don't think whether it's done now or later is a big deal and I'd rather do it when/if it's needed instead of blocking this PR on it.

**Review by adferrand — APPROVED** [review]
I guess that handling the version dependency again in the release script will not be the biggest part of moving to `pyproject.toml`, given all the dynamic stuff that is in the `setup.py` of certbot package.

So this LGTM !

**Comment by bmw** [comment]
I appreciate the flexibility 😄 

This will need one more +1 since I resolved the merge conflicts from the release and moved the changelog to the right section.

**Review by adferrand — APPROVED** [review]

**Pull request merged**
