### PR TITLE
Fix linux-py39-cover test

### PR DESCRIPTION
**Pull request by ohemorange**
This was failing on master. These changes fix the issue, as shown by the test now passing: https://dev.azure.com/certbot/certbot/_build/results?buildId=3606&view=logs&j=24802871-fa51-53e8-3cb5-265cf7a30276

I ran the full test suite just to check that we didn't accidentally mess up anything else, since the branch that these changes come from had quite a few other changes, so it'll probably take a bit for everything to finish.

### CODE REVIEW

**Review by bmw — APPROVED** [review]
Assuming there are no interesting test failures, this LGTM. The `linux-py37-nopin` failure isn't related to this PR and is due to the new `zope.component` release last night.

**Comment by ohemorange** [comment]
Looks like the snap build is broken also due to the zope thing. Wow, the state of testing right now... Anyway, I think it's worth it to merge this so we at least have one test failure fixed, and particularly that all our PR tests pass; at worst, we've exchanged one test failure for another due to the 2 we can't check right now because of zope.

**Comment by bmw** [comment]
I completely agree with merging this but snap builds failing for the same reason is something I think we should look into. Everything is supposed to be pinned outside of the unpinned test....

**Comment by ohemorange** [comment]
I thought I mentioned it, but just for posterity: snap builds were failing because they were attaching to in-progress builds from the other test branch.

**Pull request merged**
