### PR TITLE
add IONOS Cloud DNS plugin to the documentation

### PR DESCRIPTION
**Pull request by zak905**
Hi Certbot team, 

We have created recently a certbot plugin that integrates with the [IONOS DNS Cloud](https://github.com/ionos-cloud/certbot-dns-ionos-cloud) API. This change adds the plugin to the Third party plugins list in the docs. 

## Pull Request Checklist

- [ ] The Certbot team has recently expressed interest in reviewing a PR for this. If not, this PR may be closed due our limited resources and need to prioritize how we spend them.
- [ ] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [x ] Add or update any documentation as needed to support the changes in this PR.
- [ ] Include your name in `AUTHORS.md` if you like.

### CODE REVIEW

**Comment by rijeshharidas** [comment]
@bmw Can you help review this?

**Comment by rijeshharidas** [comment]
> @bmw Can you help review this?

or @wgreenberg ?

**Comment by wgreenberg** [comment]
Hi @rijeshharidas, as we mention [in the docs](https://eff-certbot.readthedocs.io/en/latest/contributing.html#writing-your-own-plugin), we're currently not accepting any new first-party plugins into the project. But you can still release this as a third-party plugin: [certbot-dns-ispconfig](https://github.com/m42e/certbot-dns-ispconfig).

**Comment by wgreenberg** [comment]
Ugh my apologies for not reading this carefully -- this looks fine, and I'm happy to review/merge it.

**Review by wgreenberg — APPROVED** [review]
lgtm, thanks!

**Comment by zak905** [comment]
great thanks

**Comment by zak905** [comment]
@wgreenberg when will this be released ?

**Comment by dlenski** [comment]
This is obviously about 2 years too late, but the _naming_ chosen here, and used in the documentation, is extremely confusing.

There are (at least!) two different DNS management services that use IONOS APIs:

1. Managing DNS settings for domain names using [IONOS Cloud DNS](https://cloud.ionos.com/network/cloud-dns), which hosts DNS servers in the IONOS cloud.

   This is what https://github.com/ionos-cloud/certbot-dns-ionos-cloud works with. It is developed by IONOS itself. Note the name _certbot-dns-ionos-**cloud**_ of the relevant repository.

1. Managing DNS settings for domain names registered at IONOS.

  
   This is what the https://github.com/helgeerbe/certbot-dns-ionos plugin handles. I've recently [forked and revived](https://github.com/dlenski/certbot-dns-ionos) this plugin and fixed several issues, including race conditions with its creation and deletion of TXT records.

  Note the name _certbot_dns-ionos_ of the relevant repository, which *predates* the IONOS-developed one by many years.

I've attempted to rectify and clarify this situation in #10638.

**Comment by zak905** [comment]
Hi @dlenski, 

Thanks for the initiative. As a member of the IONOS DNS cloud team, I can understand the confusion. IONOS and IONOS Cloud have two distinct APIs which lead to the necessity of having two distinct plugins. Because the old plugin is not listed, we have chosen that name. It makes sens to make a distinction, if we are to list both. 

There is also another concern related to the entry point and the module name which we will address soon: https://github.com/ionos-cloud/certbot-dns-ionos-cloud/issues/21

**Pull request merged**
