### PR TITLE
Implements support for ECDSA keys. Fixes #2163.

### LINKED ISSUE #2163: Support ECDSA subject keys
Boulder now supports [ECDSA subject keys](https://github.com/letsencrypt/boulder/pull/1298), and although it isn't deployed just yet it will be soon.  So we may want to add acme and cli support for making P384 and P521 subject keys.

### PR DESCRIPTION
**Pull request by atombrella**
Continued from #8254 Please note the ecdsa branch is not completely up-to-date with the master-branch(!)

I'm not sure about the conflict with run on existing certificates. I'm willing to have a look at it, but a few hints are appreciated.

I added some code as `NamespaceConfig.key_type`, but I had to wrap an try-except around it, since the tests were failing without it. Again, please hint if there's a better way to deal with this.

I'm hoping this will eventually be in a release of `certbot`.

Thanks to @pahrohfit and @Tomoyuki-GH for previous efforts to implement
suport for this.

Co-Authored-By: Robert Dailey <rob@wargam.es>
Co-Authored-By: Tomoyuki-GH <55397638+Tomoyuki-GH@users.noreply.github.com>

## Pull Request Checklist

- [x] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [x] Include your name in `AUTHORS.md` if you like.

### CODE REVIEW

**Comment by adferrand** [comment]
@atombrella I updated `ecdsa` branch against `master`.

**Comment by adferrand** [comment]
Why the changelog is completely different ?

**Comment by atombrella** [comment]
I'll re-open this in a new PR. Please don't let the ecdsa diverge from master, or this becomes a mess!

**Comment by ivandeex** [comment]
continued in https://github.com/certbot/certbot/pull/8431

**Pull request closed without merging**
