### PR TITLE
Remove Certbot + DNS plugins Dockerfiles

### PR DESCRIPTION
**Pull request by adferrand**
Since https://github.com/certbot/certbot-docker/pull/1 has landed, we can now remove the Dockerfiles from the certbot/certbot GIT repository, since their build and deployment will be handled by certbot/certbot-docker GIT repository.

In parallel to this PR, and to prepare the next release, certbot/certbot + all certbot/dns-* DockerHub projects must be migrated to the Autobuild configuration described in https://github.com/certbot/certbot-docker/blob/master/README.md.

Also the Docker release process (or at least the link mentioned above) should be added to the EFF documents describing the release workflow.

### CODE REVIEW

**Comment by joohoi** [comment]
I think there could be value in leaving the Dockerfiles in place, but replacing the contents with a comment directing the users to the maintained repository with fresh Dockerfiles. Some people like to build their own Docker images and expect to find the files from the open source repositories.

**Comment by adferrand** [comment]
You have the `Dockerfile-dev` for that, which allows you to build a docker using directly certbot sources. Also, maybe we can add documentation about how to build the dockers from the `certbot-docker` project. What bother me a little about leaving Dockerfile in place, is that in your proposition, it is more things like fake Dockerfiles, and if they stay functional, we have a synchronicity problem between these Dockerfiles and the ones from `certbot-docker` project.

**Comment by purificant** [comment]
https://github.com/certbot/certbot-docker/pull/1 is 404 at the time of writing, has this repo moved elsewhere?

**Comment by adferrand** [comment]
Yes, we had to move the repository to another organization, to avoid to give too much elevated rights on `certbot/certbot` GIT repository to Dockerhub.

The equivalent of my PR in the removed `certbot/certbot-docker` is the commit: https://github.com/certbot-docker/certbot-docker/commit/5c48f7545f130955db84daa9d45d9cff62d3ba45

**Comment by purificant** [comment]
Great, thank you @adferrand!

**Pull request merged**
