### PR TITLE
Improve "cannot find cert of key directive" error (#5525)

### PR DESCRIPTION
**Pull request by eicksl**
Addresses [#5525](https://github.com/certbot/certbot/issues/5525).
@jsha 

*Fix code to log separate error messages when either SSLCertificateFile or SSLCertificateKeyFile directives are not found

*Update the section in install.rst where the relevant error is referenced

*Edit a docstring where 'cert' previously referred to certificate

*Edit test_deploy_cert_invalid_vhost in the test suite to cover changes

### CODE REVIEW

**Comment by jsha** [comment]
Looks like the coverage tests are failing. You probably need to add a new unittest that covers the new `elif`.

**Comment by jsha** [comment]
Did you mean to close this? You're pretty close to having it ready. Would you like help with writing the unittest?

**Comment by eicksl** [comment]
Sorry, just reopened it. I'll try to update the branch later today with the unit test and let you know if I have any trouble.

**Comment by jsha** [comment]
Great, thanks so much for your help! I definitely appreciate it.

**Comment by eicksl** [comment]
@jsha Let me know what you think!

**Comment by jsha** [comment]
This is great, thanks @eicksl !

**Pull request merged**
