### PR TITLE
expand nginx no name error

### LINKED ISSUE #4792: Nginx should give a prompt when it can't find a server_name
When the nginx plugin can't find a server name it doesn't give you any
advice on what to do. It should tell you to add a server_name directive
to your nginx config and hint at where that might be.

### PR DESCRIPTION
**Pull request by SwartzCr**
fixes #4792

### CODE REVIEW

**Comment by ohemorange** [comment]
As discussed out of band, let's reword to the form of "here is what we would have needed" so that they go look up information about it in a higher-bandwidth source, instead of phrasing it as "go make this particular change."

Also, it's missing a trailing period.

**Comment by SwartzCr** [comment]
@ohemorange want to review again?

**Comment by ohemorange** [comment]
I thought we were planning to change the language instead of pointing directly to a link that might rot?

**Comment by SwartzCr** [comment]
I think it's unlikely that the official nginx docs link will rot. I think this is likely the highest bandwidth source of information for a user

**Comment by SwartzCr** [comment]
@ohemorange how does that look?

**Pull request merged**
