### PR TITLE
Stop rejecting punycode domain names

### LINKED ISSUE #3619: Support requesting IDNA2008 Punycode domains
As a step toward #3614

### PR DESCRIPTION
**Pull request by schoen**
First cut at not rejecting punycode names.

Probably fixes #3619.

### CODE REVIEW

**Comment by schoen** [comment]
@jsha you should be able to use this to test punycode support in Boulder now. Sorry it took me a while (even though it's basically just commenting out a single check that prohibited punycode names); I had some weird problems with tests, including having things pass locally that failed in Travis.

**Comment by schoen** [comment]
@jsha Also, @bmw told me that if you can update the Boulder https://github.com/letsencrypt/boulder/tree/docker-integration branch to merge Boulder's master, we could add an integration test on the Certbot side to start actively testing the ability to issue for punycode names.

**Comment by bmw** [comment]
After talking to @schoen, I also noticed [this comment](https://github.com/certbot/certbot/blob/master/tests/boulder-fetch.sh#L5). It's quite possible this change landed without us knowing and we can just start using boulder's `master` branch in our tests.

**Comment by jsha** [comment]
@schoen can you update this to actually remove the commented-out sections, so we can merge it?

**Comment by jsha** [comment]
FYI @bmw, I just tried this at https://travis-ci.org/jsha/certbot/builds/168435605, and got failures. Will debug and possibly send a PR.

**Comment by schoen** [comment]
> @schoen can you update this to actually remove the commented-out sections, so we can merge it?

OK, I pushed a commit that removes the comments.

**Pull request merged**
