### PR TITLE
Add warning when renewing cert less than 25 days old

### PR DESCRIPTION
**Pull request by chimeworld**
## Pull Request Checklist

- [x] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [x] Include your name in `AUTHORS.md` if you like.

### CODE REVIEW

**Comment by ali-alsabbah** [comment]
This should resolve #6719. It's possible my warning here is too verbose.

**Comment by ali-alsabbah** [comment]
@jsha can you take a look?

**Comment by bmw** [comment]
Thanks for the PR @ali-alsabbah.

We're planning on doing a thorough sweep of our open PRs in the next few weeks and should be able to review this PR then.

**Comment by osirisinferi** [comment]
Certbot users can manually change the default interval of 30 days to less than 30 days. Or even less than 25 days.vPerhaps consider a check if interval isn't 30 days or less than 25 days?

**Comment by ali-alsabbah** [comment]
@osirisinferi do you mean an interval != 30 AND not <25?

**Comment by osirisinferi** [comment]
I was thinking more of intervals < 30 days.

**Comment by osirisinferi** [comment]
This would still flood my e-mail with warnings from `certbot`s cronjob for 20 days if I've set the value `renew_before_expiry` to "10 days" in my renewal configs. It will start sending out emails from day 29 until day 10.

Could you add a check using `interval` so when people did actually have automated everything, but used a lower `renew_before_expiry` value won't get cron-spammed?

**Comment by ali-alsabbah** [comment]
@osirisinferi does this change solve your concern?

**Comment by osirisinferi** [comment]
My un-experienced Python eye says "yes", but I'll let the final judgement be done by someone with sufficient Python/certbot knowledge :stuck_out_tongue:

**Pull request closed without merging**
