### PR TITLE
Setup a timeout to the remote snap build process

### PR DESCRIPTION
**Pull request by adferrand**
This PR adds a `--timeout` flag to `tools/snap/build_remote.py` in order to fail the process if the time execution reaches the provided timeout. It is set to 5h30 on the relevant Azure job, while the job itself has a timeout of 6h managed on Azure side. This allows a slightly better output for these jobs when the snapcraft build stales for any reason.

The timeout cleanup is not perfect, since the `snapcraft` calls started from subprocesses are not terminated by the Python script. Azure kills any child process up to 10 seconds after the main process finished. However handling from the Python script would significantly increase the complexity, will not provided a significant avantage.

A snap build using a timeout of 10 seconds can be seen here: https://dev.azure.com/certbot/certbot/_build/results?buildId=3071&view=logs&j=ca2aa996-3000-528f-2c15-4e35d6e2aaa9&t=6b8d8f83-a960-5842-1f93-f9b9a106898f

### CODE REVIEW

**Comment by bmw** [comment]
I think it'd be nice to try and properly clean up (or shut up) child processes if we can. Looking at https://dev.azure.com/certbot/certbot/_build/results?buildId=3071&view=logs&j=ca2aa996-3000-528f-2c15-4e35d6e2aaa9&t=6b8d8f83-a960-5842-1f93-f9b9a106898f, the last line of output is about these hanging child processes rather than the actual error. We know now that the true cause of the error was the timeout and the second sentence in the error message maybe helps suggest that, but I do think it's reasonable for someone who is less familiar with the code or us in the future when we've forgotten the details to look at that output and think that something related to the output streams was part of the cause for the failure.

So to push back a bit, do you still think it's significantly more difficult or complex to clean up the child processes and that it's not worth doing? Please say yes if that's what you think, but I think I'll be tempted to take a shot at it myself before accepting this PR as is and I'd rather not add that to my TODO list.

**Comment by adferrand** [comment]
Well, my initial intention was of course to find a way to shutdown the snapcraft instances, but it is quite tricky to do so. I would need to find a way to propagate a signal up to `_execute_build()`, certainly with an `Event`, to hook into the loop that is parsing the output to break it and send the `SIGTERM` to `snapcraft`. But even like this we would still be dependant on the loop unblocking on its next iteration, so waiting for the new line of the process, or change significantly the parsing logic, or add another `Process` to react asynchronously.

So yes, sadly I think it is quite complex, and do not think it is worth a shot as of now...

**Comment by bmw** [comment]
Do we need to shut them down cleanly to squelch the output? I wouldn't expect us to.

If not, I think it'd require a little refactoring but at first glance doesn't seem _too_ bad. What if we refactored thing a bit to move `_run` back into the main process and then refactor things further to either:

1. Be able to just call `join` on the state process with a timeout by having it know when the build processes are finished
2. Repeatedly call to `async_result.get` with a shorter timeout or the remaining time until the full timeout which could be updated between calls to `get`

In any case, if the timeout is reached, we'd kill all processes before exiting the program.

That too seem infeasible or like too much work to you?

**Comment by adferrand** [comment]
Ok this is better. A new snap build using a timeout of 10s and latest update on this PR: https://dev.azure.com/certbot/certbot/_build/results?buildId=3157&view=results

I followed your advice and made necessary refactorings so that the timeout logic is not handled by a join() on the entire build (previously `_run` function). Indeed it seems that processes inside processes does not play well in term of cleanup. When you have one layer of child processes (in term of `multiprocessing.Process`), the parent process is capable to clean properly all of them, including the `subprocess` calls that could have been started by the child processes.

However trying to pass any reference to a child process to another child process (like the `async_result` array, the `multiprocessing.Pool` itself, or any reference to `multiprocessing.Process`) is not working as expected, and the actual state of processes cannot be retrieved from children. I think it is because normally a child process cannot see its siblings, only the parent can. Anyway, I solve that by using a `manager` dict to achieve your proposition 1), make the state process aware of when the snapcraft builds are finished.

**Comment by adferrand** [comment]
Real snap build (with normal timeout) here: https://dev.azure.com/certbot/certbot/_build/results?buildId=3158

**Review by bmw — APPROVED** [review]
Nice! Thanks for doing that.

I had initially imagined also terminating the `async_result` objects in the `finally` block, however, I didn't know that they do not have an API to allow you to do that. It looks like that's not necessary though. I kicked the build and there is still no output about IO problems so this LGTM!

**Comment by adferrand** [comment]
> I had initially imagined also terminating the `async_result` objects in the `finally` block, however, I didn't know that they do not have an API to allow you to do that.

No it is done through the termination of the pool that is handling the async map (with `terminate()`) and here is done implicitly by the context manager.

**Comment by bmw** [comment]
Oh I see! Thanks for the explanation.

**Pull request merged**
