### PR TITLE
Remove deprecated functions

### LINKED ISSUE #9302: Remove certbot.crypto_util.init_save_csr, certbot.crypto_util.init_save_key, and certbot.compat.misc.execute_command
These functions have been deprecated for some time and have better replacements.

### PR DESCRIPTION
**Pull request by wgreenberg**
This is meant for 2.0, but we don't have a tracking branch for that yet

Closes #9302.

### CODE REVIEW

**Review by alexzorin — CHANGES_REQUESTED** [review]
2022-06-07T00:48:12.8409299Z ************* Module certbot.crypto_util
    2022-06-07T00:48:12.8411628Z certbot/certbot/crypto_util.py:18:0: W0611: Unused import warnings (unused-import)
    2022-06-07T00:48:12.8413086Z certbot/certbot/crypto_util.py:38:0: W0611: Unused import zope.component (unused-import)

**Review by alexzorin — APPROVED** [review]

**Review by alexzorin — CHANGES_REQUESTED** [review]
Just looking at this, it seems like `certbot.compat.misc.execute_command` hasn't actually been removed.

**Comment by wgreenberg** [comment]
lol oops, actually removed it this time!

**Review by alexzorin — DISMISSED** [review]
😆

**Review by alexzorin — DISMISSED** [review]
Oops, forgot to change the branch.

**Review by alexzorin — APPROVED** [review]

**Pull request merged**
