### PR TITLE
Add shim for RHEL6

### PR DESCRIPTION
**Pull request by jsoref**
#7390

## Pull Request Checklist

- [x] Edit the `master` section of `CHANGELOG.md` to include a description of
  the change being made.
- [ ] Add [mypy type
  annotations](https://certbot.eff.org/docs/contributing.html#mypy-type-annotations)
  for any functions that were added or modified.
- [ ] Include your name in `AUTHORS.md` if you like.

### CODE REVIEW

**Comment by joohoi** [comment]
The testing error is not caused by this PR, so no worries there. Are you planning to add your name to `AUTHORS.md` or should we proceed?

**Comment by jsoref** [comment]
I'm fine without my name in authors. I've already contributed and don't really need my name everywhere. I'm not opposed to it being there either.

**Comment by joohoi** [comment]
You have been contributing in various ways throughout the years, and I feel it'd be fair for you to have your name in the `AUTHORS.md`. Making that change and pushing the changes would also organically re-initiate the tests.

**Comment by jsoref** [comment]
Sorry, looks like I'm already there: https://github.com/certbot/certbot/blame/745ef6e869085ace1678cbec72ed11d82a1376ed/AUTHORS.md#L126

**Comment by kmaehashi** [comment]
@jsoref Sorry, I overlooked your PR and proposed a patch (it's almost exactly the same contents as yours) in #7401, and it has merged 3 days ago. I hope you don't get me wrong🙇

**Comment by jsoref** [comment]
No worries. I just want it fixed. As noted, I really don't care about credit.

**Comment by adferrand** [comment]
OK, I close the PR, since another PR fixed the issue.

**Pull request closed without merging**
