### PR TITLE
Include new nginx config file in package.

### PR DESCRIPTION
**Pull request by bmw**

### CODE REVIEW

**Comment by bmw** [comment]
If you're still around and would like to make this change yourself and have me review, I'd appreciate it.

If you do, please add a comment here before you start so I don't duplicate work.

**Comment by adferrand** [comment]
@bmw I do that.

**Comment by adferrand** [comment]
Superseeded by #7300.

**Comment by bmw** [comment]
Thanks Adrien. It's been a busy day.

**Pull request closed without merging**
