### PR TITLE
Convert `valid_csr` and `csr_matches_pubkey` to use cryptography's APIs

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Hmm, so this relies on `==` working on public keys, which was first introduced in cryptography 41.0.0 (released in May, 2023). The current minimum version is 3.2.1 (October, 2020).

Would raising the minimum version be acceptable?

**Comment by alex** [comment]
Ok! I've gone with a dumber version (comparing the SPKI serialization of the keys) that'll work on every version. Left a comment for future us.

**Review by bmw — APPROVED** [review]
perfect

thanks a lot for coming up with an alternative approach alex

**Comment by alex** [comment]
Credit for the alternate approach actually goes to @reaperhulk :-)

**Pull request merged**
