### PR TITLE
Bind to IPv6, fix the problem of ipv6 site cannot generate / renew certificate [revision requested]

### PR DESCRIPTION
**Pull request by palxex**
Follow the guide in https://github.com/certbot/certbot/issues/1466.

### CODE REVIEW

**Comment by pde** [comment]
This is failing unit tests, so will obviously need some more work...

**Comment by nomaster** [comment]
The patch works for me. Thank you!

**Comment by bmw** [comment]
This patch will work on systems with IPv6 support, but will fail on those without. Since this solution isn't quite enough and it's failing tests, I'm closing this PR in favor of the more complete #3687.

**Comment by jsha** [comment]
@bmw are you sure this will fail on systems without IPv6? I just tested this patch on my IPv4-only system and found that it successfully bound to a port that I could then connect to:

```
~/certbot/acme/examples/standalone $ python ~/certbot/acme/acme/standalone.py
INFO:__main__:Serving at https://:::33510...
```

Or is the issue systems that don't understand the IPv6 address family at all (regardless of whether they have an address)?

**Comment by bmw** [comment]
Interesting! It's not clear to me why that works if the underlying OS doesn't have IPv6 support. Other problems with an approach like this though are:

1. Python can be compiled without IPv6 support.
2. Some systems such as the BSDs don't map IPv4 traffic to IPv6. A patch like this would make standalone unusable for people on these systems relying on IPv4.

**Comment by jsha** [comment]
To be clear, I haven't tested it on an OS without IPv6 support; I tested it on a host with IPv6 support but no IPv6 address.

**Comment by cmcqueen** [comment]
You would need to test on a kernel compiled without IPv6 support. Perhaps you would need to compile your own kernel for testing. For example, I've got an embedded Linux BeagleBone Black based system with IPv6 disabled in the kernel.

**Comment by cmcqueen** [comment]
A more cross-platform solution would be to open separate IPv4 and IPv6 listeners, and to abort only if both of them fail to open.

**Comment by higuita** [comment]
Just to help people until this is really fixed:

If you have ipv6 and certbot is failing , use this patch (https://github.com/certbot/certbot/pull/3369.diff) and it will work.

This is not the long term solution, but fix the problem until #3687 finished and applied

**Pull request closed without merging**
