### PR TITLE
Setup CI system for Python3.9

### LINKED ISSUE #8134: Add tests against Python 3.9 and claim support for it in our packages
We should at least do this once it is released which the [release schedule](https://www.python.org/dev/peps/pep-0596/#release-schedule) expects to be October 5th.

As of writing this, Azure Pipelines does not offer a prerelease version of Python 3.9. You can check the included software on each OS in Azure at https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software.

### PR DESCRIPTION
**Pull request by adferrand**
Fixes #8134

I also take the occasion to realign the Python version used when no specific version of Python is required.

### CODE REVIEW

**Comment by bmw** [comment]
Especially since tests of certbot-auto on CentOS 6 failed here, I personally prefer https://github.com/certbot/certbot/pull/8401, but we can see how the review on that goes.

You can close this if you want, but I'm just assigning us for now so it doesn't show up in the [list of Certbot issues and PRs we use for triage](https://github.com/issues?q=is%3Aopen+no%3Alabel+no%3Aassignee+user%3Acertbot+user%3Acertbot-docker+).

**Comment by adferrand** [comment]
The latest commit is not meant to stay. It was just to verify proactively if upgrading setuptools solves the problem with Python 3.9.

Once your PR is merged (I think it will) to provide a new pipstrap, I think we can continue with this PR that will be unblocked thanks to upgraded set of pip/setuptools/wheel.

**Comment by bmw** [comment]
OK. Just so you know, I assigned myself https://github.com/certbot/certbot/issues/8134 on Wednesday, started working on this then, and have made quite a bit of progress. I just wrote up where things currently stand at https://github.com/certbot/certbot/issues/8134#issuecomment-715618364.

**Comment by adferrand** [comment]
OK. Let's continue on your work then.

**Pull request closed without merging**
