### PR TITLE
Json certificate output (#3909)

### PR DESCRIPTION
**Pull request by dashaxiong**
This PR isn't for merging, it is for code review only. I plan to submit another PR with JSON and Grep certificates output which will clone from this branch. There is some redundant code in `cert_manager.py:_old_describe_certs` and `_report_human_readable` which are left there so another set of eyes can look over and make sure I haven't missed anything in the refactoring. I will delete the redundant code on the new branch.

A [helpful script](https://gist.github.com/dashaxiong/be08f8ac0e8d1e584b3a9d3ac1abcfe2) which when run against a local boulder instance, will show the output of the certificates subcommand.

This PR also excludes two test files from being counted in test coverage. Not sure of best practice, but on the face of it, checking coverage of test files seems like it could lead to a nasty recursion in testing practice. i.e. it seems to assume writing tests for tests ... for tests ... and so on. I wouldn't have brought it up, but `tox -e cover` complained that those two test files weren't up to the coverage standard.

### CODE REVIEW

**Comment by pde** [comment]
We have a backlog of PRs before the 0.11.0 release so we probably won't get to this one until next week.

**Comment by bmw** [comment]
@ohemorange, would you like to take a look at this?

**Comment by ohemorange** [comment]
Ooh, exciting! I have a few other things on my queue, and I know @pde was excited about getting this in, but if I get through those I'll look at this one.

**Comment by ynasser** [comment]
Thanks for this PR, @dashaxiong :)

I have some questions/comments before I begin an in-depth review.

Could you elaborate on this: 
>This PR isn't for merging, it is for code review only

Also, we recently decided that we don’t want #3910 as a feature.

> There is some redundant code in cert_manager.py:_old_describe_certs and _report_human_readable which are left there so another set of eyes can look over and make sure I haven't missed anything in the refactoring. 

I don’t see any functions named `_old_describe_certs` in your PR.

Also, some of the code you’ve refactored was just modified/refactored in #4202, so it might be best to wait until those changes have been merged and work off of that.

**Comment by ynasser** [comment]
Regarding excluding our tests from coverage checking and best practices, @SwartzCr do you have any opinions? Checking `.coveragerc` in master, we don’t seem to do this, but maybe we should start if it’s incorrectly measuring test coverage (I don’t actually know)?

**Comment by SwartzCr** [comment]
@ynasser I think @bmw would have better opinions on test coverage than I would

**Comment by bmw** [comment]
I don't think the changes to `.coveragerc` are necessary. While `tox -e cover` reports the coverage percentage for each file, it's only requiring you meet a minimum percentage for the entire `certbot` module looked at as a whole.

As for writing tests so other tests have coverage, the tests is the code that `tox -e cover` runs. It runs the tests and reports coverage on them and the code it calls. You don't need to write tests to call the tests so they get coverage because the tests are run directly by `tox`.

**Comment by ohemorange** [comment]
lol fun fact! `main_test` has some assertions in it that aren't hit normally (which is expected and good), leading to less than 100% test coverage in our test code, which drives down our overall percentage slightly. A quick fix would be changing coveragerc to reflect this perfectly normal behavior; a better fix would be better test coverage for files in the orange that actually need it.

**Comment by bmw** [comment]
For cases like that I usually do things like [this](https://github.com/certbot/certbot/blob/c952af5c6a4f5ef566b4a18ab0c20044cac64a9d/certbot/tests/log_test.py#L99), but I don't expect newer devs to know how to do that. I think this is a pretty unusual case though and I personally think we can worry more about it when/if lines like that are the reason we don't have 100% test coverage in Certbot.

**Comment by dashaxiong** [comment]
@ynasser I must have removed `old_describe_certs`, it was simply the old function prior to being modified for use with the `Formatter` class.

The reason I was asking for code review was to get some feedback on the changes made here. Proceeding cautiously, as I have refactored the code to use an OO approach. This is perhaps less useful if there are only going to be two output formats now that #3910 has been discontinued. But I was aiming for a simple way to add additional output formats.

**Comment by ynasser** [comment]
@dashaxiong Ah, thanks for the explanation. Your OO approach makes a lot of sense in retrospect, but since we've decided to only have one extra output format, we'd prefer a simpler approach. Sorry for not firming up the requirements earlier and causing you some extra work! If you'd like to keep working on this, shall I assign you #3909? I can also ping you when #4202 lands.

**Comment by bmw** [comment]
Since this hasn't seen any progress in over a month, I'm closing this PR for now. Feel free to reopen when it's ready for another review!

**Comment by ynasser** [comment]
I'll ping @dashaxiong when #4202 lands (which this is waiting on) and they can re-open this then.

**Comment by bmw** [comment]
Oh! I didn't realize this PR was blocked. Feel free to reopen if you like.

**Comment by SwartzCr** [comment]
I'm going to re-open this, and get my thing unblocked

**Comment by ynasser** [comment]
@SwartzCr It's blocked because of me, and resolving it is going to take a while.

**Comment by SwartzCr** [comment]
oh - okay, well it should still stay open, IMO

**Comment by bmw** [comment]
That's fine. I've been closing PRs that have been abandoned by their authors and putting a link to the closed PR in the relevant issues, but this can stay open until #4202 lands.

**Comment by dashaxiong** [comment]
@ynasser happy to get back into this once #4202 has landed. Sorry I haven't been too active on this lately, started a new job.

**Comment by ynasser** [comment]
Hi @dashaxiong! #4914 (formerly #4202) has landed, so you can get back to this now! :)

**Comment by SwartzCr** [comment]
Any progress on this?

**Comment by abcarroll** [comment]
Hate to ask again, but any progress with this? 

We have a pretty serious economic interest in seeing this merged in.  If there is anything specific an average joe could do to help get this completed, I'll see what I can do.

**Comment by jgillula** [comment]
Hi @dashaxiong ! Since we haven't seen any activity on this PR for a while, I just wanted to check and see if you still planned to work on it, or if you'd be OK with someone else picking up the work.

**Comment by bmw** [comment]
We haven't seen any updates here in a while so I'm going to go ahead and close this PR, but I put the code here in https://github.com/certbot/certbot/tree/dashaxiong-json-certificate-output and added a reference to it in #3909 so it can be built off of.

@dashaxiong, if you want to pick this back up, you're more than welcome to open a new PR, but regardless, thanks for the contribution!

**Pull request closed without merging**
