### PR TITLE
Remove win2016 from Azure devops pipelines.

### PR DESCRIPTION
**Pull request by atombrella**
From March 2022, support will be removed.
https://github.com/actions/virtual-environments/issues/4312

## Pull Request Checklist

- [x] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [x] Add or update any documentation as needed to support the changes in this PR.
- [x] Include your name in `AUTHORS.md` if you like.

### CODE REVIEW

**Review by adferrand — APPROVED** [review]
Thanks!

**Comment by alexzorin** [comment]
The packaging tasks for Server 2019 and 2022 aren't passing at the moment.

I wonder why? [The output](https://dev.azure.com/certbot/certbot/_build/results?buildId=4957&view=logs&jobId=34774c76-79f0-5cdc-0189-8b9466f67aab&j=34774c76-79f0-5cdc-0189-8b9466f67aab&t=0036cd62-29fa-5bb1-ac7e-40c326e42794) is:

>##[error]Version spec 3.9 for architecture x86 did not match any version in Agent.ToolsDirectory.
Versions in /opt/hostedtoolcache:
>
>2.7.18 (x64)
3.10.1 (x64)
3.5.10 (x64)
3.6.15 (x64)
3.7.12 (x64)
3.8.12 (x64)
3.9.9 (x64)

but the software list for that image (https://github.com/actions/virtual-environments/blob/99eda5a423543bb428e7cb04f4fff2d5e8956b00/images/win/Windows2019-Readme.md#python) includes Python 3.9 for both architectures.

Or do you only get the Python that matches the image architecture, which is x64?

**Comment by atombrella** [comment]
> The packaging tasks for Server 2019 and 2022 aren't passing at the moment.

Yes, I also noticed :cry: 
 
> I wonder why? [The output](https://dev.azure.com/certbot/certbot/_build/results?buildId=4957&view=logs&jobId=34774c76-79f0-5cdc-0189-8b9466f67aab&j=34774c76-79f0-5cdc-0189-8b9466f67aab&t=0036cd62-29fa-5bb1-ac7e-40c326e42794) is:
> 
> > ##[error]Version spec 3.9 for architecture x86 did not match any version in Agent.ToolsDirectory.
> > Versions in /opt/hostedtoolcache:
> > 2.7.18 (x64)
> > 3.10.1 (x64)
> > 3.5.10 (x64)
> > 3.6.15 (x64)
> > 3.7.12 (x64)
> > 3.8.12 (x64)
> > 3.9.9 (x64)
> 
> but the software list for that image (https://github.com/actions/virtual-environments/blob/99eda5a423543bb428e7cb04f4fff2d5e8956b00/images/win/Windows2019-Readme.md#python) includes Python 3.9 for both architectures.
> 
> Or do you only get the Python that matches the image architecture, which is x64?

I'm not sure if the right thing would've been to use `-latest` instead. I'm learning different things when doing the PRs.

**Comment by adferrand** [comment]
Well, that is unfortunate. Indeed both architectures were available in the previous windows image, but it seems that the recent versions 2019 and 2022 get only the Python architecture of the actual image one.

I think we have these options:
* manually install Python from the relevant installer downloaded from Internet instead of using the Python install action
* tweak the agent pool to enforce 32bits on the Windows agents
* switch to 64bits on the Windows installer

I have a slight preference on the last one because I do not think that it is really relevant anymore to serve a 32bits flavor on Windows in 2022, and it keeps the pipeline configuration with no custom workarounds.

**Comment by adferrand** [comment]
By the way, I missed something in the pipeline configuration with this PR.

In fact we do not need to run the installer_build job on two different versions of Windows. We just need to build it once and run it on all supported versions of Windows.

**Pull request merged**
