### PR TITLE
Support for Synology-like systems with busybox [revision requested]

### PR DESCRIPTION
**Pull request by kenkendk**
Added support for detecting system where "command -v" fails, but "which" works instead (i.e. Synology)

### CODE REVIEW

**Comment by pde** [comment]
This is not sufficient to support busybox's non-POSIX `sh`.  You will need to replace all instances of `VAR={$VAR:-$DEFAULTVALUE}` with something like `if [ "$VAR" = "" ] ; then VAR="$DEFAULTVALUE" ; fi`.  Please work on top of the pending changes in #1665 if you're planning to attempt that.

**Comment by kenkendk** [comment]
I guess that depends on what you need to support. 
The current version works on Synology, but if you would like a version that does not use the `{$VAR:-$DEFAULT}` syntax, I can make that.

**Comment by pde** [comment]
@kenkendk thanks.  In my testing `busybox sh` would mangle environment variables when it hit those expressions.

**Comment by pde** [comment]
We will review and test this after #1665 has landed.

**Comment by erikrose** [comment]
#1665 has now landed, so this is ready to be rebased on the latest master. There will also be some porting working involved.

**Comment by kenkendk** [comment]
I have re-applied the patch.
The space-in-path handling fixes were part of master, so I just added the `which` check and the `VarOrDefault` from my patch.

I have not tested it on my box yet, will do asap.

**Comment by kenkendk** [comment]
I have tested now, and it works on my box.

The Travis error is unrelated to the fix, it has a 500 error from the server in one of the build configs. If you can resubmit the job, I am sure it will pass. I can also make a bogus commit to trigger the Travis if you prefer.

**Comment by bmw** [comment]
I'm sorry this sat around so long @kenkendk. If you want to bring this PR up to date so that it works with busybox, I'll happily review.

**Comment by kenkendk** [comment]
Ok, I will close this and create a new PR where all the history is gone, as it is really a simple fix.

**Pull request closed without merging**
