### PR TITLE
Adding Atomic Hooks - Fixing Spacing

### PR DESCRIPTION
**Pull request by bobstrecansky**
Refactored after IRC talk.
@ohemorange - Just wanted to do one of these before I went though and fixed all of these to be atomic.  Is this what you were looking for?  The test suite passes, so i'd think this is ok, but i'll defer to you.

### CODE REVIEW

**Comment by bobstrecansky** [comment]
I think this is what you want @ohemorange - can you take a look when you have a minute?

**Comment by zjs** [comment]
I'm not @ohemorange, but I think the goal of #4319 is to ensure that operations involving `os.path.exists` work as expected even when other operations are happening concurrently.

Consider this excerpt from `storage.py`:

```135) def rename_renewal_config(prev_name, new_name, cli_config):
136)     """Renames cli_config.certname's config to cli_config.new_certname.
137) 
138)     :param .NamespaceConfig cli_config: parsed command line
139)         arguments
140)     """
141)     prev_filename = renewal_filename_for_lineagename(cli_config, prev_name)
142)     new_filename = renewal_filename_for_lineagename(cli_config, new_name)
143)     if os.path.exists(new_filename):
144)         raise errors.ConfigurationError("The new certificate name "
145)             "is already in use.")
146)     try:
147)         os.rename(prev_filename, new_filename)
148)     except OSError:
149)         raise errors.ConfigurationError("Please specify a valid filename "
150)             "for the new certificate name.")
```

Currently, we check whether the `new_filename` is in use on line 143 before renaming a file to that name on line 147. However, some concurrent operation could create a file with `new_filename` between when `os.path.exists` is evaluated on line 143 and when `os.rename` is evaluated on line 147, causing us to overwrite a file ― the very thing we're trying to protect against on line 143.

On newer versions of Python, I think `os.replace` might be helpful here. However, I'm not sure what the best practice would be for the set of versions we support.

**Comment by ohemorange** [comment]
Yup, that's exactly right.

@bobstrecansky you may want to check out https://blogs.msdn.microsoft.com/pythonengineering/2016/06/29/idiomatic-python-eafp-versus-lbyl/ for further reading about this

@zjs the issue is that `os.replace` and `os.rename` will both happily rename `prev_filename` to `new_filename`, even if `new_filename` already exists.

**Comment by zjs** [comment]
> @zjs the issue is that `os.replace` and `os.rename` will both happily rename `prev_filename` to `new_filename`, even if `new_filename` already exists.

You're right; I mis-remembered and thought `os.replace` raised an error if the target existed.

**Comment by bobstrecansky** [comment]
Thanks for the pointers @zjs and @ohemorange - i'll get to this PR later on this weekend / next week.

**Comment by bmw** [comment]
@bobstrecansky, I just wanted to check in since it's been over a month since we've seen any activity from you here. Are you still planning on working on this?

**Comment by bobstrecansky** [comment]
@bmw - yup, was just focusing on my other PR before getting to this one.

**Comment by bobstrecansky** [comment]
Picking this back up; apologies for the delay.

**Comment by bobstrecansky** [comment]
Sorry @ohemorange - closed!

**Pull request closed without merging**
