### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by bmw**
Fixes https://github.com/certbot/certbot/issues/9892 and https://github.com/certbot/certbot/security/dependabot

Upgrading the base docker image has been done in previous PRs like https://github.com/certbot/certbot/pull/9415. Doing this was needed because the [newer versions of `cryptography` need a newer version of rust](https://dev.azure.com/certbot/certbot/_build/results?buildId=7451&view=logs&j=fdd3565a-f3c6-5154-eca9-9ae03666f7bd&t=5dbd9851-46a4-524f-73a8-4028241afcde&l=475).

I ran the full test suite on this branch which you can see in the GitHub status checks below. The boulder tests should fail as they're to be fixed by https://github.com/certbot/certbot/pull/9889 but everything else should pass.

### CODE REVIEW

**Comment by ohemorange** [comment]
Happy to accept these changes, but out of curiosity why was libssl upgraded in the first test but not anymore? Or was that what was breaking, and not the alpine 3.18 vs 3.19?

**Comment by bmw** [comment]
libssl was what was breaking things I believe. [alpine 3.18 and 3.19 are both still supported](https://www.alpinelinux.org/releases/), but 3.19 only has openssl 3.0+. alpine 3.18 still has openssl 1.1 and after downgrading to 3.18 and that version of openssl, cryptography actually manages to build.

**Comment by bmw** [comment]
to clarify, I suspect it was the libssl change, but I don't actually know that. either change could have fixed things. all I know is this one seems to work and [the other one hung for 3 hours with no significant output](https://dev.azure.com/certbot/certbot/_build/results?buildId=7454&view=logs&j=fdd3565a-f3c6-5154-eca9-9ae03666f7bd&t=5dbd9851-46a4-524f-73a8-4028241afcde)

**Comment by ohemorange** [comment]
Works for me, though we should probably actually do that upgrade and get dependencies in order at some point, probably worth making an issue to track that.

**Review by ohemorange — APPROVED** [review]
Code looks good, but we should wait until docker test finishes running before merging

**Comment by bmw** [comment]
kk. I created https://github.com/certbot/certbot/issues/9894.

**Pull request merged**
