### PR TITLE
OS umask Context Manager

### PR DESCRIPTION
**Pull request by Mercerenies**
This PR addresses #7992, creating a context manager in `certbot.util` and implementing its use in the places the `os.umask` / `finally` pattern is used in the current codebase.

## Pull Request Checklist

- [ ] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [ ] Include your name in `AUTHORS.md` if you like.

### CODE REVIEW

**Comment by Mercerenies** [comment]
Python 2 seems to be acting up when I try to import `certbot.util` in those files. Python 3 is fine with it. In the `filesystem.py` case, it seems to be some kind of circular import issue (`certbot.util` imports `certbot._internal.lock`, which imports `certbot.compat.filesystem`, which tries to import `certbot.util`). Not sure what `http_01.py` is doing. I'll take another look at it.

```
====================================================== ERRORS ======================================================
__________________________________ ERROR collecting certbot/tests/account_test.py __________________________________
ImportError while importing test module '/home/silvio/Documents/python/certbot/certbot/tests/account_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
certbot/tests/account_test.py:15: in <module>
    from certbot.compat import filesystem
certbot/certbot/compat/filesystem.py:9: in <module>
    from certbot import util
certbot/certbot/util.py:25: in <module>
    from certbot._internal import lock
certbot/certbot/_internal/lock.py:7: in <module>
    from certbot.compat import filesystem
E   ImportError: cannot import name filesystem
```

**Comment by bmw** [comment]
To fix the Travis failures, you need to update [this line](https://github.com/certbot/certbot/blob/cc07722b3ebe2c733c20159487acd7c87ce42d79/certbot-apache/setup.py#L15) to `certbot>=1.6.0.dev0` and [this line](https://github.com/certbot/certbot/blob/cc07722b3ebe2c733c20159487acd7c87ce42d79/certbot-apache/local-oldest-requirements.txt#L3) to `-e certbot[dev]`.

Whats going on here is the tests are trying to run `certbot-apache` with the oldest version of `certbot` it claims to support which is currently version 1.1.0, but this version doesn't have `certbot.util.os_umask` being added in this PR. Updating the minimum required version should solve this problem.

Documenting how all this works is tracked by https://github.com/certbot/certbot/issues/7647.

**Comment by kden** [comment]
@bmw are you saying we add in that change to that line to the pull request even though it might affect things beyond #8020?

**Comment by bmw** [comment]
I'm not entirely sure what you have in mind when you say it might affect things beyond this PR, but yes, I think the changes I described should be made in this PR. This PR is making our Apache plugin require the latest version of Certbot which I think is the best approach, but tests will fail until the Apache plugin's dependencies are updated to state this.

**Pull request closed without merging**
