### PR TITLE
Update Pylint to 1.8.4

### LINKED ISSUE #5904: Address linter issues from using upgraded pylint
https://travis-ci.org/certbot/certbot/jobs/368515187 (from #5727)

Using a new version of pylint finds new issues. Let's clean them up! Log is in the link above, or attached below.

[pylint.txt](https://github.com/certbot/certbot/files/1953257/pylint.txt)

### PR DESCRIPTION
**Pull request by jepayne1138**
Upgrade pylint and resolve or disables resulting warnings

I made some subjective decisions on where to just disable new linter errors instead of updating the code where I thought that changes would result in worse code clarity.  Let me know if you have a different opinion on how to resolve any of the necessary changes and I'll see what I can do.

Resolves #5904

### CODE REVIEW

**Comment by bmw** [comment]
Looks like there's some merge conflicts here. Let me know if you'd like help resolving them!

**Comment by bmw** [comment]
@sydneyli, you could review this if you want. For context, this builds off of #5727 and fixes the lint failures that come up so this PR can be merged.

Because this PR has multiple authors, we can't squash the PR like normal and preserve authorship, so I had @jepayne1138 squash things down to individual commits per author so we can simply merge the PR while keeping history clean. If you take this, totally up to you how you want to recommend @jepayne1138 handles this with follow up commits for you to review, I'd just prefer we squash things down before finally merging.

I just asked Erica if she was 100% happy with that PR at https://github.com/certbot/certbot/pull/5727#issuecomment-393300869 so if the first commit here and that PR are identical, we can just review the 2nd commit.

Because this PR affects so much of the code base and a lot of stuff was landing at PyCon, @jepayne1138 offered to handle merge conflicts when they come up, but it might be good to give him initial feedback first so he can fix any issues and merge conflicts at the same time and we can get this merged before more conflicts come up.

**Comment by sydneyli** [comment]
I'll continue chewing on this review in my off-time, but probably won't have it completed this sprint.

**Comment by ohemorange** [comment]
Hey @jepayne1138 ! Any chance you could finish this up by making the change described at https://github.com/certbot/certbot/pull/5727/files/2991813b1dd582de8c0cd19f4852811a1f46ac3f#diff-b91f3d5bd63fcd17221b267e851608e8 ? Essentially instead of putting it in a hardcoded pip install, those dependencies should just be specified in `tools/dev_constraints.txt`.

**Pull request merged**
