### PR TITLE
Dns-google: update permissions needed in documentation

### PR DESCRIPTION
**Pull request by tJouve**
## Change in certbot-dns-google documentation to : 
- add permission for transaction creation => dns.managedZones.get
- add permission for RR removal transaction => dns.changes.list

## Pull Request Checklist

- [x] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [x] Add or update any documentation as needed to support the changes in this PR.
- [x] Include your name in `AUTHORS.md` if you like.

### CODE REVIEW

**Comment by alexzorin** [comment]
Hi @tJouve,

Thanks for opening this PR. 

As far as I can tell, the Google DNS plugin requires neither of these permissions. At least, not when using a Service Account.

If you encountered trouble using the plugin, would you be able to post more information about how you have things set up, Certbot logs, error messages etc?

Thank you.

**Review by mtdcr — APPROVED** [review]
I can confirm, these permissions are required, even with a service account.

**Comment by mtdcr** [comment]
Certbot output without these permissions:
~~~
Requesting a certificate for [redacted]
Encountered 403 Forbidden with reason "forbidden"
Encountered error adding TXT record: <HttpError 403 when requesting https://dns.googleapis.com/dns/v1/projects/[redacted]/managedZones/[redacted]/changes/[redacted]?alt=json returned "Forbidden". Details: "[{'message': 'Forbidden', 'domain': 'global', 'reason': 'forbidden'}]">
~~~

**Comment by tJouve** [comment]
Thanks @mtdcr for the output.

Without thoses permissions gcloud denied modifications.

The last commit just resolve merge conflict on release notes informations

**Review by alexzorin — APPROVED** [review]
Since this has more than one confirmation and it is a documentation change only, I am going to merge this. Thank you.

**Pull request merged**
