### PR TITLE
Fixes #6972 by updating lexicon to latest version

### LINKED ISSUE #6972: Unable to determine zone identifier
Just wanted to leave a note saying that using the dns-linode plugin, my zone identifier started with a capital letter, which caused the whole thing to choke with the "Unable to determine zone identifier" error message. When I went to linode console and changed the zone name to a lowercase letter, it worked correctly. Capitalizing the commands didn't make a difference. Had to do it from the linode dns manager side.

### PR DESCRIPTION
**Pull request by trinopoty**
This PR updates the lexicon dependency to v3.3.11 which has the fix for #6972 .

### CODE REVIEW

**Comment by trinopoty** [comment]
@sreyemnayr Would it be possible for you to test out this PR?

**Comment by alexzorin** [comment]
This would additionally resolve:

- #7411, fixed in Lexicon v3.3.4.
- #7425, fixed in Lexicon v3.3.6

**Comment by trinopoty** [comment]
@alexzorin If the dependency in dev_constraints.txt overrides the plugin's dependency after deployment, that would be the case. However, I'm not aware if it does so I can't say.

**Comment by alexzorin** [comment]
Ah, I should have looked at the PR more closely. Sorry :) !

**Comment by trinopoty** [comment]
I can integrate #7411 and #7425 into here or in a different PR if updating the dependency is the only thing that needs to be done.

**Comment by trinopoty** [comment]
`py34` can't find `dns-lexicon==3.3.11`. Any fix for that?

**Comment by alexzorin** [comment]
It seems that [v3.3.5 was the last version to support Python 3.4](https://github.com/AnalogJ/lexicon/commit/d0f6b0b5b3bb292075508f545ff1479d55a487a1#diff-2eeaed663bd0d25b7e608891384b7298R80) and it's restricted in newer releases. cc @adferrand

**Comment by bmw** [comment]
This is both a bit tricky for us to fix and for me to explain why.

I don't really want to update the requirement in `setup.py`. I think the main effect it would have is to completely break the plugin with older versions of Lexicon and it would prevent some Linux distros from being able to package this plugin at all. Certbot packages often see updates in distros where they are unable to update libraries because they may be used by other software. I personally think a Linode plugin that doesn't work with capitalized zone names is better than no Linode plugin at all. We could add a comment in `setup.py` explaining that v3.3.11 is preferred though.

The one place where our users would see an effect by updating the pinning in `dev_constraints.txt` is in our [docker image](https://hub.docker.com/r/certbot/dns-linode). Unfortunately, the way our system of pinnings currently works is the same versions are mostly used everywhere and we can't update the lexicon version until we drop Python 3.4 support. We've been trying to do this for a while and are planning on doing it after our next release. This is blocked by https://github.com/certbot/certbot/issues/7007.

So we could tweak the system of pinnings a bit allowing us to do something like only run with an older version of Lexicon when testing on Python 3.4, but I think I'd prefer waiting until we've dropped Python 3.4 support and updating this pinning globally for our setup.

**Comment by trinopoty** [comment]
@bmw Should I close this PR? I can open another one when Python 3.4 support is dropped with the then latest lexicon release if needed.

**Comment by bmw** [comment]
Either way is fine with me! I created https://github.com/certbot/certbot/issues/7631 and put it in our 1.2.0 milestone to make sure we don't forget about this.

**Pull request closed without merging**
