### PR TITLE
Remove docker-compose dependency

### PR DESCRIPTION
**Pull request by bmw**
This is progress towards https://github.com/certbot/certbot/issues/9370 as discussed at https://github.com/certbot/certbot/pull/9435.

I kept the command using `docker-compose` because `docker compose` doesn't seem that widely recognized yet and https://www.docker.com/blog/announcing-compose-v2-general-availability/ describes aliasing `docker-compose` to `docker compose` on newer systems by default.

### CODE REVIEW

**Review by alexzorin — APPROVED** [review]
Do you know what the difference is between [this log](https://dev.azure.com/certbot/ba534f81-a483-4b9b-9b4e-a60bec8fee72/_apis/build/builds/5983/logs/286) and [this log](https://dev.azure.com/certbot/ba534f81-a483-4b9b-9b4e-a60bec8fee72/_apis/build/builds/5981/logs/55)? Is it that `pytest` decided to run one of them in parallel, so we drop all the output from Docker/Boulder and Certbot?

This change LGTM modulo the question above, but that is probably unrelated to this PR.

**Comment by bmw** [comment]
I'm glad you asked this question!

The reason for the difference is my commit [here](https://github.com/certbot/certbot/commit/a82dc945aa1b7a5c04ba95d2d4006e481bccd693) causing `sys.stdout` to always be used and changing the flags passed to `pytest`. To make sure things look similar, I cherry-picked that commit onto this code, ran it at https://dev.azure.com/certbot/certbot/_build/results?buildId=5986&view=results, and was very disappointed to find that [we have the same problem trying to kill the `docker-compose logs` process](https://dev.azure.com/certbot/certbot/_build/results?buildId=5986&view=logs&j=c121f918-31e1-5a38-5825-6d6cfbed40ca&t=360ef6cc-e78a-544f-50f9-385ea532dee3&l=37791). I hate it, but I appreciate you catching this.

I think my preferred way to fix this is during shutdown to check `process.args` before calling `terminate` and if it contains something like `docker-compose logs`, nuke it more aggressively by calling [kill](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.kill) which I've confirmed works in Azure Pipelines. What do you think? Would you prefer a different approach?

**Comment by bmw** [comment]
I came up with an approach I personally like better that lets everything shutdown cleanly. This approach does cause the `boulder` directory to be deleted earlier in the shutdown process, but I think that's fine because `docker-compose down` has already returned.

I'm also testing this with the same changes causing more verbose output at https://dev.azure.com/certbot/certbot/_build/results?buildId=5991&view=results.

**Review by alexzorin — APPROVED** [review]
Nice, nice nice nice. Clever and clean. LGTM.

**Pull request merged**
