### PR TITLE
 Declare Python 3.12 support and add tests #9779 

### PR DESCRIPTION
**Pull request by jmg0**
## Pull Request Checklist

- [x] The Certbot team has recently expressed interest in reviewing a PR for this. If not, this PR may be closed due our limited resources and need to prioritize how we spend them.
- [x] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [x] Add or update any documentation as needed to support the changes in this PR.
- [x] Include your name in `AUTHORS.md` if you like.

### CODE REVIEW

**Comment by bmw** [comment]
The unit test failures seem partially/entirely related to https://github.com/dateutil/dateutil/issues/1314. To fix that, we can ignore the warning in `pytest.ini` in the root of this repo.

The lint failures are trickier... Ideally, I think we'd [update the pinned `pylint` version](https://eff-certbot.readthedocs.io/en/latest/contributing.html#updating-dependency-versions), but I unfortunately expect that to be a fair bit of work. If you want to try and do that, it'd be much appreciated, but instead for now we could configure CI to run our lint tests with an older version of Python. If we did this workaround, I think we should create a new issue for us to track coming up with a more robust fix here though.

**Comment by bmw** [comment]
I did the work to upgrade pylint myself at https://github.com/certbot/certbot/pull/9839.

**Comment by mrtyson93** [comment]
nice

**Comment by bmw** [comment]
Closing this in favor of https://github.com/certbot/certbot/pull/9852.

**Pull request closed without merging**
