### PR TITLE
Allow specify revocation reason

### PR DESCRIPTION
**Pull request by dashaxiong**
This adds a feature to specify the reason for certificate revocation (#3242).

The reasons are the same as the user allowed reasons in `letsencrypt.boulder.revocation.reasons.go` which are a subset of the reasons specified in the ACME protocol according to RFC 5280 section 5.3.1. The only difference is that the command line input of the reasons is all lower case. This can easily be changed without consequence if a different style is preferred, as the reason is encoded as an integer code by the `cli` parser.

### CODE REVIEW

**Comment by pde** [comment]
@rolandshoemaker interested in reviewing this?

**Comment by pde** [comment]
Putting this in 1.0.0 tentatively because that's where the ticket was but I suspect this will land much sooner.

**Comment by dashaxiong** [comment]
FYI the first two commits (b083db0, 2efa1db) are also by me, but I wrote my address as 'craig at plannd.com.au', which means that github doesn't recognise it.

**Comment by rolandshoemaker** [comment]
Generally looks good to me, you may want to do a downcase on the reason arg before checking in `REVOCATION_REASONS` though so people can use either the all lowercase or IETF style reason names (i.e. `keyCompromise`).

**Comment by dashaxiong** [comment]
@rolandshoemaker it will now ignore the case of reason arguments. It's a little bit hacky. Might be better to decide on just using IETF style. 

The trouble is, it ought to have been straightforward to use the `type` argument of `argparse.add_argument` to convert the input string to lower case before the `choices` list is checked (that is the document behaviour of `argparse`). For some reason this didn't transform the input string before checking against the `choices` list, so I have made a `CaseInsensitiveList` to pass to `choices`.

**Comment by dashaxiong** [comment]
@rolandshoemaker I looked into the command line argument handling. It turns out that `configargparse.ArgParser` is called a first time, in which the `type_func` is applied to the input prior to being compared to the `choices` array. It is also called a second time, by `cli.set_by_cli` and the `reconstructed_args` are passed to it, but on the second run the `type_func` is not applied. I have commented the CaseInsensitiveList to explain briefly why it is necessary for use with `choices` parameter. Ready for review.

**Comment by dashaxiong** [comment]
I'm closing this pull request as I am not happy with the commit history, and I am uncertain what effect `git filter-branch` will have given that I have merged in from master several times. I have opened another PR (#3988) with a cleaner commit history.

**Pull request closed without merging**
