### PR TITLE
add example of --renew-hook envvar values and hook script (#3502)

### PR DESCRIPTION
**Pull request by jwm**

### CODE REVIEW

**Comment by bmw** [comment]
@SwartzCr, would you like to review this?

**Comment by SwartzCr** [comment]
sorry for how long this took @jwm!
I think it's great - but I have two small nitpicks. I can merge it as soon as you respond to them!

**Comment by jwm** [comment]
@SwartzCr sure thing. I don't see where your comments are, though. Do you have a review queued up but not submitted?

**Comment by jwm** [comment]
@SwartzCr ping - can you please let me know where your comments are? I don't see them in the PR. Happy to update based on your feedback.

**Comment by SwartzCr** [comment]
omg sorry @jwm that's the second time I've done that x_x
Review is submitted - mainly I'm just asking for comment lines explaining the script.
Sorry for the delay I was ooto at the end of last week

**Comment by jwm** [comment]
@SwartzCr no worries. :smile: I updated based on your comment and rebased.

**Comment by SwartzCr** [comment]
Thanks so much! Merging this now :D

**Pull request merged**
