### PR TITLE
Adjust file paths message from Warning to Info.

### PR DESCRIPTION
**Pull request by ezekiel**
In regards to issue #2552, allow `--quiet` to squelch the message.

### CODE REVIEW

**Comment by schoen** [comment]
Thanks @ezekiel , I've asked @pde what he thinks about your solution over in the issue discussion.

**Comment by ezekiel** [comment]
I would suggest that PR #5773 is likely a better choice overall, as brings the logging functionality in-line with the output from `--help`, and would still resolve issue #2552.

**Comment by pde** [comment]
Let's take this for now.

**Comment by pde** [comment]
Closes: #2552

**Pull request merged**
