### PR TITLE
delete: warn that certificate may still be installed

### LINKED ISSUE #6734: `delete` might check if a certificate is in-use to avoid breaking web server configs
There's have been a few instances of Certbot users ending up with busted Apache/nginx configurations after using `certbot delete` against in-use certificates.

Without a sophisticated understanding of how the `apache`/`nginx` plugins work, the user couldn't  reasonably be expected to know that they need to remove these references before `delete` can be safely used.

I cannot find any user-facing documentation that identifies this limitation and risk.

Some potential approaches for mitigations:

- `delete`, when running interactively, might warn the user that they should ensure that no active configuration makes reference to this certificate. Additionally, include the same information in the help topic for `delete`. Bare minimum warning to the user. Or,
- `delete`, when running interactively, might refuse to run if there is an installer and it can use the installer plugin to identify that the certificate is in use. Requires an enhancement to `IInstaller`. Or,
- `delete` might undeploy the certificate if there is an installer, where undeploy might mean replacing with snakeoil or removing the virtual host entirely. Requires an enhancement to `IInstaller`.

### LINKED ISSUE #8755: Warn user for broken webserver configurations when deleting a certificate (after revoking)
Currently, when the user revokes a cert, it gets the following question:

https://github.com/certbot/certbot/blob/8759ccaecb69ea93c5b3c95f6af71bb9130117b1/certbot/certbot/_internal/main.py#L597-L602

Today, someone on the Community was left with a "catch 22" (broken webserver getting in the way of getting a new certificate): https://community.letsencrypt.org/t/had-to-revoke-some-certs-now-im-stuck/148574

I'm not sure what the generic cert delete command gives as a warning, but I would like to propose **adding a warning to every certificate deletion action in certbot** that it might leave your webserver configuration broken!

We've seen this quite often on the Community and not many users are aware of this fact.. Especially as certbot can perfectly do the HTTP to HTTPS transition, but is NOT able to transition back again from HTTPS to HTTP.

### PR DESCRIPTION
**Pull request by alexzorin**
Implemented in the nginx and apache installers. no-op for others.

---

Fixes #6734.
Fixes #8755.

This is a very early draft, I'm just looking for design feedback for the high level approach.

The existing interactive warning gets enhanced to:

image

### CODE REVIEW

**Comment by ohemorange** [comment]
So my main question is at a high level, what made you go for the detection option vs. the more simple first option where we say basically the same thing but use "may" and tell them to check? Personally I don't think it's too complicated of a feature to not be worth the upkeep, but if there's no marginal benefit at all then of course it's not.

Honestly, I'm pretty excited that the `_match_func/_find_location` code got to be reused, but that's no reason to make decisions I suppose.

If we do go with this, I think it might be worth specifically separating out the particular certs that we found installed. I honestly didn't even catch that we list its location at first, because to a user it's just reiterating what they asked for (which is good, but we're saying something else here). So like, list the certs, say the message, then list the found certs with their location? Or flip the last two, but either way say it again and point it out specifically.

Also, how sure are we about our ability to find the certs? Do you think it's worth printing the warning message even if we don't find any?

**Comment by alexzorin** [comment]
>what made you go for the detection option vs. the more simple first option where we say basically the same thing but use "may" and tell them to check

So my ideal is for `certbot --nginx` and `certbot delete` to be symmetrical; you don't have to futz with the webserver config and Certbot will just snakeoil the SSL vhost when deleting.

I think today, Certbot sort of drops the user in the deep end if they have to delete a certificate. If you look at the "Safely deleting certificates" header in the screenshot at #8910, the whole process feels a bit ugly and kludgey.

The detection option is an attempt to get slightly closer to that symmetry. Help the user out a little bit by warning of guaranteed danger.

Maybe in truth the options are the following, and having an in-between option is pointless:

1. Do the snakeoil thing
2. Just warn unconditionally and link to the docs in #8910.

> I honestly didn't even catch that we list its location at first

OK, that's very good to know. 

My first approach did actually list the certificates after the warning. Later, I opted for this more compact option, for the space savings. 

I have no problem at all with going back to listing the certificates twice.

> Also, how sure are we about our ability to find the certs?

When the installer was used? I can't think of a reason why it wouldn't work. It even seems resilient against random whitespace added by the user.

The other cases, such as `certonly` certificates without an `installer` set, will never be found because we don't know how to look for them. 

One potential enhancement here that I didn't go for is: when no `installer` is set for the certificate, load whatever the "default" installer is, if any, and check it for the certificate.

I am slightly less worried about `certonly` users, since they are necessarily a bit more clued in about how their server software is configure with the certificate in the first place. 

>Do you think it's worth printing the warning message even if we don't find any?

Yes, I think so.

**Comment by ohemorange** [comment]
> So my ideal is for certbot --nginx and certbot delete to be symmetrical; you don't have to futz with the webserver config and Certbot will just snakeoil the SSL vhost when deleting.

In that case, how come you decided to not go directly for that implementation?

> The other cases, such as certonly certificates without an installer set, will never be found because we don't know how to look for them.

Just a reminder here that even if the initial call was `certonly`, the `--nginx` or `--apache` flag will set the installer as well.

> One potential enhancement here that I didn't go for is: when no installer is set for the certificate, load whatever the "default" installer is, if any, and check it for the certificate.

When we use the "default" authenticator/installer, do we set that value in the renewal config?

> I am slightly less worried about certonly users, since they are necessarily a bit more clued in about how their server software is configured with the certificate in the first place.

I suspect that is not in fact true; they could, for example, just have been following a different tutorial that has you copy and paste code into your config, which they wouldn't necessarily remember or have needed to understand. But I definitely agree with the implicit statement here that we shouldn't try to remove their certificates for them, more stating that regardless of how good our automatic deletion or detection implementation is, having robust/clear instructions is still important.

Did you happen to take a look at the pr/branch of the last time we tried implementing this? I remember we ended up hitting some gotchas and...maybe revoking it and never going back? Don't quite remember. I believe that approach was more ambitious (for example, I think we tried to delete the lines rather than replace with snake oil (which I think is a much cleaner approach, great call)), so this one may not hit the same gotchas, but might be helpful to check.

**Comment by alexzorin** [comment]
> In that case, how come you decided to not go directly for that implementation?

Well, I don't really know. You had previously warned me against trying to do the full blown thing, and this ended up being my starting point.

But now I also realize that it sort of veers into the territory of having an `uninstall` verb, separate to `delete`. Maybe that requires more thought.

> Just a reminder here that even if the initial call was certonly, the --nginx or --apache flag will set the installer as well.

TIL. Well, that's even better.

>When we use the "default" authenticator/installer, do we set that value in the renewal config?

Yes.

>Did you happen to take a look at the pr/branch of the last time we tried implementing this?

Do you know where it is? I can't find it in neither the branch list nor https://github.com/certbot/certbot/pulls?q=is%3Apr+is%3Aunmerged+delete+.

**Comment by ohemorange** [comment]
> Well, I don't really know. You had previously warned me against trying to do the full blown thing, and this ended up being my starting point.
>
> But now I also realize that it sort of veers into the territory of having an uninstall verb, separate to delete. Maybe that requires more thought.

Ah yeah, I suspect I didn't realize how close the implementations would be to each other. As for the latter, it's a little weird because we are still leaving around most of the stuff, but I don't think we need to worry about that here.

>> When we use the "default" authenticator/installer, do we set that value in the renewal config?
>
> Yes.

Then we can probably treat it the same as anything else we find there, I think, no?

> Do you know where it is? I can't find it in neither the branch list nor https://github.com/certbot/certbot/pulls?q=is%3Apr+is%3Aunmerged+delete.

Unfortunately neither can I, though I spent some time searching. Ah well 🤷

**Pull request closed without merging**
